"use client";
import { BookOpenCheck, Building2, GraduationCap, KeyRound, Landmark, Settings, ShieldCheck, TestTube2, UserRoundCog } from "lucide-react";
import { useMemo, useState } from "react";
import { DBP_ROLES, DBP_ROLE_KEYS, DEMO_USERS, type DbpRole } from "../../lib/auth/roles";
const roleIcons={akademisyen:GraduationCap,abd_asd_baskani:Building2,lee_ogrenci_isleri:BookOpenCheck,enstitu_sekreteri:UserRoundCog,enstitu_yoneticisi:ShieldCheck,admin:Settings} satisfies Record<DbpRole,typeof GraduationCap>;
export function LoginPanel(){
  const[selectedRole,setSelectedRole]=useState<DbpRole>("akademisyen");
  const[loginMode,setLoginMode]=useState<"ldap"|"demo">("ldap");
  const[identity,setIdentity]=useState("");const[password,setPassword]=useState("");const[selectedDemo,setSelectedDemo]=useState("");
  const role=DBP_ROLES[selectedRole];const roleDemoUsers=useMemo(()=>DEMO_USERS.filter(user=>user.role===selectedRole),[selectedRole]);
  const selectRole=(roleKey:DbpRole)=>{setSelectedRole(roleKey);setSelectedDemo("");if(loginMode==="demo"){setIdentity("");setPassword("")}};
  const selectDemoUser=(id:string)=>{setSelectedDemo(id);const user=DEMO_USERS.find(candidate=>candidate.id===id);if(!user)return;setSelectedRole(user.role);setIdentity(user.username);setPassword(user.password)};
  const switchMode=(mode:"ldap"|"demo")=>{setLoginMode(mode);setIdentity("");setPassword("");setSelectedDemo("")};
  const submitLogin=()=>{if(loginMode!=="demo"||!selectedDemo)return;const user=DEMO_USERS.find(candidate=>candidate.id===selectedDemo);if(!user)return;window.localStorage.setItem("lee-dbp-session",JSON.stringify({name:user.name,username:user.username,role:user.role,department:user.department??"LEE"}));window.location.href="/panel"};
  return <div className="role-login-layout"><section className="role-selector" aria-label="Giriş rolü seçimi"><span className="eyebrow">YETKİ TÜRÜ</span><h1>Görevinizi seçin</h1><p>e‑Enstitü hesabınıza tanımlanmış rol ile devam edin.</p><div className="role-grid">{DBP_ROLE_KEYS.map(roleKey=>{const Icon=roleIcons[roleKey];const item=DBP_ROLES[roleKey];return <button type="button" className={selectedRole===roleKey?"role-option selected":"role-option"} onClick={()=>selectRole(roleKey)} key={roleKey}><span><Icon size={18}/></span><div><b>{item.label}</b><small>{item.description}</small></div></button>})}</div></section><section className="signin-card"><div className="login-mode-tabs"><button type="button" className={loginMode==="ldap"?"active":""} onClick={()=>switchMode("ldap")}><Landmark size={15}/>Kurumsal LDAP</button><button type="button" className={loginMode==="demo"?"active":""} onClick={()=>switchMode("demo")}><TestTube2 size={15}/>Demo Kullanıcı Seç</button></div><div className="signin-icon">{loginMode==="ldap"?<KeyRound size={22}/>:<TestTube2 size={22}/>}</div><span className="eyebrow">LEE DBP YÖNETİM ALANI</span><h2>{loginMode==="ldap"?"Kurumsal Giriş":"Demo Kullanıcı Seç"}</h2><div className="selected-role"><span>Seçili yetki</span><strong>{role.label}</strong></div>{loginMode==="demo"&&<div className="demo-picker"><label htmlFor="demo-user">Demo kullanıcı</label><select id="demo-user" value={selectedDemo} onChange={event=>selectDemoUser(event.target.value)}><option value="">Kullanıcı seçin</option>{roleDemoUsers.map(user=><option value={user.id} key={user.id}>{user.name}{user.department?` — ${user.department}`:""}</option>)}</select><small>Seçim yaptığınızda demo bilgileri otomatik doldurulur.</small></div>}<form onSubmit={event=>{event.preventDefault();submitLogin()}}><label htmlFor="identity">{loginMode==="ldap"?"T.C. kimlik numarası / kurumsal kullanıcı adı":"Demo kullanıcı adı"}</label><input id="identity" value={identity} onChange={event=>setIdentity(event.target.value)} placeholder="Kullanıcı bilginizi girin" readOnly={loginMode==="demo"}/><label htmlFor="password">Parola</label><input id="password" value={password} onChange={event=>setPassword(event.target.value)} type="password" placeholder="Parolanızı girin" readOnly={loginMode==="demo"}/><button type="submit"><KeyRound size={16}/>{loginMode==="ldap"?"LDAP ile Giriş Yap":"Demo Giriş Yap"}</button></form><p className="signin-note">{loginMode==="ldap"?"Üniversite kurumsal hesabınız LDAP servisi üzerinden doğrulanacaktır.":"Demo hesaplar yalnızca geliştirme ve eğitim amacıyla kullanılacaktır."}</p></section></div>;
}
