"use client";
import { Plus, X } from "lucide-react";
import { useMemo, useState } from "react";
import { LEE_PROGRAMS, MAIN_DEPARTMENTS, type ProgramLevel } from "../../lib/data/programs";
export function CourseCreateDialog({open,onClose,onCreated}:{open:boolean;onClose:()=>void;onCreated:()=>void}){
 const[main,setMain]=useState(MAIN_DEPARTMENTS[0]);const[level,setLevel]=useState<ProgramLevel>("Tezli Yüksek Lisans");
 const programs=useMemo(()=>LEE_PROGRAMS.filter(item=>item.mainDepartment===main&&item.levels.includes(level)),[main,level]);
 if(!open)return null;
 return <div className="course-dialog-backdrop" role="presentation"><section className="course-create-dialog" role="dialog" aria-modal="true" aria-labelledby="course-create-title"><header><div><small>ENSTİTÜ YETKİLİ İŞLEMİ</small><h2 id="course-create-title">ABD / ASD Adına Ders Ekle</h2></div><button type="button" onClick={onClose} aria-label="Kapat"><X size={17}/></button></header><form onSubmit={event=>{event.preventDefault();onCreated();onClose()}}><div className="create-course-grid"><label className="wide"><span>Ana ABD / ASD Başkanlığı</span><select required value={main} onChange={event=>setMain(event.target.value)}>{MAIN_DEPARTMENTS.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Program düzeyi</span><select required value={level} onChange={event=>setLevel(event.target.value as ProgramLevel)}><option>Tezsiz Yüksek Lisans</option><option>Tezli Yüksek Lisans</option><option>Doktora</option></select></label><label><span>İlgili ABD / ASD ve program</span><select required defaultValue=""><option value="" disabled>Programı seçin</option>{programs.map(item=><option key={`${item.department}-${item.programName}`} value={item.programName}>{item.department} — {item.programName}</option>)}</select></label><label><span>Ders kodu</span><input required placeholder="Örn. BLM 505"/></label><label><span>Ders adı</span><input required placeholder="Ders adını yazın"/></label><label className="wide"><span>Görevlendirilen akademisyen</span><select required defaultValue=""><option value="" disabled>Akademisyeni seçin</option><option>Dr. Öğr. Üyesi Ayşe Yılmaz</option><option>Prof. Dr. Mehmet Kaya</option></select></label></div>{programs.length===0&&<p className="no-program-warning">Seçilen ana ABD/ASD için bu düzeyde program bulunmuyor.</p>}<footer><button type="button" onClick={onClose}>Vazgeç</button><button className="create" type="submit" disabled={programs.length===0}><Plus size={15}/>Dersi Oluştur</button></footer></form></section></div>;
}
