"use client";

import { AlertTriangle, BarChart3, BookOpen, CalendarClock, Database, ExternalLink, FolderKanban, MapPinned, Network, PieChart, RefreshCw, Search, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { PublicSiteHeader } from "../PublicSiteHeader";
import { Bars, Donut, Empty, LineChart, Panel, SubjectBubbleMatrix, WorldHeatMap, strategicMatrix, tones } from "../article/page";
import type { CountItem, Dashboard } from "../article/page";
import { dbpPath } from "../../lib/dbpPath";

type TrDashboard = Dashboard & {
  institutionName: string;
  summary: Dashboard["summary"] & { totalProjects: number; currentYearPublications: number };
  projectGroups: CountItem[];
  projectSubjects: CountItem[];
  filterOptions: { years: string[] };
  quality: Dashboard["quality"] & { unitMethod: string; sdgMethod: string };
};
type TrRecord = { id: string; title: string; year: number; publicationTypeLabel: string; journalName: string; doi: string; languageLabel: string; accessLabel: string; citations: number; projectGroup: string; projectNumber: string; detailUrl: string; authors: Array<{ name: string }>; subjects: string[] };
type RecordResult = { documentType: "PAPER" | "PROJECT"; page: number; limit: number; total: number; totalPages: number; items: TrRecord[] };

const formatNumber = (value: number) => new Intl.NumberFormat("tr-TR", { maximumFractionDigits: 2 }).format(value || 0);
const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("tr-TR", { dateStyle: "long", timeStyle: "short" }).format(new Date(value)) : "—";

function RecordBrowser({ options }: { options: TrDashboard["filterOptions"] }) {
  const [query, setQuery] = useState("");
  const [year, setYear] = useState("");
  const [page, setPage] = useState(1);
  const [result, setResult] = useState<RecordResult | null>(null);
  const [error, setError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    const params = new URLSearchParams({ documentType: "PROJECT", search: query, year, page: String(page), limit: "20" });
    fetch(dbpPath(`/api/dbp/tr-dizin-records?${params}`), { signal: controller.signal }).then(async (response) => {
      const body = await response.json() as RecordResult | { message?: string };
      if (!response.ok) throw new Error("message" in body ? body.message || "Kayıtlar alınamadı." : "Kayıtlar alınamadı.");
      return body as RecordResult;
    }).then((body) => { setResult(body); setError(""); }).catch((reason: unknown) => { if (reason instanceof Error && reason.name !== "AbortError") setError(reason.message); });
    return () => controller.abort();
  }, [page, query, year]);
  return <section className="article-section tr-records"><div className="article-section-title"><span>09</span><div><small>DOĞRULANABİLİR PROJELER</small><h2>TR Dizin proje kayıtları</h2></div></div><div className="tr-record-toolbar projects-only"><div className="tr-record-type"><FolderKanban size={16} /><span>Projeler</span></div><label><Search size={16} /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Proje başlığı, yürütücü veya proje no ara" /></label><select aria-label="Proje yılı" value={year} onChange={(event) => { setYear(event.target.value); setPage(1); }}><option value="">Tüm yıllar</option>{options.years.map((item) => <option key={item}>{item}</option>)}</select></div>{error && <div className="quality-error"><AlertTriangle size={16} />{error}</div>}{!result && !error && <div className="quality-loading">TR Dizin proje kayıtları hazırlanıyor…</div>}{result && <><div className="tr-record-summary"><strong>{formatNumber(result.total)}</strong> proje · Sayfa {result.page}/{result.totalPages}</div><div className="tr-record-list">{result.items.map((item) => <article key={item.id}><div><small>{item.year || "—"} · {item.projectGroup || "Proje"}</small><h3>{item.title || "Başlık bilgisi bulunmuyor"}</h3><p>{item.authors.map((author) => author.name).join(", ") || "Yürütücü bilgisi bulunmuyor"}</p><span>{item.projectNumber || "Proje numarası belirtilmemiş"}</span></div><aside><b>Proje</b>{item.detailUrl && <a href={item.detailUrl} target="_blank" rel="noreferrer" aria-label="TR Dizin proje kaydını aç"><ExternalLink size={16} /></a>}</aside></article>)}</div><div className="tr-pagination"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>← Önceki</button><span>{page} / {result.totalPages}</span><button type="button" disabled={page >= result.totalPages} onClick={() => setPage((value) => value + 1)}>Sonraki →</button></div></>}</section>;
}

export default function TrDizinBibliometricsPage() {
  const [data, setData] = useState<TrDashboard | null>(null);
  const [error, setError] = useState("");
  const [retry, setRetry] = useState(0);
  useEffect(() => {
    const controller = new AbortController();
    fetch(dbpPath("/api/dbp/tr-dizin-bibliometrics"), { signal: controller.signal }).then(async (response) => {
      const body = await response.json() as TrDashboard | { message?: string };
      if (response.status === 202) throw new Error("İlk TR Dizin görüntüsü hazırlanıyor. Birkaç dakika sonra yeniden deneyin.");
      if (!response.ok) throw new Error("message" in body ? body.message || "TR Dizin göstergeleri alınamadı." : "TR Dizin göstergeleri alınamadı.");
      return body as TrDashboard;
    }).then((body) => { setData(body); setError(""); }).catch((reason: unknown) => { if (reason instanceof Error && reason.name !== "AbortError") setError(reason.message); });
    return () => controller.abort();
  }, [retry]);
  const kpis = useMemo(() => data ? [
    ["Toplam yayın", data.summary.totalPublications, "TR Dizin PAPER kayıtları"], ["H-index", data.summary.hIndex, "TR Dizin atıf profili"], ["Toplam atıf", data.summary.totalCitations, "Haftalık güncellenir"], ["Atıf / yayın", data.summary.citationsPerPublication, "Ortalama etki"], ["En yüksek atıf", data.summary.maxCitations, "Tek yayında"], ["Açık erişim", `%${formatNumber(data.summary.openAccessRate)}`, "Yayınların oranı"], ["OKÜ yazar", data.summary.authorCount, `Doğrudan eşleşme %${data.quality.authorCoverage}`], ["Dergi", data.summary.sourceCount, "Farklı yayın kaynağı"], ["Aktif eşleşen SKA", data.summary.activeSdgCount, "İçerik eşleşmesi"], ["Araştırma makalesi", data.summary.researchArticleCount, "Toplam"], ["Araştırma projesi", data.summary.totalProjects, "TR Dizin PROJECT kayıtları"],
  ] : [], [data]);
  const sdgCounts = data?.sdgs.map((item) => ({ name: `SKA ${item.id} · ${item.title}`, count: item.count })) || [];
  const unitTotal = data?.units.reduce((sum, item) => sum + item.count, 0) || 0;
  return <main className="dbp-page quality-page article-page tr-dizin-page"><PublicSiteHeader active="bibliometrics" bibliometricsSource="trdizin" /><section className="quality-hero article-hero"><div><small>TR DİZİN · ULUSAL ARAŞTIRMA PERFORMANSI</small><h1>TR Dizin Bibliyometrik Göstergeleri</h1><p>OKÜ adresli ulusal yayınların, projelerin, atıf etkisinin, konu alanlarının ve sürdürülebilirlik ilişkisinin canlı görünümü.</p></div><span><Database size={18} />TR Dizin kurumsal veri görüntüsü</span></section>
    {error && <section className="quality-error"><AlertTriangle size={18} /><span>{error}</span><button type="button" onClick={() => setRetry((value) => value + 1)}><RefreshCw size={15} />Durumu kontrol et</button></section>}{!data && !error && <section className="quality-loading">TR Dizin göstergeleri son başarılı görüntüden hazırlanıyor…</section>}
    {data && <><section className="article-source-strip"><span><Database size={16} />Kurum: {data.institutionName}</span><span><CalendarClock size={16} />Yayın verisi: {formatDate(data.lastFullHarvestAt || data.lastSuccessfulHarvestAt)}</span><span><RefreshCw size={16} />Atıflar: {formatDate(data.lastCitationRefreshAt)}</span><a href="https://search.trdizin.gov.tr/" target="_blank" rel="noreferrer">Veri kaynağı: TR Dizin <ExternalLink size={14} /></a></section>
      <section className="article-section"><div className="article-section-title"><span>01</span><div><small>GENEL BAKIŞ</small><h2>Kurumsal yayın ve proje performansı</h2></div></div><div className="article-kpis">{kpis.map(([label, value, note]) => <article key={String(label)}><span>{label}</span><strong>{typeof value === "number" ? formatNumber(value) : value}</strong><small>{note}</small></article>)}</div></section>
      <section className="article-grid two"><Panel eyebrow="ZAMAN SERİSİ" title="Yıllık yayın trendi" icon={<TrendingUp size={20} />}><LineChart data={data.yearlyPublications} label="TR Dizin yıllık yayın trendi" unit="Yayın sayısı" /></Panel><Panel eyebrow="ATIF ETKİSİ" title="Yayın yılına göre toplam atıf" icon={<BarChart3 size={20} />}><LineChart data={data.yearlyCitations} color="var(--chart-4)" label="TR Dizin yıllık atıf görünümü" unit="Atıf sayısı" /></Panel></section>
      <section className="article-grid three"><Panel eyebrow="YAYIN BİÇİMİ" title="Yayın türü dağılımı" icon={<PieChart size={20} />}><Donut data={data.publicationTypes} center={formatNumber(data.summary.totalPublications)} suffix="yayın" /></Panel><Panel eyebrow="ERİŞİM" title="Açık erişim durumu" icon={<BookOpen size={20} />}><Donut data={data.openAccess} center={`%${formatNumber(data.summary.openAccessRate)}`} suffix="açık erişim" /></Panel><Panel eyebrow="VERİ TABANI" title="TR Dizin alan veri tabanı" icon={<Database size={20} />}><Donut data={data.sourceTypes} center={formatNumber(data.summary.totalPublications)} suffix="yayın" /></Panel></section>
      <section className="article-section"><div className="article-section-title"><span>02</span><div><small>AKADEMİK BİRİMLER</small><h2>Birim bazlı yayın dağılımı</h2></div></div><div className="article-grid two embedded"><Panel eyebrow="YAYIN SAYISI" title="Doğrudan eşleşen birim yayınları"><Bars data={data.units} limit={14} /></Panel><Panel eyebrow="ORANSAL DAĞILIM" title="Birimlerin yayın payı"><Donut data={data.units} center={formatNumber(unitTotal)} suffix="eşleşen yayın" /></Panel></div><p className="quality-note">{data.quality.unitMethod}. Kapsam %{formatNumber(data.quality.unitCoverage)}; eşleşmeyen kayıtlar herhangi bir birime tahmini olarak yazılmamıştır.</p></section>
      <section className="article-section"><div className="article-section-title"><span>03</span><div><small>ARAŞTIRMACILAR</small><h2>OKÜ akademisyen toplam yayın görünümü</h2></div></div><Panel eyebrow="20 YAYIN VE ÜZERİ" title="TR Dizin kurum adresiyle eşleşen akademisyenler" icon={<Users size={20} />} className="embedded-panel">{data.authors.length ? <Bars data={data.authors} /> : <Empty>Doğrudan eşleşmeyle 20 yayın eşiğini aşan akademisyen bulunamadı.</Empty>}</Panel></section>
      <section className="article-section"><div className="article-section-title"><span>04</span><div><small>KONU ALANLARI</small><h2>TR Dizin konu kategorileri</h2></div></div><div className="article-grid two embedded"><Panel eyebrow="ALAN SIRALAMASI" title="Konu kategorileri"><Bars data={data.subjects} limit={18} /></Panel><Panel eyebrow="ALAN PAYLARI" title="Alanların oransal dağılımı"><Donut data={data.subjects} center={formatNumber(data.summary.totalPublications)} suffix="yayın" /></Panel></div></section><Panel eyebrow="YIL × ALAN × YAYIN" title="Alan bazlı yayınların yıllara göre dağılımı" className="article-wide"><SubjectBubbleMatrix data={data.subjectYearly || []} totals={data.subjects} /></Panel>
      <section className="article-section"><div className="article-section-title"><span>05</span><div><small>ORTAK ARAŞTIRMA AĞI</small><h2>Uluslararası ve ulusal iş birliği</h2></div></div><div className="article-grid two embedded article-collaboration-grid"><Panel eyebrow="DÜNYA GÖRÜNÜMÜ" title="Uluslararası iş birliği yoğunluk haritası" icon={<MapPinned size={20} />}><WorldHeatMap data={data.countries} /></Panel><Panel eyebrow="ULUSAL · İLK 10" title="Türkiye’de iş birliği yapılan kurumlar" icon={<Network size={20} />}><Bars data={data.nationalInstitutions} limit={10} /></Panel></div></section>
      <section className="article-section"><div className="article-section-title"><span>06</span><div><small>SÜRDÜRÜLEBİLİR KALKINMA</small><h2>SKA analizi</h2></div></div><div className="article-grid two embedded"><Panel eyebrow="TOPLAM YAYIN" title="SKA bazlı yayın dağılımı"><Bars data={sdgCounts} showShare /></Panel><Panel eyebrow="ORANSAL GÖRÜNÜM" title="SKA paylarının dağılımı"><Donut data={sdgCounts} center={formatNumber(data.sdgs.reduce((sum, item) => sum + item.count, 0))} suffix="yayın–SKA ilişkisi" /></Panel></div><Panel eyebrow="İYİLEŞTİRME ALANI" title="Geliştirilebilecek SKA hedefleri" icon={<Sparkles size={20} />} className="embedded-panel article-development"><p>En düşük doğrulanabilir içerik eşleşmesine sahip hedefler izleme alanı olarak listelenir.</p><div>{data.developingSdgs.map((item) => <article key={item.id}><img src={dbpPath(`/sdg/sdg_${item.id}.png`)} alt="" /><span><b>SKA {item.id}</b><small>{item.title}</small></span><strong>{formatNumber(item.count)}</strong></article>)}</div><p className="quality-note">Yöntem: {data.quality.sdgMethod}. Bu, editoryal SKA etiketi değil bibliyometrik içerik eşleşmesidir.</p></Panel></section>
      <section className="article-section article-strategy"><div className="article-section-title"><span>07</span><div><small>2025–2029 STRATEJİK PLANI</small><h2>OKÜ stratejik hedefleri bazlı yayın dağılımı</h2></div></div><div>{data.strategicGoals.map((goal, index) => <article key={goal.id}><header><span style={{ background: tones[index % tones.length] }}>{goal.id}</span><div><h3>{goal.title}</h3><small>{goal.sdgs.map((id) => `SKA ${id}`).join(" · ")}</small></div><strong>{formatNumber(goal.count)}</strong></header><i><em className={`series-${index % tones.length}`} style={{ width: `${Math.max(2, goal.count / Math.max(1, ...data.strategicGoals.map((item) => item.count)) * 100)}%` }} /></i></article>)}</div><Panel eyebrow="CANLI UYUM GÖRÜNÜMÜ" title="Yayınların SKA ve Stratejik Plan Uyum Matrisi" icon={<Target size={20} />} className="article-strategy-matrix"><p className="quality-note">Yayın sayıları güncel TR Dizin içerik eşleşmelerinden; amaç ve hedef bağlantıları 2025–2029 Stratejik Plan referans eşlemesinden hesaplanır.</p><div className="quality-table-scroll"><table className="quality-table"><thead><tr><th>SKA</th><th>Yayın sayısı</th><th>Bağlantılı SP amacı</th><th>Bağlantılı SP hedefleri</th><th>Yorum</th></tr></thead><tbody>{strategicMatrix.map((row) => { const sdg = data.sdgs.find((item) => item.id === row.sdg); return <tr key={row.sdg}><td><span className="article-sdg-label">SKA {row.sdg} – {sdg?.title}</span></td><td><strong>{formatNumber(sdg?.count || 0)}</strong></td><td>{row.goal}</td><td>{row.targets}</td><td>{row.note}</td></tr>; })}</tbody></table></div></Panel></section>
      <section className="article-section"><div className="article-section-title"><span>08</span><div><small>ARAŞTIRMA PROJELERİ</small><h2>TR Dizin proje görünümü</h2></div></div><div className="article-grid two embedded"><Panel eyebrow="PROJE GRUPLARI" title="Proje destek grupları"><Bars data={data.projectGroups} /></Panel><Panel eyebrow="PROJE ALANLARI" title="Projelerin konu dağılımı"><Donut data={data.projectSubjects} center={formatNumber(data.summary.totalProjects)} suffix="proje" /></Panel></div></section>
      <RecordBrowser options={data.filterOptions} /><section className="article-sync"><div><CalendarClock /><span><b>Sonraki yayın ve proje üst verisi güncellemesi</b>{formatDate(data.nextRefreshAt)}</span></div><div><RefreshCw /><span><b>Sonraki atıf güncellemesi</b>{formatDate(data.nextCitationRefreshAt)}</span></div><small>Üst veriler Şubat ortası ve Eylül son haftasında; atıf göstergeleri haftalık yenilenir. Başarısız işlemde son başarılı görüntü korunur.</small></section></>}
  </main>;
}
