import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root = process.cwd();
const department = "İşletme";
const programName = "İşletme";
const level = "Tezsiz Yüksek Lisans";
const official = JSON.parse(readFileSync(path.join(root, "data/courses/2026-2027.json"), "utf8"))
  .filter((course) => course.department === department && course.programName === programName && course.level === level);
const db = new DatabaseSync(path.join(root, "local-volume/data/dbp.sqlite"), { readOnly:true });
const profile = db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name = ? AND level = ?").get(programName, level);
const programOutcomes = JSON.parse(profile?.outcomes_json || "[]");
if (programOutcomes.length !== 11) throw new Error(`11 mevcut program çıktısı bekleniyordu; bulunan: ${programOutcomes.length}`);

const specs = {
  ISL703:{ label:"işletme araştırmaları", primary:[1,3,5,8], secondary:[0,2,4,6,9], sdgs:["4","8","16"], topics:["Bilimsel bilgi ve işletme araştırmasının kapsamı","Araştırma problemi ve amaçların yapılandırılması","İşletme alan yazınının sistematik incelenmesi","Kuramsal çerçeve ve araştırma modeli","Nicel araştırma tasarımları","Nitel araştırma tasarımları","Karma yöntem yaklaşımı","Örnekleme stratejileri","Veri toplama araçları ve ölçüm","Geçerlik, güvenirlik ve araştırma kalitesi","İşletme verilerinin çözümlenmesi","Bulguların yorumlanması ve tartışılması","Bilimsel yazım ve kaynak gösterme","Araştırma ve yayın etiği","Araştırma tasarımının bütüncül değerlendirilmesi"] },
  ISL705:{ label:"finansal muhasebe", primary:[0,1,3,4], secondary:[2,8,9], sdgs:["8","9","16"], topics:["Muhasebenin bilgi sistemi içindeki işlevi","Finansal tabloların yapısı ve unsurları","Muhasebe eşitliği ve hesapların işleyişi","Dönen varlık işlemleri","Duran varlık işlemleri","Kısa vadeli yabancı kaynaklar","Uzun vadeli yabancı kaynaklar","Öz kaynak işlemleri","Gelir ve gider hesapları","Dönem sonu envanter işlemleri","Değerleme ilkeleri","Finansal tabloların hazırlanması","Nakit akış bilgilerinin yorumlanması","Muhasebe bilgilerinde kalite ve etik","Finansal raporların bütüncül değerlendirilmesi"] },
  ISL707:{ label:"yönetim ve organizasyon", primary:[0,1,2,6,7], secondary:[8,9,10], sdgs:["5","8","16"], topics:["Yönetim ve organizasyonun temel kavramları","Klasik yönetim yaklaşımları","İnsan ilişkileri ve davranışsal yaklaşım","Sistem ve durumsallık yaklaşımları","Örgütsel yapı ve tasarım","Yetki, sorumluluk ve merkezileşme","Koordinasyon ve denetim mekanizmaları","Örgüt kültürü ve iklimi","Güç, politika ve çatışma","Karar verme süreçleri","Motivasyon ve iş tasarımı","Liderlik ve yönetsel etkileşim","Örgütsel değişim","Etik ve kurumsal yönetişim","Örgütsel yapıların karşılaştırmalı değerlendirilmesi"] },
  ISL709:{ label:"finansal yönetim", primary:[0,1,2,3,4], secondary:[8,9,10], sdgs:["8","9","12"], topics:["Finansal yönetimin amacı ve kapsamı","Finansal tablolar ve oran analizi","Paranın zaman değeri","Risk ve getiri ilişkisi","Tahvil değerlemesi","Hisse senedi değerlemesi","Sermaye bütçelemesi","Yatırım projelerinde nakit akışları","Sermaye maliyeti","Sermaye yapısı kararları","Çalışma sermayesi yönetimi","Kâr dağıtım politikaları","Finansal planlama ve tahmin","Sürdürülebilir finans kararları","Finansal kararların bütüncül değerlendirilmesi"] },
  ISL711:{ label:"pazarlama yönetimi", primary:[0,1,2,3,6,10], secondary:[7,9], sdgs:["8","9","12"], topics:["Pazarlama yönetiminin kapsamı","Pazar çevresinin analizi","Pazarlama bilgi sistemi","Tüketici ve örgütsel pazarlar","Pazar bölümlendirme","Hedef pazar seçimi","Konumlandırma stratejileri","Ürün ve marka kararları","Fiyatlandırma kararları","Dağıtım kanalı yönetimi","Bütünleşik pazarlama iletişimi","Müşteri ilişkileri ve değer yönetimi","Dijital pazarlama kararları","Sorumlu ve sürdürülebilir pazarlama","Pazarlama planının değerlendirilmesi"] },
  ISL713:{ label:"uygulamalı istatistik", primary:[1,3,4], secondary:[0,2,5,10], sdgs:["4","8","9"], topics:["İstatistiksel düşünme ve veri türleri","Betimsel istatistikler","Olasılık kavramları","Rassal değişkenler ve dağılımlar","Örnekleme dağılımları","Nokta ve aralık tahmini","Hipotez testlerinin mantığı","Tek örneklem testleri","İki örneklem testleri","Ki-kare testleri","Varyans analizine giriş","Korelasyon analizi","Basit doğrusal regresyon","İstatistiksel sonuçların raporlanması","İşletme verilerinin bütüncül yorumlanması"] },
  ISL715:{ label:"muhasebe teorileri", primary:[0,1,4,8], secondary:[2,3,9], sdgs:["8","12","16"], topics:["Muhasebe teorisinin kapsamı","Muhasebe düşüncesinin tarihsel gelişimi","Pozitif ve normatif muhasebe teorileri","Düzenleyici yaklaşımlar","Finansal raporlamanın amaçları","Muhasebe bilgisinin niteliksel özellikleri","Varlık ve yükümlülük kavramları","Gelir ve giderin kuramsal temelleri","Sermaye ve kârın korunması","Değerleme yaklaşımları","Muhasebe politikaları ve tahminler","Kurumsal raporlama ve paydaşlar","Muhasebe seçimlerinin ekonomik sonuçları","Etik ve kamu yararı","Muhasebe teorilerinin karşılaştırmalı değerlendirilmesi"] },
  ISL717:{ label:"tek düzen muhasebe sistemi", primary:[0,2,3,4], secondary:[1,8,10], sdgs:["8","9","16"], topics:["Tek düzen muhasebe sisteminin yapısı","Hesap planı ve kayıt düzeni","Dönen varlık hesaplarının uygulaması","Duran varlık hesaplarının uygulaması","Kısa vadeli yabancı kaynak kayıtları","Uzun vadeli yabancı kaynak kayıtları","Öz kaynak işlemleri","Gelir tablosu hesapları","Maliyet hesaplarına giriş","Nazım hesaplar","Dönem sonu muhasebe işlemleri","Envanter ve değerleme kayıtları","Finansal tabloların düzenlenmesi","Muhasebe kayıtlarında iç kontrol","Bütüncül kayıt uygulamasının değerlendirilmesi"] },
  ISL719:{ label:"yeşil yönetim ve işletmecilik", primary:[1,2,6,8,9], secondary:[0,7,10], sdgs:["8","12","13"], topics:["Yeşil yönetimin kavramsal temelleri","İşletmeler ve çevresel sorumluluk","Çevre yönetim sistemleri","Kaynak verimliliği ve temiz üretim","Döngüsel ekonomi modelleri","Yeşil tedarik zinciri","Sürdürülebilir ürün ve hizmet tasarımı","Karbon ve su ayak izi","Yeşil insan kaynakları yönetimi","Çevresel performans ölçümü","Sürdürülebilir finansman","Çevresel raporlama","Paydaş katılımı ve yönetişim","Yeşil dönüşümde etik sorunlar","Yeşil işletme stratejisinin değerlendirilmesi"] },
  ISL721:{ label:"örgütsel iletişim", primary:[1,2,6,7], secondary:[0,8,10], sdgs:["5","8","16"], topics:["Örgütsel iletişimin kapsamı","İletişim kuramları","Örgütsel iletişim ağları","Biçimsel ve biçimsel olmayan iletişim","Yönetsel iletişim ve geri bildirim","Örgüt kültürü ve iletişim","Gruplarda iletişim süreçleri","Çatışma ve müzakere iletişimi","Liderlik iletişimi","Kriz iletişimi","Kurumsal kimlik ve itibar","Dijital örgütsel iletişim","Kültürler arası iletişim","İletişimde etik ve kapsayıcılık","Örgütsel iletişim sisteminin değerlendirilmesi"] },
  ISL723:{ label:"nicel çözümleme teknikleri", primary:[1,3,4], secondary:[2,5,10], sdgs:["4","8","9"], topics:["Nicel karar problemlerinin yapılandırılması","Veri hazırlama ve model değişkenleri","Doğrusal modelleme ilkeleri","Doğrusal programlama modelleri","Grafik çözüm yöntemi","Simpleks yönteminin mantığı","Duyarlılık analizi","Taşıma modelleri","Atama modelleri","Ağ modelleri","Tamsayılı programlama","Karar analizi","Stok modelleri","Nicel sonuçların yönetsel yorumlanması","Çözüm yaklaşımlarının karşılaştırılması"] },
  ISL725:{ label:"hizmet pazarlaması ve yönetimi", primary:[0,1,2,6,10], secondary:[3,7,9], sdgs:["8","9","12"], topics:["Hizmetlerin yapısı ve özellikleri","Hizmet tüketici davranışı","Hizmetlerde pazar bölümlendirme","Hizmet konumlandırması","Hizmet ürünü ve marka yönetimi","Hizmet fiyatlandırması","Hizmet dağıtım kanalları","Hizmet iletişimi","Hizmet süreçlerinin tasarımı","Fiziksel kanıt ve hizmet ortamı","Hizmet personeli ve içsel pazarlama","Hizmet kalitesi ölçümü","Hizmet hataları ve telafi","Dijital hizmetler ve müşteri deneyimi","Hizmet pazarlama stratejisinin değerlendirilmesi"] },
  ISL727:{ label:"ticari işletme hukuku", primary:[0,1,2,8], secondary:[6,9,10], sdgs:["8","9","16"], topics:["Ticari işletme hukukunun kaynakları","Ticari işletme kavramı ve unsurları","Ticari iş ve ticari hüküm","Tacir sıfatı ve sonuçları","Ticaret sicili ve ticaret unvanı","Haksız rekabet","Ticari defterler","Cari hesap","Tacir yardımcıları","Acente ilişkileri","Ticaret şirketlerine giriş","Kıymetli evrakın temel ilkeleri","Ticari sözleşmelerde sorumluluk","Elektronik ticari işlemler","Ticari uyuşmazlıkların değerlendirilmesi"] },
  ISL706:{ label:"yönetim muhasebesi", primary:[0,1,2,3,4], secondary:[5,9,10], sdgs:["8","9","12"], topics:["Yönetim muhasebesinin kapsamı","Maliyet kavramları ve sınıflandırmalar","Maliyet davranışları","Maliyet-hacim-kâr analizi","Tam ve değişken maliyetleme","Sipariş ve safha maliyetleme","Faaliyet tabanlı maliyetleme","Bütçeleme süreci","Esnek bütçeler","Standart maliyetler ve sapmalar","Sorumluluk muhasebesi","Kısa vadeli karar analizleri","Fiyatlandırma kararları","Performans ölçümü","Yönetsel karar bilgilerinin değerlendirilmesi"] },
  ISL708:{ label:"ileri uygulamalı istatistik", primary:[1,3,4], secondary:[0,2,5,10], sdgs:["4","8","9"], topics:["Çok değişkenli veri yapısı","Çoklu doğrusal regresyon","Regresyon varsayımlarının sınanması","Model seçimi ve tanı ölçütleri","Lojistik regresyon","Tek yönlü varyans analizi","Çok faktörlü varyans analizi","Çok değişkenli varyans analizi","Temel bileşenler analizi","Faktör analizi","Kümeleme analizi","Diskriminant analizi","Parametrik olmayan yöntemler","Çok değişkenli sonuçların raporlanması","İşletme araştırmalarında model değerlendirmesi"] },
  ISL710:{ label:"üretim yönetimi", primary:[0,1,2,3,4,9], secondary:[6,10], sdgs:["8","9","12"], topics:["Üretim sistemlerinin yapısı","Üretim stratejisi","Ürün ve süreç tasarımı","Kapasite planlaması","Kuruluş yeri kararları","İşyeri düzenleme","Talep tahmini","Toplu üretim planlama","Ana üretim çizelgeleme","Malzeme ihtiyaç planlaması","Stok yönetimi","Çizelgeleme ve sıralama","Kalite yönetimi","Yalın ve sürdürülebilir üretim","Üretim sisteminin bütüncül değerlendirilmesi"] },
  ISL712:{ label:"stratejik yönetim", primary:[0,1,2,4,6,7,9], secondary:[3,8,10], sdgs:["8","9","16"], topics:["Stratejik yönetimin kapsamı","Vizyon, misyon ve amaçlar","Dış çevre analizi","Sektör ve rekabet analizi","İç çevre ve kaynak analizi","Temel yetenekler","İşletme düzeyi stratejileri","Kurumsal düzey stratejileri","Uluslararası stratejiler","Stratejik iş birlikleri","Stratejinin uygulanması","Örgüt yapısı ve strateji","Stratejik kontrol","Etik ve sürdürülebilirlik","Stratejik seçeneklerin değerlendirilmesi"] },
  ISL714:{ label:"maliyet muhasebesi", primary:[0,1,3,4], secondary:[2,8,9], sdgs:["8","9","12"], topics:["Maliyet muhasebesinin amaçları","Maliyet unsurları ve sınıflandırma","İlk madde ve malzeme maliyetleri","İşçilik maliyetleri","Genel üretim giderleri","Gider yerleri ve dağıtım","Sipariş maliyet sistemi","Safha maliyet sistemi","Birleşik ürün maliyetleri","Tam maliyet yöntemi","Değişken maliyet yöntemi","Standart maliyetler","Fire ve kayıp maliyetleri","Maliyet bilgilerinin karar amaçlı kullanımı","Maliyet raporlarının değerlendirilmesi"] },
  ISL716:{ label:"çağdaş maliyet yönetimi", primary:[0,1,2,3,4,9], secondary:[5,10], sdgs:["8","9","12"], topics:["Stratejik maliyet yönetimi","Değer zinciri analizi","Faaliyet tabanlı maliyetleme","Faaliyet tabanlı yönetim","Hedef maliyetleme","Yaşam seyri maliyetleme","Kaizen maliyetleme","Kalite maliyetleri","Tam zamanında üretim ve maliyet","Kısıtlar teorisi muhasebesi","Çevresel maliyetleme","Müşteri kârlılık analizi","Kıyaslama ve performans ölçümü","Dijitalleşme ve maliyet sistemleri","Çağdaş yöntemlerin karşılaştırılması"] },
  ISL718:{ label:"bilgisayar destekli istatistik", primary:[1,3,4,10], secondary:[0,2,5], sdgs:["4","8","9"], topics:["İstatistiksel yazılım ortamı ve veri yapıları","Veri aktarımı ve düzenleme","Eksik ve aykırı gözlemler","Betimsel analizlerin yürütülmesi","Görsel veri keşfi","Güven aralıklarının hesaplanması","Hipotez testlerinin uygulanması","Ki-kare analizleri","Korelasyon çözümlemesi","Doğrusal regresyon uygulaması","Varyans analizi uygulaması","Parametrik olmayan testler","Çıktı tablolarının yorumlanması","Analiz sonuçlarının raporlanması","İşletme veri analizinin bütüncül yürütülmesi"] },
  ISL720:{ label:"yöneylem araştırması", primary:[1,2,3,4,10], secondary:[0,5,9], sdgs:["8","9","12"], topics:["Yöneylem araştırmasının karar süreçlerindeki yeri","Model kurma yaklaşımı","Doğrusal programlama","Grafik çözüm ve gölge fiyatlar","Simpleks yöntemi","Duyarlılık ve parametre analizi","Taşıma problemi","Atama problemi","Ağ optimizasyonu","Proje çizelgeleme modelleri","Stok kontrol modelleri","Kuyruk modelleri","Karar analizi","Çok ölçütlü karar yaklaşımı","Model sonuçlarının yönetsel değerlendirilmesi"] },
  ISL722:{ label:"yönetim ve liderlik", primary:[0,1,2,6,7], secondary:[8,9,10], sdgs:["5","8","16"], topics:["Yönetim ve liderlik ayrımı","Liderlik özellikleri yaklaşımı","Davranışsal liderlik kuramları","Durumsal liderlik yaklaşımları","Dönüşümcü ve etkileşimci liderlik","Lider-üye etkileşimi","Güç ve etkileme taktikleri","Motivasyon ve liderlik","Takım liderliği","Çatışma ve müzakere","Stratejik liderlik","Etik liderlik","Kapsayıcı liderlik","Dijital çağda liderlik","Liderlik yaklaşımının örgütsel bağlamda değerlendirilmesi"] },
  ISL724:{ label:"güncel yönetim yaklaşımları", primary:[0,1,2,6,10], secondary:[7,8,9], sdgs:["8","9","12"], topics:["Yönetim yaklaşımlarındaki güncel dönüşüm","Çevik yönetim","Yalın yönetim","Öğrenen örgütler","Bilgi yönetimi","Yetenek yönetimi","Kurumsal yönetişim","İnovasyon yönetimi","Dijital dönüşüm yönetimi","Veriye dayalı yönetim","Ağ ve platform organizasyonları","Uzaktan ve hibrit çalışma","Dayanıklılık ve kriz yönetimi","Sürdürülebilir yönetim","Güncel yaklaşımların karşılaştırılması"] },
  ISL726:{ label:"para ve sermaye piyasaları", primary:[0,1,3,4], secondary:[2,8,9], sdgs:["8","9","16"], topics:["Finansal sistemin yapısı","Para piyasalarının işleyişi","Merkez bankacılığı ve para politikası","Faiz oranlarının oluşumu","Para piyasası araçları","Sermaye piyasalarının işlevi","Borçlanma araçları","Pay senetleri","Yatırım fonları","Türev piyasalar","Piyasa endeksleri","Risk ve getiri ölçümü","Piyasa etkinliği","Finansal düzenleme ve yatırımcı korunması","Piyasa göstergelerinin bütüncül değerlendirilmesi"] },
  ISL728:{ label:"tüketici davranışları", primary:[0,1,2,3,6], secondary:[8,9,10], sdgs:["8","10","12"], topics:["Tüketici davranışının kapsamı","Tüketici karar süreci","Algılama ve dikkat","Öğrenme ve bellek","Güdülenme ve kişilik","Tutum oluşumu ve değişimi","Benlik ve yaşam tarzı","Sosyal sınıf ve statü","Referans grupları ve aile","Kültür ve alt kültür","Satın alma durumu","Müşteri deneyimi","Dijital tüketici davranışı","Etik ve sürdürülebilir tüketim","Tüketici içgörülerinin pazarlama kararlarına aktarılması"] },
  ISL730:{ label:"finansal okuryazarlık", primary:[0,1,2,3,8], secondary:[4,9,10], sdgs:["4","8","10"], topics:["Finansal okuryazarlığın kapsamı","Bütçe ve nakit akışı yönetimi","Tasarruf kararları","Faiz ve paranın zaman değeri","Kredi ürünleri ve borç yönetimi","Bankacılık ürünleri","Sigorta ve risk yönetimi","Yatırım araçları","Risk-getiri dengesi","Portföy çeşitlendirmesi","Emeklilik planlaması","Vergi ve finansal kararlar","Dijital finans ve güvenlik","Finansal dolandırıcılık ve tüketici hakları","Bireysel finansal planın değerlendirilmesi"] },
  ISL732:{ label:"elektronik ticaret hukuku", primary:[0,1,2,8,10], secondary:[6,9], sdgs:["8","9","16"], topics:["Elektronik ticaretin hukuki çerçevesi","Elektronik sözleşmeler","Elektronik imza ve güven hizmetleri","Mesafeli sözleşmeler","Tüketicinin korunması","Elektronik ticari ileti","Kişisel verilerin korunması","Çerezler ve çevrim içi izleme","Platformların hukuki sorumluluğu","Fikri mülkiyet hakları","Alan adları ve marka uyuşmazlıkları","Elektronik ödeme sistemleri","Siber güvenlik ve hukuki sorumluluk","Sınır ötesi elektronik ticaret","Elektronik ticaret uyuşmazlıklarının değerlendirilmesi"] },
};

const checklist = ["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const qualityChecks = (hasSource) => checklist.map((item, index) => ({ item, status:!hasSource && [1,19,20].includes(index) ? "Doğrulanmalı" : [3,5,6,7,8,9,10,11,12,13,14,15,16,18].includes(index) ? "Revize Edildi" : "Uygun", ...(!hasSource && [1,19,20].includes(index) ? { note:"Resmî müfredat kimliği korunmuş; ayrıntılı OBS bağlantısı doğrulanamadığından eksik akademik alanlar handoff ölçütleri ve programın mevcut 11 program çıktısı temelinde öneri niteliğinde tamamlanmıştır." } : {}) }));
const normalizeInstructor = (value = "") => String(value).replace(/^Yrd\.?\s*Doç\.?\s*Dr\.?/iu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+/giu," ").replace(/\b\S+@\S+\b/giu," ").replace(/\s+/gu," ").trim() || "Atama Bekliyor";
const matrix = (primary, secondary) => Array.from({ length:5 }, (_, row) => ({ outcome:`DÖÇ${row + 1}`, values:programOutcomes.map((_, col) => primary.includes(col) ? [4,4,5,4,5][row] : secondary.includes(col) ? [2,3,2,3,2][row] : [1,1,2,1,1][row]) }));
const outcomes = (label) => [`${label} alanındaki ileri kavram ve yaklaşımları analiz eder.`,`${label} kapsamındaki yöntemleri işletme problemlerine uygular.`,`${label} verilerini uygun ölçütlerle karşılaştırır ve yorumlar.`,`${label} sorunlarına uygulanabilir çözüm seçenekleri geliştirir.`,`${label} kararlarını mesleki, etik ve sürdürülebilirlik ölçütleriyle değerlendirir.`];
const workloads = (course, assessments) => {
  const target = Number(course.ects) * 30;
  const contact = 15 * (Number(course.theory) + Number(course.practice));
  const rows = [{ name:"Ders Süresi", count:15, hours:Number(course.theory) + Number(course.practice), total:contact }];
  for (const item of assessments) {
    const key = item.name.toLocaleLowerCase("tr-TR");
    if (key.includes("ödev")) rows.push({ name:"Ödev Hazırlığı", count:item.count, hours:8, total:item.count * 8 });
    else if (key.includes("ara sınav")) rows.push({ name:"Ara Sınav Hazırlığı", count:item.count, hours:20, total:item.count * 20 });
    else if (key.includes("yarıyıl sonu")) rows.push({ name:"Yarıyıl Sonu Sınavı Hazırlığı", count:item.count, hours:25, total:item.count * 25 });
  }
  const used = rows.reduce((sum, row) => sum + row.total, 0);
  const outside = Math.max(0, Math.floor(((target - used) / 15) * 2) / 2);
  rows.splice(1, 0, { name:"Sınıf Dışı Çalışma Süresi", count:15, hours:outside, total:outside * 15 });
  const delta = target - rows.reduce((sum, row) => sum + row.total, 0);
  if (delta) rows.push({ name:"Kaynak İnceleme ve Akademik Hazırlık", count:1, hours:delta, total:delta });
  return rows;
};

const excluded = new Set(["ISL701","ISL702","ISL704"]);
const academic = official.filter((course) => !excluded.has(course.code)).map((course) => {
  const spec = specs[course.code];
  if (!spec) throw new Error(`${course.code}: ders tanımı eksik.`);
  const assessments = [{ name:"Ara Sınav", count:1, weight:40 },{ name:"Yarıyıl Sonu Sınavı", count:1, weight:60 }];
  return { code:course.code, ...(course.code === "ISL703" ? { aliases:["ISL703","ISL704"] } : {}), name:course.name, department, programName, language:"Türkçe", level, teachingMode:"Yüz Yüze", theory:Number(course.theory), practice:Number(course.practice), credit:Number(course.credit), ects:Number(course.ects), prerequisites:"Yok", instructor:normalizeInstructor(course.instructor), purpose:`Öğrencinin ${spec.label} alanındaki ileri bilgileri analiz etmesini, bu bilgileri işletme sorunlarına uygulamasını ve ulaştığı sonuçları bilimsel, mesleki ve etik ölçütlerle değerlendirmesini sağlamak.`, content:`${spec.label.charAt(0).toLocaleUpperCase("tr-TR") + spec.label.slice(1)} kapsamında ${spec.topics.slice(0,7).join(", ")}; ${spec.topics.slice(7,14).join(", ")} konuları ele alınır.`, methods:"Kuramsal anlatım, bilimsel kaynak incelemesi, örnek olay çözümlemesi, problem çözme ve akademik tartışma.", resources:"İşletme alanındaki temel lisansüstü kaynaklar; dersin kapsamına uygun güncel hakemli makaleler; ilgili mevzuat, standart ve mesleki raporlar.", sdgs:spec.sdgs, outcomes:outcomes(spec.label), weeklyTopics:spec.topics, assessments, workloads:workloads(course, assessments), contributionMatrix:matrix(spec.primary, spec.secondary), qualityChecks:qualityChecks(Boolean(course.sourceUrl)), publicQualityChecklist:false };
});

const projectOfficial = official.find((course) => course.code === "ISL701");
const projectSpec = { primary:[1,2,5,7,8,9], secondary:[0,3,4,6,10] };
const project = { code:"ISL7XX", aliases:["ISL701","ISL702"], name:"Bitirme Projesi", department, programName, language:"Türkçe", level, teachingMode:"Bireysel Çalışma", theory:0, practice:0, credit:0, ects:30, prerequisites:"Yok", instructor:"Öğrencinin Proje Danışmanı", purpose:"Öğrencinin işletme alanındaki mesleki bir problemi bilimsel kaynaklara dayalı olarak çözümlemesini, uygulanabilir bir proje yaklaşımı geliştirmesini ve çalışmasını etik ilkelere uygun biçimde raporlamasını sağlamak.", content:"Proje konusunun sınırlandırılması, kaynak tarama, problem ve amaçların yapılandırılması, yöntem ve çalışma planı, veri veya dokümanların değerlendirilmesi, bulguların yorumlanması, bilimsel raporlama ve bitirme projesinin teslimi.", methods:"Bireysel proje çalışması, danışman görüşmesi, bilimsel kaynak incelemesi, veri veya doküman çözümlemesi, akademik yazım ve geri bildirim.", resources:"Proje konusuna özgü güncel hakemli literatür; Enstitü yazım ve etik yönergeleri; ilgili mevzuat, standart ve mesleki raporlar.", sdgs:["4","8","9"], outcomes:["İşletme alanındaki mesleki bir problemi yapılandırır.","Proje problemine uygun bilimsel kaynakları eleştirel değerlendirir.","Uygulanabilir bir proje yöntemi ve çalışma planı geliştirir.","Proje bulgularını yönetsel ve sürdürülebilirlik ölçütleriyle yorumlar.","Bitirme projesini bilimsel ve etik ilkelere uygun raporlar."], weeklyTopics:["Proje alanının ve beklentilerin belirlenmesi","Proje probleminin sınırlandırılması","Amaç, kapsam ve çalışma sorularının yapılandırılması","Kaynak tarama stratejisinin oluşturulması","Bilimsel ve mesleki kaynakların değerlendirilmesi","Proje yönteminin seçilmesi","Çalışma planı ve zaman çizelgesinin geliştirilmesi","Veri veya doküman toplama sürecinin yürütülmesi","Toplanan materyalin düzenlenmesi","Veri veya dokümanların çözümlenmesi","Bulguların işletme açısından yorumlanması","Yönetsel, etik ve sürdürülebilirlik etkilerinin değerlendirilmesi","Proje raporunun yapılandırılması","Bilimsel yazım ve etik uygunluk denetimi","Bitirme projesinin teslimi ve değerlendirilmesi"], assessments:[{ name:"Başarılı / Başarısız", count:1, weight:100 }], workloads:[{ name:"Proje Planlama ve Danışman Görüşmeleri", count:15, hours:2, total:30 },{ name:"Kaynak İnceleme ve Proje Çalışması", count:15, hours:44, total:660 },{ name:"Proje Raporunun Hazırlanması", count:1, hours:180, total:180 },{ name:"Nihai Düzenleme ve Teslim", count:1, hours:30, total:30 }], contributionMatrix:matrix(projectSpec.primary, projectSpec.secondary), qualityChecks:qualityChecks(Boolean(projectOfficial?.sourceUrl)), publicQualityChecklist:false };

const all = [...academic, project];
const forbidden = /(quiz|ödev|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|arasınav|vize|yarıyıl\s+sonu\s+sınavı|final)/iu;
for (const course of all) {
  if (course.weeklyTopics.length !== 15) throw new Error(`${course.code}: 15 hafta yok.`);
  if (course.code !== "ISL7XX" && course.weeklyTopics.some((topic) => forbidden.test(topic))) throw new Error(`${course.code}: yasak haftalık başlık.`);
  if (course.outcomes.length !== 5) throw new Error(`${course.code}: 5 DÖÇ yok.`);
  if (course.workloads.reduce((sum, row) => sum + row.total, 0) !== course.ects * 30) throw new Error(`${course.code}: AKTS iş yükü tutarsız.`);
  if (course.contributionMatrix.some((row) => row.values.length !== 11 || row.values.some((value) => value < 1 || value > 5))) throw new Error(`${course.code}: DÖÇ-PÇ matrisi geçersiz.`);
}
const emit = (file, exportName, value) => writeFileSync(path.join(root, "lib/data", file), `import type { CoursePackage } from "./coursePackages";\n\nexport const ${exportName}: CoursePackage[] = ${JSON.stringify(value, null, 2)};\n`);
emit("isletmeTezsizCoursePackages.ts", "isletmeTezsizCoursePackages", academic);
emit("isletmeTezsizCommonCoursePackages.ts", "isletmeTezsizCommonCoursePackages", [project]);
console.log(JSON.stringify({ official:official.length, academic:academic.length, common:1, total:all.length, programOutcomes:programOutcomes.length, excluded:["ISL701","ISL702"] }));
