import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root = process.cwd();
const department = "İktisat ABD";
const programName = "Ekonomi ve Finans";
const level = "Tezsiz Yüksek Lisans";
const official = JSON.parse(readFileSync(path.join(root, "data/courses/2026-2027.json"), "utf8"))
  .filter((course) => course.department === department && course.programName === programName && course.level === level);
const db = new DatabaseSync(path.join(root, "local-volume/data/dbp.sqlite"), { readOnly: true });
const profile = db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name = ? AND level = ?").get(programName, level);
const programOutcomes = JSON.parse(profile?.outcomes_json || "[]");
if (programOutcomes.length !== 11) throw new Error(`11 mevcut program çıktısı bekleniyordu; bulunan: ${programOutcomes.length}`);

const plans = {
  "İKT703": ["Bilimsel bilginin özellikleri ve iktisadi araştırma", "Ekonomi ve finansta araştırma probleminin kurulması", "Alan yazını tarama stratejileri", "Kuramsal çerçeve ve hipotez geliştirme", "Nicel ve nitel araştırma desenleri", "Ekonomik ve finansal veri kaynakları", "Örnekleme ve veri kalitesi", "Değişkenlerin ölçülmesi ve model seçimi", "Betimsel analiz ve bulguların görselleştirilmesi", "Nedensellik ve yorumlama sınırları", "Bilimsel yazımın yapısı", "Atıf, kaynakça ve fikrî mülkiyet", "Araştırma etiği ve veri bütünlüğü", "Yayın etiği ve yazarlık sorumlulukları", "Bir araştırma tasarımının bütüncül değerlendirilmesi"],
  "İKT705": ["Finansal sistem ve piyasa yapısı", "Para ve sermaye piyasası araçları", "Piyasa katılımcıları ve aracılık", "Finansal varlıkların fiyatlanmasına giriş", "Kripto varlıkların teknik temelleri", "Blokzincir, mutabakat ve işlem yapısı", "Kripto varlık türleri ve kullanım alanları", "Merkezi ve merkeziyetsiz finans", "Kripto piyasalarda fiyat oluşumu", "Likidite, oynaklık ve piyasa riski", "Portföy yaklaşımı ve çeşitlendirme", "Kripto varlıklarda saklama ve güvenlik", "Düzenleme, vergileme ve tüketicinin korunması", "Finansal istikrar ve sistemik etkiler", "Güncel piyasa gelişmelerinin kanıta dayalı değerlendirilmesi"],
  "İKT707": ["Makroekonomik göstergelerin kapsamı", "Millî gelir ve büyüme göstergeleri", "Enflasyon ölçütleri ve fiyat endeksleri", "İşgücü piyasası göstergeleri", "Para ve kredi göstergeleri", "Faiz oranları ve getiri eğrisi", "Döviz kuru göstergeleri", "Ödemeler dengesi", "Kamu maliyesi göstergeleri", "Borçluluk ve finansal kırılganlık", "Öncü, eşanlı ve gecikmeli göstergeler", "Konjonktür ve çıktı açığı", "Gösterge setlerinde veri kalitesi", "Ulusal ve uluslararası veri kaynaklarının karşılaştırılması", "Makroekonomik görünümün bütüncül yorumlanması"],
  "İKT709": ["Paranın işlevleri ve parasal sistem", "Para arzı tanımları ve yaratılma süreci", "Para talebi yaklaşımları", "Faiz oranının belirlenmesi", "Merkez bankası bilançosu", "Para politikası araçları", "Parasal aktarım mekanizması", "Enflasyon ve para politikası", "Beklentiler ve politika güvenilirliği", "Kural ve takdir tartışması", "Geleneksel olmayan para politikaları", "Finansal istikrar ve makroihtiyati çerçeve", "Dijital para ve ödeme sistemleri", "Açık ekonomide para politikası", "Güncel parasal gelişmelerin değerlendirilmesi"],
  "İKT711": ["Döviz piyasasının yapısı", "Nominal ve reel döviz kuru", "Satın alma gücü paritesi", "Faiz paritesi koşulları", "Ödemeler dengesi ve kur ilişkisi", "Döviz kuru rejimleri", "Kur beklentileri ve fiyat oluşumu", "Merkez bankası müdahaleleri", "Kur geçişkenliği", "Döviz kuru oynaklığı", "Vadeli işlemler ve kur riski", "Kur krizlerinin dinamikleri", "Dolarlaşma ve bilanço etkileri", "Uluslararası rezerv yönetimi", "Döviz piyasasındaki güncel eğilimler"],
  "İKT713": ["Dünya ekonomisinin tarihsel dönüşümü", "Küreselleşmenin ekonomik boyutları", "Uluslararası ticaret ağları", "Küresel değer zincirleri", "Sermaye hareketleri ve finansal bütünleşme", "Çok uluslu şirketler", "Uluslararası ekonomik kuruluşlar", "Bölgesel ekonomik bütünleşmeler", "Küresel gelir dağılımı", "Göç ve işgücü hareketliliği", "Teknolojik dönüşüm ve dijital küreselleşme", "Küresel krizler ve yayılma kanalları", "İklim değişikliği ve dünya ekonomisi", "Jeoekonomi ve tedarik güvenliği", "Küreselleşmenin geleceğine ilişkin yaklaşımlar"],
  "İKT715": ["Davranışsal finansın gelişimi", "Beklenen fayda ve rasyonellik varsayımı", "Sınırlı rasyonellik", "Kayıptan kaçınma ve beklenti teorisi", "Aşırı güven ve kendine atfetme", "Temsil edilebilirlik ve çapa etkisi", "Zihinsel muhasebe", "Sürü davranışı", "Yatırımcı duyarlılığı", "Piyasa anomalileri", "Varlık fiyatlarında balonlar", "Davranışsal portföy yaklaşımı", "Kurumsal kararlarda davranışsal etkiler", "Finansal kararların etik boyutu", "Davranışsal bulguların piyasa verileriyle değerlendirilmesi"],
  "İKT717": ["Stratejik karar problemlerinin yapısı", "Belirsizlik ve risk altında karar", "Karar ölçütleri ve amaçların belirlenmesi", "Ekonomik çevre analizi", "Finansal durum analizi", "Senaryo geliştirme", "Duyarlılık analizi", "Karar ağaçları", "Çok ölçütlü karar yaklaşımı", "Oyun teorisi ve stratejik etkileşim", "Rekabet ve piyasa sinyalleri", "Davranışsal sapmaların kararlara etkisi", "Kurumsal yönetişim ve etik", "Strateji seçeneklerinin karşılaştırılması", "Kanıta dayalı karar önerisinin yapılandırılması"],
  "İKT719": ["Mali iktisadın kapsamı", "Kamu kesiminin ekonomik rolü", "Kamu malları ve dışsallıklar", "Piyasa başarısızlıkları", "Kamu harcamalarının ekonomik etkileri", "Vergilemenin etkinlik etkileri", "Vergileme ve gelir dağılımı", "Kamu bütçesi ve mali denge", "Mali çarpanlar", "Borçlanma ve kuşaklar arası etkiler", "Mali kurallar", "Yerel yönetim maliyesi", "Sosyal güvenlik sistemleri", "Maliye politikası ve sürdürülebilirlik", "Güncel mali gelişmelerin değerlendirilmesi"],
  "İKT721": ["Kamu mali yönetiminin kapsamı", "Bütçe hakkı ve mali yönetişim", "Stratejik planlama ve performans programı", "Bütçe hazırlama süreci", "Bütçenin uygulanması", "Kamu gelir ve gider işlemleri", "İç kontrol sistemi", "İç denetim", "Dış denetim ve hesap verebilirlik", "Performans denetimi", "Mali saydamlık", "Kamu mali raporlaması", "Risk yönetimi ve usulsüzlük göstergeleri", "Dijitalleşme ve kamu mali yönetimi", "Denetim bulgularının politika açısından yorumlanması"],
  "İKT723": ["Vergilemenin ekonomik temelleri", "Vergi adaleti ve etkinlik", "Gelir ve kurumlar vergisindeki eğilimler", "Tüketim vergilerindeki gelişmeler", "Servet ve mülkiyet vergileri", "Uluslararası vergi rekabeti", "Çifte vergilendirme sorunları", "Transfer fiyatlandırması", "Matrah aşındırma ve kâr aktarımı", "Dijital ekonominin vergilendirilmesi", "Çevre vergileri ve karbon fiyatlaması", "Vergi uyumu ve davranışsal yaklaşımlar", "Vergi teknolojileri ve e-belge sistemleri", "Vergi politikalarının dağılımsal etkileri", "Güncel vergi reformlarının karşılaştırılması"],
  "İKT704": ["Finansal analizde bilgi kaynakları", "Finansal tabloların temel analizi", "Oran analizi", "Büyüme ve kârlılık göstergeleri", "Nakit akışı ve firma değeri", "Sektör ve rekabet analizi", "Makroekonomik koşulların değerlemeye etkisi", "Teknik analizin varsayımları", "Trend ve destek-direnç kavramları", "Hareketli ortalamalar", "Momentum göstergeleri", "Hacim ve oynaklık göstergeleri", "Grafik formasyonlarının yorumlanması", "Temel ve teknik bulguların bütünleştirilmesi", "Analiz sonuçlarının risk sınırlarıyla değerlendirilmesi"],
  "İKT706": ["Finansal kriz kavramı ve türleri", "Bankacılık krizlerinin nedenleri", "Döviz krizleri", "Borç krizleri", "Varlık fiyatı balonları", "Finansal kırılganlık göstergeleri", "Asimetrik bilgi ve ahlaki tehlike", "Likidite ve bulaşma mekanizmaları", "Kriz modelleri", "Erken uyarı göstergeleri", "Krizlerin reel ekonomi üzerindeki etkileri", "Merkez bankası ve son kredi mercii", "Kriz yönetimi ve yeniden yapılandırma", "Küresel kriz deneyimlerinin karşılaştırılması", "Finansal dayanıklılık politikalarının değerlendirilmesi"],
  "İKT708": ["Para ve bankacılık sisteminin işlevleri", "Finansal aracılık", "Banka bilançosu ve temel riskler", "Mevduat ve kredi mekanizması", "Kaydi para yaratılması", "Merkez bankacılığı", "Para piyasaları", "Faiz oranlarının vade yapısı", "Bankacılıkta likidite yönetimi", "Kredi riski ve sermaye yeterliliği", "Bankacılık düzenleme ve denetimi", "Ödeme sistemleri", "Dijital bankacılık ve finansal teknoloji", "Banka krizleri ve mevduat güvencesi", "Para-banka göstergelerinin birlikte yorumlanması"],
  "İKT710": ["Uluslararası finansal sistem", "Ödemeler dengesi hesapları", "Döviz kuru belirlenmesi", "Uluslararası parite koşulları", "Sermaye hareketleri", "Uluslararası portföy yatırımları", "Doğrudan yabancı yatırımlar", "Ülke riski", "Uluslararası borçlanma araçları", "Türev ürünlerle kur riskinden korunma", "Çok uluslu işletmelerde finansman", "Uluslararası finansal kuruluşlar", "Küresel likidite döngüsü", "Finansal bulaşma", "Uluslararası finansal gelişmelerin ekonomik etkileri"],
  "İKT712": ["Güncel ekonomik sorunları çözümleme çerçevesi", "Enflasyon ve hayat pahalılığı", "İşsizlik ve istihdam yapısı", "Gelir dağılımı ve yoksulluk", "Büyüme ve verimlilik", "Cari işlemler dengesi", "Kamu mali dengesi", "Finansal istikrar", "Enerji ve emtia fiyatları", "Dijital dönüşüm ve işgücü", "Demografik değişim", "İklim değişikliğinin ekonomik etkileri", "Küresel tedarik sorunları", "Politika seçeneklerinin karşılaştırılması", "Güncel ekonomik görünümün kanıta dayalı değerlendirilmesi"],
  "İKT714": ["Ekonomik ve finansal tahminin kapsamı", "Veri kaynakları ve frekans seçimi", "Zaman serilerinin temel özellikleri", "Durağanlık ve dönüşümler", "Eğilim ve mevsimsellik", "Hareketli ortalama ve üstel düzeltme", "Tek değişkenli tahmin modelleri", "Çok değişkenli tahmin yaklaşımı", "Öncü göstergelerin seçimi", "Model kurma ve değişken seçimi", "Tahmin başarısının ölçülmesi", "Örneklem dışı değerlendirme", "Senaryo ve duyarlılık analizi", "Tahmin belirsizliğinin raporlanması", "Makro-finansal tahminlerin karar süreçlerinde kullanılması"],
  "İKT716": ["Kamu borcunun ekonomik niteliği", "İç ve dış borçlanma", "Borçlanma araçları", "Borçlanma maliyeti ve faiz yapısı", "Vade ve para birimi kompozisyonu", "Borç sürdürülebilirliği", "Birincil denge ve borç dinamikleri", "Borç yönetimi stratejileri", "Yeniden finansman riski", "Faiz ve kur riski", "Likidite ve nakit yönetimi", "Borçlanmanın makroekonomik etkileri", "Mali kurallar ve kurumsal yapı", "Borç krizleri ve yeniden yapılandırma", "Kamu borç portföyünün risk açısından değerlendirilmesi"],
  "İKT718": ["Menkul ve gayrimenkul kıymetlerin kapsamı", "Finansal getirilerin vergilendirilme ilkeleri", "Faiz gelirlerinin vergilendirilmesi", "Kâr paylarının vergilendirilmesi", "Sermaye kazançlarının vergilendirilmesi", "Yatırım fonları ve kolektif araçlar", "Gayrimenkul ediniminde vergiler", "Kira gelirlerinin vergilendirilmesi", "Gayrimenkul değer artış kazançları", "Emlak vergisi ve yerel yükümlülükler", "Vergi kesintisi ve beyan uygulamaları", "Uluslararası yatırım ve vergilendirme", "Vergi planlaması ile vergiden kaçınma ayrımı", "Vergilemenin yatırım kararlarına etkisi", "Güncel mevzuat eğilimlerinin ekonomik değerlendirilmesi"],
  "İKT720": ["Uluslararası maliyenin kapsamı", "Küresel kamu gelirleri eğilimleri", "Kamu harcamalarının uluslararası karşılaştırması", "Uluslararası vergi rekabeti", "Vergi cennetleri ve şeffaflık", "Çok uluslu şirketlerin vergilendirilmesi", "Küresel asgari kurumlar vergisi", "Sınır ötesi dijital hizmetlerin vergilendirilmesi", "Uluslararası kamu borcu", "Egemen risk ve borçlanma maliyeti", "Uluslararası mali kuruluşlar", "Mali krizlerde politika koordinasyonu", "İklim finansmanı", "Küresel mali kurallar ve yönetişim", "Uluslararası mali gelişmelerin Türkiye'ye etkileri"],
};

const titles = {
  "İKT703":"Bilimsel Araştırma ve Yayın Etiği", "İKT705":"Finansal Piyasalar ve Kripto Paralar", "İKT707":"Makroekonomik Göstergeler",
  "İKT709":"Parasal Ekonomi", "İKT711":"Döviz Ekonomisi", "İKT713":"Dünya Ekonomisi ve Küreselleşme", "İKT715":"Davranışsal Finans",
  "İKT717":"Ekonomi ve Finansta Stratejik Karar Alma", "İKT719":"Mali İktisat", "İKT721":"Kamu Mali Yönetimi ve Denetimi",
  "İKT723":"Vergilendirmede Yeni Gelişmeler", "İKT704":"Finansal Piyasalarda Temel ve Teknik Analiz", "İKT706":"Finansal Krizler",
  "İKT708":"Para-Banka", "İKT710":"Uluslararası Finans", "İKT712":"Güncel Ekonomik Sorunlar",
  "İKT714":"Makroekonomik ve Finansal Göstergelerin Tahmini", "İKT716":"Kamu Borçlarının Finansmanı",
  "İKT718":"Menkul ve Gayrimenkul Kıymetlerin Vergilendirilmesi", "İKT720":"Uluslararası Mali Gelişmeler",
};
const focus = {
  "İKT703":["bilimsel araştırma sürecini", "ekonomik ve finansal araştırma tasarımlarını", "araştırma ve yayın etiği ilkelerini", [1,7,8,9,10], [0,2,3]],
  "İKT705":["finansal piyasalar ile kripto varlıkların işleyişini", "piyasa verileri ve risk göstergelerini", "yatırım seçenekleri ile düzenleyici etkileri", [0,1,4,5,7,10], [2,6,9]],
  "İKT707":["makroekonomik göstergelerin yapısını", "ulusal ve uluslararası gösterge setlerini", "ekonomik görünüm ve politika etkilerini", [0,1,3,7,10], [2,6]],
  "İKT709":["parasal ekonomi kuramlarını", "para, faiz, enflasyon ve kredi göstergelerini", "para politikası seçeneklerini", [0,1,3,7,10], [2,5,6]],
  "İKT711":["döviz piyasası kuramlarını", "kur, rezerv ve dış denge göstergelerini", "kur riski ve politika seçeneklerini", [0,1,5,6,7], [2,3,10]],
  "İKT713":["dünya ekonomisi ve küreselleşme yaklaşımlarını", "küresel ticaret, yatırım ve gelir verilerini", "uluslararası gelişmelerin ekonomik etkilerini", [0,1,3,6,10], [2,7,9]],
  "İKT715":["davranışsal finans kuramlarını", "yatırımcı davranışı ve piyasa anomalilerini", "finansal kararların sonuçlarını", [0,1,4,5,10], [2,9]],
  "İKT717":["stratejik karar alma yaklaşımlarını", "ekonomik ve finansal karar verilerini", "belirsizlik altındaki strateji seçeneklerini", [0,1,2,7,8], [4,5,9]],
  "İKT719":["mali iktisat kuramlarını", "kamu gelir, gider ve borç göstergelerini", "maliye politikalarının refah etkilerini", [0,1,2,3,9], [6,10]],
  "İKT721":["kamu mali yönetimi ve denetim sistemlerini", "bütçe, performans ve denetim bulgularını", "hesap verebilirlik ve mali yönetişim uygulamalarını", [0,1,2,3,7,9], [8,10]],
  "İKT723":["güncel vergileme yaklaşımlarını", "vergi yapısı ve uyum göstergelerini", "vergi reformlarının ekonomik etkilerini", [0,1,2,3,7,9], [6,10]],
  "İKT704":["temel ve teknik analiz yaklaşımlarını", "finansal tablo, fiyat ve hacim verilerini", "yatırım seçeneklerini risk sınırlarıyla", [0,1,4,5,7], [2,9,10]],
  "İKT706":["finansal kriz kuramlarını", "kırılganlık ve erken uyarı göstergelerini", "kriz yönetimi politikalarını", [0,1,2,3,5,6], [7,9,10]],
  "İKT708":["para ve bankacılık sistemini", "banka bilançosu, kredi ve para göstergelerini", "bankacılık riskleri ile düzenleme seçeneklerini", [0,1,3,5,7], [2,9,10]],
  "İKT710":["uluslararası finans kuramlarını", "sermaye hareketleri ve dış finansman verilerini", "uluslararası yatırım ve risk seçeneklerini", [0,1,4,5,6,7], [2,9,10]],
  "İKT712":["güncel ekonomik sorunların kuramsal temellerini", "güncel makroekonomik ve sosyal göstergeleri", "alternatif politika seçeneklerini", [0,1,2,3,6,10], [7,9]],
  "İKT714":["ekonomik ve finansal tahmin yaklaşımlarını", "zaman serisi ve öncü gösterge verilerini", "tahmin modelleri ile belirsizlik sonuçlarını", [0,1,2,7,10], [3,4,5]],
  "İKT716":["kamu borçlanması kuramlarını", "borç portföyü ve sürdürülebilirlik göstergelerini", "finansman seçenekleri ile mali riskleri", [0,1,3,5,7], [2,6,9]],
  "İKT718":["menkul ve gayrimenkul kıymetlerin vergilendirilmesini", "getiri, değer artışı ve vergi yükü göstergelerini", "vergilemenin yatırım kararlarına etkilerini", [0,1,3,4,7,9], [2,5,10]],
  "İKT720":["uluslararası mali gelişmelerin kuramsal çerçevesini", "küresel vergi, harcama ve borç göstergelerini", "uluslararası mali kararların ekonomik etkilerini", [0,1,3,6,7,10], [2,5,9]],
};

const checklist = ["Ders adı ve kodları doğrulandı mı?","Tüm OBS bağlantıları gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const qualityChecks = () => checklist.map((item, index) => ({ item, status:[2,20,21].includes(index+1)?"Doğrulanmalı":[4,6,7,8,9,10,11,12,13,14,15,16,17,19].includes(index+1)?"Revize Edildi":"Uygun", ...([2,20,21].includes(index+1)?{note:"Kesin OBS ayrıntı bağlantısı bulunmadığından resmî katalog bilgisi korunmuş, eksik akademik alanlar öneri niteliğinde tamamlanmıştır."}:{}) }));
const matrix = (outcomes, primary, secondary) => outcomes.map((_, row) => ({ outcome:`DÖÇ${row+1}`, values:programOutcomes.map((__, col) => primary.includes(col) ? (row===0?5:row<3?4:3) : secondary.includes(col) ? (row<2?3:2) : 1 + ((row+col)%2)) }));
const resourcesFor = (code) => {
  if (["İKT707","İKT709","İKT711","İKT708","İKT712","İKT714"].includes(code)) return "TCMB Elektronik Veri Dağıtım Sistemi (EVDS); TÜİK Veri Portalı; IMF World Economic Outlook ve International Financial Statistics; OECD Data Explorer.";
  if (["İKT705","İKT704","İKT706","İKT710","İKT715"].includes(code)) return "TCMB EVDS; Borsa İstanbul piyasa ve eğitim kaynakları; BIS Statistics; IMF Data; güncel hakemli finans literatürü.";
  if (["İKT719","İKT721","İKT723","İKT716","İKT718","İKT720"].includes(code)) return "T.C. Hazine ve Maliye Bakanlığı istatistik ve raporları; Gelir İdaresi Başkanlığı mevzuat ve rehberleri; OECD Revenue Statistics; IMF Fiscal Monitor.";
  return "TÜİK Veri Portalı; TCMB EVDS; Dünya Bankası World Development Indicators; OECD Data Explorer; güncel hakemli ekonomi ve finans literatürü.";
};
const workload = (course, assessments) => {
  const target = Number(course.ects)*30;
  const rows = [{name:"Ders Süresi",count:15,hours:Number(course.theory)+Number(course.practice),total:15*(Number(course.theory)+Number(course.practice))}];
  for (const item of assessments) {
    const key=item.name.toLocaleLowerCase("tr-TR"); const count=Number(item.count||1);
    if(key.includes("ödev")) rows.push({name:"Ödev Hazırlığı",count,hours:8,total:count*8});
    else if(key.includes("ara sınav")) rows.push({name:"Ara Sınav Hazırlığı",count,hours:20,total:count*20});
    else if(key.includes("yarıyıl sonu")) rows.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count,hours:25,total:count*25});
  }
  const used=rows.reduce((sum,row)=>sum+row.total,0); const outside=Math.max(0,Math.floor(((target-used)/15)*2)/2);
  rows.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:outside,total:outside*15});
  const delta=target-rows.reduce((sum,row)=>sum+row.total,0); if(delta) rows.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:delta,total:delta});
  return rows;
};
const academic = official.filter((course)=>!['İKT701','İKT702'].includes(course.code)).map((course)=>{
  const name=titles[course.code]; const meta=focus[course.code]; const weeklyTopics=plans[course.code];
  if(!name||!meta||weeklyTopics?.length!==15) throw new Error(`${course.code}: ders taslağı eksik.`);
  const [theoryFocus,dataFocus,decisionFocus,primary,secondary]=meta;
  const outcomes=[`${theoryFocus.charAt(0).toLocaleUpperCase('tr-TR')+theoryFocus.slice(1)} ileri düzeyde analiz eder.`,`${dataFocus.charAt(0).toLocaleUpperCase('tr-TR')+dataFocus.slice(1)} uygun göstergelerle yorumlar.`,`${decisionFocus.charAt(0).toLocaleUpperCase('tr-TR')+decisionFocus.slice(1)} karşılaştırmalı olarak değerlendirir.`,`${name} kapsamındaki bir probleme kanıta dayalı çözüm geliştirir.`,`${name} alanındaki kararları mesleki ve etik ilkelerle gerekçelendirir.`];
  const assessments=[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}];
  return {code:course.code,name,department,programName,language:"Türkçe",level,teachingMode:"Yüz Yüze",instructor:course.instructor||"Atama Bekliyor",theory:Number(course.theory),practice:Number(course.practice),credit:Number(course.credit),ects:Number(course.ects),prerequisites:"Yok",purpose:`Öğrencinin ${theoryFocus}, ${dataFocus} ve ${decisionFocus} ileri düzey ekonomi ve finans bilgisiyle değerlendirebilmesini sağlamak.`,content:`Ders kapsamında ${weeklyTopics.slice(0,5).join(", ")}; veri çözümleme, karar verme, mesleki sorumluluk ve güncel gelişmelerle ilişkilendirilerek ele alınır.`,methods:"Anlatım, yönlendirilmiş tartışma, güncel ekonomik ve finansal veri çözümleme, vaka incelemesi ve bireysel çalışma.",resources:resourcesFor(course.code),sdgs:course.code==='İKT703'?[4,8,16].map(String):course.code.match(/719|721|723|716|718|720/)?[8,10,16].map(String):[8,9,10].map(String),outcomes,weeklyTopics,assessments,workloads:workload(course,assessments),contributionMatrix:matrix(outcomes,primary,secondary),qualityChecks:qualityChecks(),publicQualityChecklist:false};
});

const projectOutcomes=["Ekonomi veya finans alanında uygulanabilir bir proje problemi yapılandırır.","Proje problemine ilişkin ekonomik ve finansal kaynakları eleştirel değerlendirir.","Proje amacına uygun veri ve çözümleme yaklaşımını planlar.","Proje bulgularını mesleki, ekonomik ve etik ölçütlerle yorumlar.","Bitirme projesini akademik yazım ilkelerine uygun biçimde raporlar."];
const projectWeeks=["Bitirme projesi alanının ve kapsamının belirlenmesi","Ekonomik veya finansal problemin sınırlandırılması","Proje amacı ve araştırma sorularının yapılandırılması","Ekonomi ve finans kaynakları için tarama stratejisi","Alan yazınının tematik sınıflandırılması","Kuramsal ve uygulamalı çerçevenin kurulması","Veri kaynaklarının ve göstergelerin belirlenmesi","Çözümleme yaklaşımı ile iş planının yapılandırılması","Etik, veri güvenliği ve izin gerekliliklerinin değerlendirilmesi","Ekonomik ve finansal verilerin düzenlenmesi","Bulguların çözümlenmesi ve yorumlanması","Bulguların alan yazınıyla karşılaştırılması","Politika, yatırım veya yönetim çıkarımlarının geliştirilmesi","Akademik proje metni, atıf ve kaynakça düzeni","Bitirme projesinin bütüncül değerlendirilmesi"];
const project={code:"İKT7XX",aliases:["İKT701","İKT702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin ekonomi ve finans alanındaki ileri düzey bilgi ve becerilerini mesleki bir problem üzerinde bütünleştirerek bilimsel ve etik ölçütlere uygun bir bitirme projesi yürütmesini sağlamak.",content:"Ekonomi veya finans alanında proje probleminin belirlenmesi, kaynak ve veri incelemesi, çözümleme yaklaşımının planlanması, bulguların yorumlanması ve sonuçların akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışmanlık görüşmesi, literatür ve veri incelemesi, ekonomik çözümleme, akademik raporlama ve yapılandırılmış geri bildirim.",resources:"Enstitü proje yazım ilkeleri; TÜİK Veri Portalı; TCMB EVDS; Dünya Bankası, IMF ve OECD veri kaynakları; ilgili güncel hakemli yayınlar.",sdgs:["4","8","16"],outcomes:projectOutcomes,weeklyTopics:projectWeeks,assessments:[{name:"Bitirme Projesi",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışmanlık",count:15,hours:2,total:30},{name:"Literatür ve Veri İncelemesi",count:15,hours:20,total:300},{name:"Çözümleme ve Raporlama",count:15,hours:38,total:570}],contributionMatrix:matrix(projectOutcomes,[0,1,2,4,5,7,8,9,10],[3,6]),qualityChecks:qualityChecks(),publicQualityChecklist:false};

if(academic.length!==20) throw new Error(`20 akademik ders bekleniyordu; bulunan: ${academic.length}`);
for(const course of [...academic,project]){
  if(course.weeklyTopics.length!==15) throw new Error(`${course.code}: 15 hafta yok.`);
  if(course.code!=="İKT7XX"&&course.weeklyTopics.some((topic)=>/(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|vize|final)/iu.test(topic))) throw new Error(`${course.code}: yasak haftalık başlık.`);
  if(course.workloads.reduce((sum,row)=>sum+row.total,0)!==course.ects*30) throw new Error(`${course.code}: AKTS iş yükü tutarsız.`);
  if(course.contributionMatrix.some((row)=>row.values.length!==11||row.values.some((value)=>value<1||value>5))) throw new Error(`${course.code}: DÖÇ-PÇ matrisi geçersiz.`);
}
const emit=(file,exportName,value)=>writeFileSync(path.join(root,"lib/data",file),`import type { CoursePackage } from "./coursePackages";\n\nexport const ${exportName}: CoursePackage[] = ${JSON.stringify(value,null,2)};\n`);
emit("ekonomiFinansTezsizCoursePackages.ts","ekonomiFinansTezsizCoursePackages",academic);
emit("ekonomiFinansTezsizCommonCoursePackages.ts","ekonomiFinansTezsizCommonCoursePackages",[project]);
console.log(JSON.stringify({official:official.length,academic:academic.length,common:1,total:academic.length+1,programOutcomes:programOutcomes.length}));
