import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const naturalCase=(v="")=>{const text=clean(v);if(!text||text!==text.toLocaleUpperCase("tr-TR"))return text;return cap(text.toLocaleLowerCase("tr-TR")).replace(/^Iso\b/u,"ISO")};
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="gida muhendisligi tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["Gıda mühendisliğindeki ileri düzey bilgileri uygular.","Gıda sistemlerindeki sorunları bilimsel yöntemlerle analiz eder.","Gıda proseslerini tasarlar ve optimize eder.","Deneysel ve analitik yöntemleri uygular ve değerlendirir.","Gıda verilerini analiz eder ve yorumlar.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Disiplinler arası çalışmalarda iş birliği yapar ve sorumluluk alır.","Bilimsel ve teknik çalışmalarını etkili biçimde sunar.","Bilimsel, mesleki ve etik ilkeleri uygular.","Gıda sistemlerini kalite, güvenlik ve sürdürülebilirlik açısından değerlendirir.","Güncel gıda teknolojilerini izler ve çalışmalarına uygular."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Gıda Mühendisliği ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/mikrobiy|mikotoksin|ferment|immobilize|enzim/u.test(n))return{label:"gıda mikrobiyolojisi ve biyoteknolojisi",core:[1,2,4],sdgs:["2","3","9"],terms:["mikrobiyal sistemlerin özellikleri","gıda mikrobiyotasının gelişimi","fermantasyon kinetiği","enzim ve hücre teknolojileri","mikrobiyal analiz yöntemleri","proses değişkenlerinin denetimi","ürün güvenliği ve kalite","biyoteknolojik uygulamalar"]};
 if(/meyve|sebze|tahil|bugday|ekmek|sut|peynir|dondurma/u.test(n))return{label:"gıda ürünleri ve proses teknolojileri",core:[1,3,10],sdgs:["2","9","12"],terms:["hammadde özellikleri","ürün bileşimi ve kalite ölçütleri","proses akışının tasarımı","temel işleme basamakları","proses değişkenleri","ürün kalite kayıpları","depolama ve raf ömrü","sürdürülebilir üretim seçenekleri"]};
 if(/kimya|biyokimya|karbonhidrat|biyoaktif|aroma|renk|reo|su aktiv/u.test(n))return{label:"gıda kimyası ve fiziksel özellikler",core:[1,4,5],sdgs:["2","3","12"],terms:["gıda bileşenlerinin yapısı","kimyasal ve biyokimyasal reaksiyonlar","faz ve moleküler etkileşimler","fiziksel özelliklerin ölçümü","reaksiyon kinetiği","analitik veri değerlendirme","işleme sırasında değişimler","kalite ve stabilite ilişkisi"]};
 if(/analiz|kromatografi|deney|arastirma|istatistik|bilimsel/u.test(n))return{label:"deneysel ve analitik gıda araştırmaları",core:[4,5,6],sdgs:["4","9","17"],terms:["araştırma problemi","deneysel tasarım","örnekleme ve numune hazırlama","analitik yöntem seçimi","cihaz kalibrasyonu ve yöntem doğrulama","veri analizi ve belirsizlik","bulguların yorumlanması","bilimsel raporlama ve etik"]};
 if(/muhafaza|isil|kurutma|ambalaj|paket|raf omru|depolama/u.test(n))return{label:"gıda muhafaza ve ambalajlama prosesleri",core:[2,3,10],sdgs:["2","9","12"],terms:["bozulma mekanizmaları","ısı ve kütle aktarımı","muhafaza proseslerinin tasarımı","ısıl ve ısıl olmayan yöntemler","ambalaj malzemesi özellikleri","raf ömrü modelleme","proses doğrulama","enerji ve kaynak verimliliği"]};
 if(/mevzuat|kalite|organik|beslenme|urun gelistirme/u.test(n))return{label:"gıda kalite, güvenlik ve ürün geliştirme",core:[3,9,10],sdgs:["2","3","12"],terms:["gıda mevzuatı ve standartlar","tehlike ve risk analizi","kalite güvence sistemleri","ürün gereksinimlerinin belirlenmesi","formülasyon ve proses seçimi","duyusal ve analitik doğrulama","etiketleme ve izlenebilirlik","sürdürülebilir ürün geliştirme"]};
 return{label:"ileri gıda mühendisliği",core:[1,2,11],sdgs:["2","9","12"],terms:["gıda sistemlerinin mühendislik analizi","kütle ve enerji dengeleri","proses değişkenleri","deneysel ölçüm ve modelleme","proses tasarımı ve optimizasyon","ürün güvenliği ve kalite","sürdürülebilir üretim","güncel gıda teknolojileri"]};};
const generatedWeeks=(name,d)=>{const s=prose(name).replace(/projeleri?/giu,"çalışmaları").replace(/sunumu?/giu,"anlatımı");return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).filter((x)=>!forbiddenWeekTopic(x)).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbiddenWeekTopic=(value)=>["quiz","kisa sinav","odev","proje","sunum","konu tekrari","genel tekrar","ara sinav","arasinav","arasınav","vize","final","yariyil sonu"].some((term)=>fold(value).includes(term));
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|GMB80[1-8]|GMB85[36])$/u;
const academic=official.filter((o)=>!common.test(o.code)).map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbiddenWeekTopic(clean(x[1]))).map((x)=>naturalCase(x[1]))),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Gıda Mühendisliği ABD",programName:"Gıda Mühendisliği",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:naturalCase(detail(c,"dersin amaci"))||`${cap(sub)} alanındaki ileri yaklaşımları bilimsel ölçütlerle analiz etme ve gıda mühendisliği uygulamalarına aktarma yetkinliği kazandırmak.`,content:naturalCase(detail(c,"dersin icerigi"))||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:naturalCase(detail(c,"dersin yontem ve teknikleri"))||"Kuramsal anlatım, bilimsel kaynak incelemesi, örnek olay çözümlemesi, uygulama verilerinin değerlendirilmesi ve akademik tartışma.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"Gıda mühendisliği ve gıda bilimi alanındaki temel kaynaklar; güncel hakemli alan literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin gıda mühendisliği araştırmasını bilimsel yöntem, sürdürülebilirlik ve etik ilkeler doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, gıda mühendisliği literatürü, araştırma problemi, yöntem, saha etiği, veri yönetimi, ilerleme ve raporlama.",stages:["Akademik çalışma planı","Gıda mühendisliği araştırma alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Sürdürülebilirlik ve etik gereklilikler","Araştırma tasarımının değerlendirilmesi","Saha ve veri toplama planı","Araştırma kayıtlarının kontrolü","Bulguların ön değerlendirmesi","Analiz yaklaşımının gözden geçirilmesi","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Akademik ilerleme izlemesi","Sonraki dönem çalışma planı"]},
{code:"GMB8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili ileri gıda mühendisliği literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal-yöntemsel altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü gıda mühendisliği ve gıda teknolojisi literatürü, araştırma problemi, kuramsal çerçeve, deneysel yöntem, proses güvenliği, sürdürülebilirlik ve etik.",stages:["Tez alanının bilimsel kapsamı","İleri gıda mühendisliği literatürü","Kuramsal yaklaşımlar","Araştırma boşluğunun tanımlanması","Araştırma soruları","Kuramsal varsayımlar","Deneysel araştırma desenleri","Örnekleme yaklaşımı","Laboratuvar, proses ve veri kaynakları","Veri kalite ölçütleri","Analiz seçenekleri","Bulguların gıda mühendisliği açısından yorumlanması","Gıda güvenliği ve etik riskler","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"GMB806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Gıda mühendisliği alanındaki bilimsel bir problemi literatüre dayalı inceleme, akademik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, araştırma problemi, kanıt sentezi, bilimsel metin, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Literatür tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Gıda mühendisliği kanıtlarının karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve bulguların sentezi","Tablo ve görsellerin düzenlenmesi","Bilimsel tartışmanın yapılandırılması","Sonuç ve çıkarımlar","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel anlatımın uygulanması","Geri bildirimle nihai düzenleme"]},
{code:"GMB85X",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Gıda mühendisliği araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, analiz etme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, deneysel tasarım, örnekleme ve numune hazırlama, analitik veri toplama, istatistiksel çözümleme, yöntem doğrulama, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve gıda mühendisliği araştırması","Araştırma problemi ve hipotez","Deneysel araştırma tasarımları","Değişken ve kontrol grupları","Örnekleme ve numune hazırlama","Analitik yöntem seçimi","Ölçüm güvenilirliği ve belirsizlik","İstatistiksel veri analizi","Yöntem doğrulama ve kalite güvencesi","Bulguların mühendislik açısından yorumlanması","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"GMB81X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin gıda mühendisliği alanında bağımsız bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün gıda mühendisliği araştırma problemi, literatür sentezi, araştırma tasarımı, saha etiği, veri üretimi, analiz, sürdürülebilirlik bağlamında yorum, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve hipotezlerin yapılandırılması","Yöntem ve örnekleme planı","Etik ve saha izinleri","Veri toplama planı","Saha kayıtları ve kalite kontrolü","Veri toplama sürecinin izlenmesi","Verilerin düzenlenmesi","Analizlerin yürütülmesi","Bulguların gıda mühendisliği açısından yorumlanması","Bulguların literatürle karşılaştırılması","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="GMB806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="GMB85X"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Gıda Mühendisliği ABD",programName:"Gıda Mühendisliği",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="GMB85X"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="GMB85X"?"Prof. Dr. HANDE DEMİR":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, deneysel ve analitik verilerin çözümlemesi, mühendislik modellemesi, akademik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"Gıda mühendisliği, gıda bilimi ve proses teknolojisi alanındaki temel kaynaklar; güncel hakemli alan literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","gidaMuhendisligiTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const gidaMuhendisligiTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","gidaMuhendisligiCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const gidaMuhendisligiCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));
