import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="fizik tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["İleri düzey fizik bilgilerini uygular ve bütünleştirir.","Fiziksel problemleri analiz eder ve modeller.","Deneyleri tasarlar, yürütür ve değerlendirir.","Deneysel verileri istatistiksel yöntemlerle analiz eder ve yorumlar.","Fizik temelli teknolojik çözümler geliştirir.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Disiplinler arası çalışmalarda iş birliği yapar ve sorumluluk alır.","Bilimsel çalışmalarını yazılı ve sözlü olarak sunar.","Bilimsel, mesleki ve etik ilkeleri uygular.","Fizik uygulamalarını kalite, güvenlik ve toplumsal etki açısından değerlendirir.","Bilimsel hesaplama ve güncel teknolojileri etkin kullanır."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Fizik ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/nukleer|radyasyon|reaktor|notron|parcacik|cekirdek|gama|radyoaktif|dedektor|zirhlama/u.test(n))return{label:"nükleer fizik ve radyasyon",core:[1,2,3],sdgs:["3","7","9"],terms:["çekirdek yapısı ve etkileşimler","radyoaktif bozunma süreçleri","nükleer reaksiyon kinematiği","nötron ve parçacık taşınımı","radyasyon-madde etkileşimi","algılama ve ölçüm sistemleri","doz, zırhlama ve güvenlik","nükleer uygulamaların değerlendirilmesi"]};
 if(/katihal|malzeme|kristal|superiletken|fonon|yogun madde|bant/u.test(n))return{label:"katıhal ve malzeme fiziği",core:[1,2,5],sdgs:["7","9","12"],terms:["kristal yapı ve simetri","bağlanma ve örgü dinamiği","elektronik bant yapısı","fononlar ve ısıl özellikler","manyetik ve elektriksel özellikler","malzeme üretim teknikleri","karakterizasyon yöntemleri","işlevsel malzeme uygulamaları"]};
 if(/optik|optoelektronik|yariiletken|metal yari|luminesans|x isin/u.test(n))return{label:"optik ve yarıiletken fiziği",core:[1,2,5],sdgs:["7","9","12"],terms:["elektromanyetik dalgalar ve optik","ışık-madde etkileşimi","optik ölçüm ilkeleri","yarıiletken bant yapısı","taşıyıcıların üretimi ve taşınımı","eklem ve kontak fiziği","optoelektronik aygıtlar","ölçüm ve aygıt uygulamaları"]};
 if(/yildiz|astronomi|gunes|tayf/u.test(n))return{label:"astrofizik",core:[1,2,4],sdgs:["4","7","9"],terms:["gök koordinatları ve gözlemsel veriler","ışınım ve tayf oluşumu","yıldız yapısı ve evrimi","yıldızlararası ortam","çift yıldız sistemleri","Güneş fiziği","astronomik ölçüm ve veri analizi","güncel astrofizik araştırmaları"]};
 if(/matematik|ortogonal|modelleme|sayisal|yapay sinir|fonksiyonel teori|simulasyon|difüzyon/u.test(n))return{label:"matematiksel ve hesaplamalı fizik",core:[2,4,11],sdgs:["4","9","17"],terms:["fiziksel problemin matematiksel formülasyonu","diferansiyel ve integral yöntemler","özdeğer problemleri","ortogonal fonksiyonlar","sayısal çözüm yöntemleri","hesaplamalı modelleme","doğrulama ve hata analizi","fiziksel sonuçların yorumlanması"]};
 if(/akademik turkce|arastirma|bilimsel/u.test(n))return{label:"fizikte bilimsel araştırma ve iletişim",core:[6,8,9],sdgs:["4","9","17"],terms:["bilimsel araştırma problemi","fizikte deneysel ve kuramsal desenler","literatür tarama ve kaynak eleştirisi","veri ve belirsizlik analizi","bilimsel metin yapısı","atıf ve kaynak gösterme","araştırma ve yayın etiği","bilimsel sonuçların sunumu"]};
 return{label:"ileri fizik",core:[1,2,3],sdgs:["4","9","12"],terms:["ileri fizik kavramları","kuramsal model ve varsayımlar","fiziksel nicelikler ve bağıntılar","deneysel veya hesaplamalı yöntemler","ölçüm ve veri analizi","model doğrulama","teknolojik uygulamalar","güncel fizik araştırmaları"]};};
const generatedWeeks=(name,d)=>{const s=prose(name);return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbiddenWeekTopic=(value)=>["quiz","kisa sinav","odev","proje","sunum","konu tekrari","genel tekrar","ara sinav","vize","final","yariyil sonu"].some((term)=>fold(value).includes(term));
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|FZK80[1-8]|FZK89[89])$/u;
const academic=official.filter((o)=>!common.test(o.code)).map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbiddenWeekTopic(clean(x[1]))).map((x)=>x[1])),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Fizik ABD",programName:"Fizik",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:detail(c,"dersin amaci")||`${cap(sub)} alanındaki temel metinleri ve ileri kuramsal yaklaşımları analiz etme, karşılaştırma ve bilimsel ölçütlerle yorumlama yetkinliği kazandırmak.`,content:detail(c,"dersin icerigi")||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:detail(c,"dersin yontem ve teknikleri")||"Kuramsal anlatım, kaynak ve metin çözümlemesi, karşılaştırmalı tartışma ve araştırma bulgularının değerlendirilmesi.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"Fizik alanındaki temel kaynaklar; güncel hakemli alan literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin fizik alanındaki lisansüstü araştırmasını bilimsel yöntem, etik ilkeler ve akademik takvim doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, fizik literatürü, araştırma problemi, kuramsal veya deneysel yöntem seçimi, veri yönetimi, etik, ilerleme izlemesi ve bilimsel raporlama.",stages:["Akademik çalışma planı","Fizik uzmanlık alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Araştırma soruları ve hipotezler","Kuramsal veya deneysel yöntem seçimi","Ölçüm ve veri planı","Bilimsel etik ve laboratuvar güvenliği","İlerleme kayıtlarının değerlendirilmesi","Analiz yaklaşımının gözden geçirilmesi","Fiziksel bulguların yorumu","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Sonraki dönem çalışma planı"]},
{code:"FZK8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili ileri fizik literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal, deneysel ve hesaplamalı altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü güncel fizik literatürü, kuramsal modeller, araştırma problemi, deney veya hesaplama yöntemi, ölçüm, veri analizi, doğrulama, güvenlik ve etik.",stages:["Tez alanının bilimsel kapsamı","İleri fizik literatürü","Kuramsal model ve varsayımlar","Araştırma boşluğunun tanımlanması","Araştırma soruları ve hipotezler","Fiziksel sistemin sınırlarının belirlenmesi","Deneysel ve hesaplamalı yöntem seçenekleri","Deney veya benzetim tasarımı","Ölçüm, belirsizlik ve veri güvenilirliği","Fiziksel performans ölçütleri","Bulguların kuramsal yorumu","Alternatif modellerin karşılaştırılması","Güvenlik ve etik gereklilikler","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"FZK806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Fizik alanındaki bilimsel bir problemi literatüre dayalı inceleme, teknik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, fizik probleminin yapılandırılması, kuramsal ve deneysel kanıt sentezi, bilimsel yazım, görsel veri sunumu, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Fizik literatürünü tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Kuramsal ve deneysel çalışmaların karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve kanıtların sentezi","Denklem, tablo ve şekillerin düzenlenmesi","Bilimsel tartışmanın yapılandırılması","Sonuç ve fizik çıkarımları","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel savununun yapılandırılması","Geri bildirimle nihai düzenleme"]},
{code:"FZK899",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Fizik araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, çözümleme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, deneysel ve kuramsal fizik araştırma desenleri, ölçüm ve veri toplama, belirsizlik ve istatistiksel çözümleme, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve fizik araştırması","Araştırma problemi ve hipotez","Kuramsal araştırma tasarımı","Deneysel araştırma tasarımı","Örnekleme ve ölçüm planı","Veri toplama sistemleri","Ölçüm belirsizliği ve hata","İstatistiksel veri analizi","Bulguların fiziksel yorumu","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Laboratuvar güvenliği ve bilimsel sorumluluk","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"FZK81X",name:"YÜKSEK LİSANS TEZİ",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin fizik alanında özgün bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün fizik problemi, literatür sentezi, kuramsal model, deney veya hesaplama tasarımı, veri üretimi, belirsizlik analizi, doğrulama, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve hipotezlerin yapılandırılması","Fiziksel modelin geliştirilmesi","Yöntem ve doğrulama planı","Etik ve güvenlik gereklilikleri","Deney veya hesaplama altyapısı","Veri üretimi ve kalite kontrolü","Verilerin düzenlenmesi","Analizlerin yürütülmesi","Bulguların fiziksel açıdan yorumlanması","Bulguların literatürle karşılaştırılması","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}
];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="FZK806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="FZK899"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Fizik ABD",programName:"Fizik",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="FZK899"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="FZK899"?"Dr. Öğr. Üyesi NAZMİ SEDEFOĞLU":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, matematiksel modelleme, teknik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"Fizik alanındaki temel kaynaklar; güncel hakemli alan literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","fizikTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const fizikTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","fizikCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const fizikCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));




