import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="elektrik-elektronik muhendisligi tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["Elektrik-elektronik mühendisliğindeki ileri düzey bilgileri uygular.","Karmaşık mühendislik problemlerini analiz eder ve modeller.","Elektrik-elektronik sistemleri tasarlar ve optimize eder.","Modern mühendislik yöntem ve araçlarını seçer ve kullanır.","Deneysel çalışmaları tasarlar, yürütür ve yorumlar.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Disiplinler arası ekiplerde iş birliği yapar ve sorumluluk alır.","Bilimsel ve teknik çalışmalarını etkili biçimde sunar.","Bilimsel, mesleki ve etik ilkeleri uygular.","Mühendislik çözümlerini sürdürülebilirlik ve toplumsal etki açısından değerlendirir.","Güncel bilimsel ve teknolojik gelişmeleri izler ve çalışmalarına uygular."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Elektrik Elektronik Mühendisliği ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/haberlesme|enformasyon|kod|uydu|optik kablosuz|anten|propagasyon|mikrodalga|radar/u.test(n))return{label:"haberleşme ve elektromanyetik sistemler",core:[1,2,3],sdgs:["9","11","17"],terms:["sistem modeli ve temel ilkeler","işaret ve kanal gösterimleri","analitik çözüm yöntemleri","tasarım parametreleri","performans ölçütleri","gürültü ve belirsizlik","benzetim ve doğrulama","güncel haberleşme uygulamaları"]};
 if(/guc|gerilim|evirici|donusturucu|kiyici|enerji|turb|ruzgar|gunes|hidroelektrik|anahtarlamali/u.test(n))return{label:"güç elektroniği ve enerji sistemleri",core:[2,3,10],sdgs:["7","9","13"],terms:["enerji dönüşümünün temelleri","devre ve sistem modelleri","anahtarlama yapıları","denetim stratejileri","kararlılık ve güç kalitesi","kayıp ve verim analizi","tasarım doğrulama","sürdürülebilir enerji uygulamaları"]};
 if(/goruntu|oruntu|yapay|ogrenme|veri|dogal dil|sinir|bulan|gri|siniflandirma|modelleme/u.test(n))return{label:"yapay zekâ ve veri işleme",core:[2,3,4],sdgs:["4","9","10"],terms:["veri gösterimi ve ön işleme","özellik çıkarımı","model kurma ilkeleri","öğrenme ve kestirim yöntemleri","başarım ölçütleri","doğrulama ve genelleme","hesaplama araçları","etik ve güvenilir yapay zekâ"]};
 if(/biyomedikal|norobilim|tibbi|biyoelektromanyetik|algilayici/u.test(n))return{label:"biyomedikal ve algılayıcı sistemler",core:[2,4,5],sdgs:["3","9","10"],terms:["biyolojik sistemlerin mühendislik temelleri","algılayıcı ve ölçüm ilkeleri","sinyal edinimi","gürültü ve ön işleme","özellik ve parametre çıkarımı","sistem tasarımı","deneysel doğrulama","güvenlik ve etik"]};
 if(/matematik|sayisal yontem|istatistik|olasilik|rastgele|optimizasyon|kestirim|spektral/u.test(n))return{label:"matematiksel modelleme ve kestirim",core:[1,2,4],sdgs:["4","9","17"],terms:["ileri matematiksel gösterimler","lineer ve doğrusal olmayan modeller","olasılık ve rastgele değişkenler","sayısal çözüm teknikleri","kestirim ve optimizasyon","hata ve yakınsama analizi","hesaplamalı doğrulama","mühendislik problem uygulamaları"]};
 if(/gomulu|sayisal tasarim|bilgisayar/u.test(n))return{label:"sayısal ve gömülü sistem tasarımı",core:[2,3,4],sdgs:["9","11","12"],terms:["sayısal sistem mimarileri","donanım-yazılım birlikte tasarımı","işlemci ve çevrebirimler","gerçek zamanlı gereksinimler","haberleşme arayüzleri","tasarım ve doğrulama araçları","başarım ve kaynak analizi","güvenilir sistem uygulamaları"]};
 return{label:"elektrik-elektronik mühendisliği",core:[1,2,3],sdgs:["7","9","11"],terms:["ileri alan kavramları","matematiksel modelleme","sistem analizi","tasarım yöntemleri","modern mühendislik araçları","deneysel veya hesaplamalı doğrulama","performans ve güvenilirlik","güncel mühendislik uygulamaları"]};};
const generatedWeeks=(name,d)=>{const s=prose(name);return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbidden=/\b(quiz|kısa sınav|odev|ödev|proje|sunum|konu tekrarı|genel tekrar|ara sınav|vize|final|yarıyıl sonu)\b/iu;
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|EEM80[1-8]|EEM885)$/u;
const academic=official.filter((o)=>!common.test(o.code)).map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbidden.test(clean(x[1]))).map((x)=>x[1])),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Elektrik Elektronik Mühendisliği ABD",programName:"Elektrik Elektronik Mühendisliği",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:detail(c,"dersin amaci")||`${cap(sub)} alanındaki ileri modelleri analiz etme, uygun mühendislik yöntemlerini seçme ve çözüm sonuçlarını doğrulama yetkinliği kazandırmak.`,content:detail(c,"dersin icerigi")||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:detail(c,"dersin yontem ve teknikleri")||"Kuramsal anlatım, matematiksel modelleme, teknik problem çözümü, benzetim veya deney sonuçlarının tartışılması.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"NIST sensör ve ölçüm bilimi yayınları; NIST TN 1297 ölçüm belirsizliği rehberi; güncel hakemli algılayıcı sistemleri literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin elektrik-elektronik mühendisliği alanındaki lisansüstü araştırmasını bilimsel yöntem, mühendislik etiği ve akademik takvim doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, mühendislik literatürü, araştırma problemi, yöntem seçimi, veri yönetimi, etik, ilerleme izlemesi ve bilimsel raporlama.",stages:["Akademik çalışma planı","Uzmanlık alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Araştırma soruları ve hedefler","Yöntem seçeneklerinin değerlendirilmesi","Veri ve deney planı","Mühendislik etiği ve güvenlik","İlerleme kayıtlarının değerlendirilmesi","Analiz yaklaşımının gözden geçirilmesi","Bulguların teknik yorumu","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Sonraki dönem çalışma planı"]},
{code:"EEM8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili ileri elektrik-elektronik mühendisliği literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal, deneysel ve hesaplamalı altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü güncel literatür, ileri mühendislik modelleri, araştırma problemi, yöntem ve araç seçimi, deney veya benzetim tasarımı, doğrulama, güvenilirlik ve etik.",stages:["Tez alanının bilimsel kapsamı","İleri alan literatürü","Kuramsal model ve varsayımlar","Araştırma boşluğunun tanımlanması","Araştırma soruları","Analitik çözüm yaklaşımları","Sayısal yöntem seçenekleri","Deney veya benzetim tasarımı","Veri ve ölçüm güvenilirliği","Doğrulama ölçütleri","Bulguların mühendislik yorumu","Alternatif çözümlerin karşılaştırılması","Etik ve güvenlik gereklilikleri","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"EEM806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Elektrik-elektronik mühendisliği alanındaki bilimsel bir problemi literatüre dayalı inceleme, teknik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, mühendislik probleminin yapılandırılması, teknik kanıt sentezi, bilimsel yazım, görsel veri sunumu, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Literatür tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Teknik yaklaşımların karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve kanıtların sentezi","Tablo, şekil ve bağıntıların düzenlenmesi","Bilimsel tartışmanın yapılandırılması","Sonuç ve mühendislik çıkarımları","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel anlatımın uygulanması","Geri bildirimle nihai düzenleme"]},
{code:"EEM885",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Elektrik-elektronik mühendisliği araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, çözümleme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, mühendislik araştırma desenleri, deney ve benzetim tasarımı, veri toplama, istatistiksel çözümleme, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve mühendislik araştırması","Araştırma problemi ve hipotez","Deneysel araştırma tasarımı","Hesaplamalı araştırma tasarımı","Örnekleme ve ölçüm planı","Veri toplama sistemleri","Geçerlik, güvenirlik ve belirsizlik","Veri analizi yaklaşımları","Bulguların teknik yorumu","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Mühendislik etiği ve güvenlik","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"EEM81X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin elektrik-elektronik mühendisliği alanında özgün bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün mühendislik problemi, literatür sentezi, matematiksel model, deney veya benzetim tasarımı, veri üretimi, analiz, doğrulama, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve hipotezlerin yapılandırılması","Kuramsal modelin geliştirilmesi","Yöntem ve doğrulama planı","Etik ve güvenlik gereklilikleri","Deney veya benzetim altyapısı","Veri üretimi ve kalite kontrolü","Verilerin düzenlenmesi","Analizlerin yürütülmesi","Bulguların mühendislik açısından yorumlanması","Bulguların literatürle karşılaştırılması","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}
];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="EEM806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="EEM885"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Elektrik Elektronik Mühendisliği ABD",programName:"Elektrik Elektronik Mühendisliği",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="EEM885"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="EEM885"?"Doç. Dr. HALİL EROL":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, matematiksel modelleme, teknik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"IEEE ve NIST mühendislik yayınları; güncel hakemli elektrik-elektronik mühendisliği literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","elektrikElektronikTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const elektrikElektronikTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","elektrikElektronikCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const elektrikElektronikCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));

