import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root=process.cwd(), sourcePath=process.argv[2]||"C:/Users/asus/OneDrive/Desktop/e-enstitü/bologna-lisansustu-2026-08-17-ders-verileri.json";
const department="Siyaset Bilimi ve Kamu Yönetimi ABD", programName="Siyaset Bilimi ve Kamu Yönetimi", level="Tezsiz Yüksek Lisans";
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();
const fold=(v="")=>clean(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const natural=(v="")=>{const t=clean(v);if(!t||t!==t.toLocaleUpperCase("tr-TR"))return t;const l=t.toLocaleLowerCase("tr-TR");return l[0].toLocaleUpperCase("tr-TR")+l.slice(1)};
const instructor=(v="")=>clean(String(v).replace(/\bYrd\.?\s*Doç\.?\s*Dr\.?\b/giu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+|\b\S+@\S+\b/giu," "))||"Atama Bekliyor";
const source=JSON.parse(readFileSync(sourcePath,"utf8")).data;
const program=source.programs.find(x=>fold(x.name).includes("siyaset bilimi ve kamu yonetimi tezsiz yuksek lisans"));
if(!program)throw new Error("Siyaset Bilimi ve Kamu Yönetimi tezsiz programı kaynakta bulunamadı.");
const coursesById=new Map(source.courses.map(x=>[x.id,x]));
const sourceByCode=new Map(source.programCourses.filter(x=>x.program_id===program.id).map(a=>{const c=coursesById.get(a.course_id);return[c.code,{course:c,assignment:a}]}));
const officialPath=path.join(root,"data/courses/2026-2027.json"), allOfficial=JSON.parse(readFileSync(officialPath,"utf8"));
const official=allOfficial.filter(x=>x.department===department&&x.programName===programName&&x.level===level);
if(![50,51].includes(official.length))throw new Error(`50 tekilleştirilmiş veya 51 ham satır bekleniyordu; bulunan ${official.length}.`);
const profile=JSON.parse(readFileSync(path.join(root,"seed/program-profiles.json"),"utf8")).find(x=>x.programName===programName&&x.level===level);
const pcs=profile?.outcomes||[];if(pcs.length!==11)throw new Error(`11 mevcut PÇ bekleniyordu; bulunan ${pcs.length}.`);
const cells=r=>(r||[]).map(x=>clean(typeof x==="object"?(x?.text??x?.value??""):x));
const tables=c=>c?.package?.tables||[];
const table=(c,keys)=>tables(c).find(t=>{const h=fold(cells(t.rows?.[0]).join(" "));return keys.every(k=>h.includes(k))});
const detail=(c,label)=>{for(const t of tables(c))for(const r of t.rows||[]){const a=cells(r);if(fold(a[0]).includes(label)&&a.slice(1).join(" "))return clean(a.slice(1).join(" "))}return""};
const resourcesFor=c=>{const t=tables(c).find(x=>fold(x.title)==="ders kaynaklari");return(t?.rows||[]).map(r=>cells(r).filter(Boolean).join(": ")).filter(Boolean).join("; ")};
const checklist=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=hasSource=>checklist.map((item,i)=>({item,status:!hasSource&&[1,19,20].includes(i)?"Doğrulanmalı":[3,5,6,7,8,9,10,11,12,13,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));

const domains={
  management:{label:"kamu yönetimi ve yönetişim",core:[0,1,2,4,9],secondary:[3,5,6,8,10],topics:["kamu yönetiminin kapsamı ve temel kavramları","klasik ve çağdaş yönetim yaklaşımları","kamu örgütlerinin yapısı","bürokrasi ve yönetsel davranış","kamu personel sistemi","stratejik yönetim ve planlama","performans, kalite ve hesap verebilirlik","yönetişim aktörleri ve katılım","idari reform ve kurumsal değişim","kamu hizmetlerinde dijital dönüşüm","karar süreçleri ve uygulama sorunları","karşılaştırmalı yönetim örnekleri","etik ve kamu yararı","güncel yönetsel sorunların analizi","yönetim yaklaşımlarının bütüncül değerlendirilmesi"],sdgs:[4,16,17]},
  politics:{label:"siyaset kuramı ve siyasal sistemler",core:[0,1,4,6,9],secondary:[2,5,7,8,10],topics:["siyasetin kapsamı ve temel kavramları","iktidar, otorite ve meşruiyet","devlet kuramları","demokrasi yaklaşımları","siyasal ideolojiler","partiler ve seçim sistemleri","siyasal kültür ve toplumsallaşma","milliyetçilik ve kimlik siyaseti","modernleşme ve siyasal değişim","karşılaştırmalı siyasal sistemler","siyasal aktörler ve karar süreçleri","Türkiye'de siyasal düşüncenin gelişimi","haklar, özgürlükler ve etik","güncel siyasal tartışmaların analizi","siyasal kuramların bütüncül değerlendirilmesi"],sdgs:[4,10,16]},
  communication:{label:"siyasal iletişim ve medya",core:[1,6,7,9,10],secondary:[0,2,4,5,8],topics:["iletişim ve siyaset ilişkisinin kavramsal temelleri","kamusal alan ve kamuoyu","medya sistemleri ve siyasal aktörler","retorik ve ikna kuramları","propaganda modelleri","söylem çözümleme yaklaşımları","kurumsal iletişim ve itibar","dijital medya ve siyasal katılım","nefret söylemi ve ayrımcılık","kriz iletişimi","iletişim kampanyalarının çözümlemesi","medya metinlerinin karşılaştırılması","ifade özgürlüğü ve iletişim etiği","güncel iletişim örneklerinin değerlendirilmesi","siyasal iletişim süreçlerinin bütüncül analizi"],sdgs:[4,10,16]},
  law:{label:"kamu hukuku, idari yargı ve haklar",core:[0,2,4,8,9],secondary:[1,5,6,10],topics:["hukuk devleti ve kamu hukuku ilkeleri","idarenin kuruluşu ve görevleri","idari işlem ve eylemler","idarenin sorumluluğu","temel hak ve özgürlükler","idari yargının yapısı","dava türleri ve başvuru yolları","adil yargılanma hakkı","kanun yolları ve yargısal denetim","vergilemenin anayasal ilkeleri","vergi sistemi ve güncel gelişmeler","yargı kararlarının çözümlenmesi","kamu yararı ve ölçülülük","güncel hukuki sorunların değerlendirilmesi","hukuki güvencelerin bütüncül analizi"],sdgs:[10,16,17]},
  local:{label:"yerel yönetimler, kent ve kamu politikası",core:[0,2,4,6,9],secondary:[1,5,7,8,10],topics:["yerel yönetimlerin temel kavramları","yerel yönetim sistemlerinin gelişimi","merkez-yerel ilişkileri","yerel mali yapı ve kaynaklar","kentleşme dinamikleri","çevre sorunları ve politikaları","yerelleşme ve çok düzeyli yönetişim","sivil toplum ve katılım","kamu politikası süreci","politika aktörleri ve araçları","karşılaştırmalı yerel yönetim örnekleri","politika uygulama ve değerlendirme","sürdürülebilirlik ve kamu yararı","güncel yerel sorunların analizi","yerel politika seçeneklerinin bütüncül değerlendirilmesi"],sdgs:[10,11,16]},
  economy:{label:"siyasal ekonomi ve kamu maliyesi",core:[0,2,4,9],secondary:[1,5,6,8,10],topics:["siyasal ekonominin temel kavramları","devlet-piyasa ilişkileri","kapitalizmin kurumsal yapısı","kamu ekonomisi ve maliye politikası","bölüşüm ve eşitsizlik","vergileme ve kamu gelirleri","yerel yönetim maliyesi","küresel siyasal ekonomi","krizler ve kurumsal dönüşüm","düzenleyici politikalar","ekonomik göstergelerin yorumlanması","ülke örneklerinin karşılaştırılması","mali etik ve kamu yararı","güncel ekonomik sorunların analizi","politika seçeneklerinin toplumsal etkileri"],sdgs:[8,10,16]},
  research:{label:"sosyal bilim araştırma yöntemleri",core:[0,1,2,3,5],secondary:[4,6,7,8,10],topics:["bilimsel bilgi ve araştırma etiği","araştırma problemi ve soru geliştirme","kuramsal çerçeve oluşturma","literatür tarama ve kaynak değerlendirme","nitel araştırma tasarımları","nicel araştırma tasarımları","örnekleme ve veri toplama","ölçme, geçerlik ve güvenirlik","nitel veri çözümleme","nicel veri çözümleme","bulguların yorumlanması","bilimsel yazım ve kaynak gösterme","yayın etiği ve araştırma bütünlüğü","araştırma raporunun yapılandırılması","araştırma sonuçlarının bütüncül değerlendirilmesi"],sdgs:[4,16,17]},
};
const domainFor=name=>{const n=fold(name);if(/bilimsel arastirma|metod/.test(n))return domains.research;if(/iletisim|propaganda|retorik|medya|nefret|kamuoyu/.test(n))return domains.communication;if(/hukuk|vergi|yargi|hak|idarenin mali/.test(n))return domains.law;if(/yerel|kent|cevre|sivil toplum|mahalli|kamu politikasi/.test(n))return domains.local;if(/ekonomi|maliye|kapital/.test(n))return domains.economy;if(/yonetim|reform|personel|strateji|kalite|kriz/.test(n))return domains.management;return domains.politics};
const outcomes=(name,d)=>[`${name} kapsamındaki ileri kavram ve yaklaşımları analiz eder.`,`${natural(d.topics[3])} ile ilişkili kurum ve uygulamaları karşılaştırır.`,`${natural(d.topics[7])} bağlamındaki veri ve kanıtları yorumlar.`,`${natural(d.topics[10])} için uygun analiz yaklaşımını uygular.`,`${name} alanındaki sorunlara etik ve kamu yararı odaklı öneriler geliştirir.`];
const matrix=d=>Array.from({length:5},(_,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,c)=>d.core.includes(c)?[4,5,4,5,4][r]:d.secondary.includes(c)?[2,3,3,2,3][r]:[1,2,1,2,1][r])}));
const forbidden=/(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|arasınav|vize|yarıyıl\s+sonu\s+sınavı|final)/iu;
const weeks=(c,d)=>{const t=table(c,["hafta","konu"]);const raw=(t?.rows||[]).slice(1).map(cells).map(x=>natural(x[1])).filter(x=>x&&!forbidden.test(x));const seen=new Set();return[...raw,...d.topics.map(natural)].filter(x=>{const key=fold(x);if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,15)};
const assessments=c=>{const t=table(c,["yariyil","katki"])||tables(c).find(x=>fold(x.title)==="degerlendirme olcutleri");const rows=(t?.rows||[]).slice(1).map(cells).filter(x=>x[0]&&!fold(x[0]).startsWith("toplam")).map(x=>({name:natural(x[0]),count:Number(x[1])||1,weight:Number(String(x.at(-1)).replace(/[^0-9.,]/g,"").replace(",","."))||0})).filter(x=>x.weight>0);return rows.length?rows:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,ass)=>{const target=ects*30,rows=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of ass){const n=fold(a.name);if(n.includes("odev"))rows.push({name:"Ödev Hazırlığı",count:a.count,hours:8,total:a.count*8});else if(n.includes("ara sinav"))rows.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))rows.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}const left=target-rows.reduce((s,x)=>s+x.total,0),h=Math.max(0,Math.floor((left/15)*2)/2);rows.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:h,total:15*h});const delta=target-rows.reduce((s,x)=>s+x.total,0);if(delta)rows.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:delta,total:delta});return rows};

const academicRows=official.filter(x=>!["SKY701","SKY702","SKY7XX"].includes(x.code));
const academic=academicRows.map(row=>{const src=sourceByCode.get(row.code),c=src?.course,d=domainFor(row.name),name=natural(c?.name||row.name),ass=assessments(c),theory=Number(src?.assignment?.theory??row.theory),practice=Number(src?.assignment?.practice??row.practice),ects=Number(src?.assignment?.ects??row.ects)||6;return{...row,name,theory,practice,credit:Number(src?.assignment?.local_credit??row.credit),ects,instructor:instructor(row.instructor||detail(c,"dersi verenler")),language:c?.language||"Türkçe",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",prerequisites:"Yok",purpose:natural(detail(c,"dersin amaci"))||`Öğrencinin ${d.label} alanındaki ileri kuramsal bilgileri siyasal ve yönetsel sorunların çözümünde kullanmasını sağlamak.`,content:natural(detail(c,"dersin icerigi"))||`${name}; ${d.topics.slice(0,10).join(", ")} boyutlarıyla ele alınır.`,methods:natural(detail(c,"dersin yontem"))||"Kuramsal anlatım, bilimsel kaynak incelemesi, örnek olay çözümlemesi, karşılaştırmalı analiz ve yapılandırılmış akademik tartışma.",resources:resourcesFor(c)||"Ders kapsamına uygun güncel kitaplar, hakemli siyaset bilimi ve kamu yönetimi literatürü, mevzuat, resmi raporlar ve açık veri kaynakları.",sdgs:d.sdgs.map(String),outcomes:outcomes(name,d),weeklyTopics:weeks(c,d),assessments:ass,workloads:workloads(ects,theory,practice,ass),contributionMatrix:matrix(d),...(c?.source_url?{sourceUrl:c.source_url}:{}),qualityChecks:checks(Boolean(c?.source_url)),publicQualityChecklist:false,status:undefined,source:undefined}});
const project={code:"SKY7XX",aliases:["SKY701","SKY702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin siyaset bilimi ve kamu yönetimi alanındaki bilgi ve becerilerini mesleki bir problem üzerinde bütünleştirerek bilimsel, etik ve kamu yararı odaklı bir bitirme projesi yürütmesini sağlamak.",content:"Proje probleminin belirlenmesi, literatür ve veri incelemesi, yöntem ve çalışma planının geliştirilmesi, bulguların siyasal-yönetsel bağlamda yorumlanması ve sonuçların akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışman görüşmesi, bilimsel kaynak incelemesi, veri veya doküman çözümlemesi, akademik yazım ve yapılandırılmış geri bildirim.",resources:"Enstitü bitirme projesi ilkeleri; proje konusuna ilişkin mevzuat, resmi raporlar, açık veri kaynakları ve güncel hakemli çalışmalar.",sdgs:["4","16","17"],outcomes:["Siyaset bilimi ve kamu yönetimi alanında uygulanabilir bir proje problemi yapılandırır.","Proje problemine ilişkin bilimsel ve kurumsal kaynakları eleştirel değerlendirir.","Proje amacına uygun veri, yöntem ve çalışma planı geliştirir.","Proje bulgularını siyasal, yönetsel ve toplumsal etkileriyle yorumlar.","Bitirme projesini bilimsel yazım ve etik ilkelerine uygun biçimde raporlar."],weeklyTopics:["Proje alanının ve kapsamının belirlenmesi","Siyasal veya yönetsel problemin sınırlandırılması","Proje amacı ve sorularının geliştirilmesi","Literatür tarama stratejisinin oluşturulması","Bilimsel ve kurumsal kaynakların değerlendirilmesi","Yöntem ve veri kaynaklarının seçilmesi","Çalışma planı ve zaman çizelgesinin geliştirilmesi","Veri veya doküman toplama sürecinin yürütülmesi","Toplanan materyalin düzenlenmesi","Veri veya dokümanların çözümlenmesi","Bulguların siyasal ve yönetsel bağlamda yorumlanması","Etik, kamu yararı ve uygulanabilirlik etkilerinin değerlendirilmesi","Proje raporunun yapılandırılması","Bilimsel yazım ve kaynak gösterme denetimi","Bitirme projesinin teslimi ve değerlendirilmesi"],assessments:[{name:"Başarılı / Başarısız",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışman Görüşmeleri",count:15,hours:2,total:30},{name:"Kaynak ve Veri İnceleme",count:15,hours:20,total:300},{name:"Çözümleme ve Proje Raporlama",count:15,hours:36,total:540},{name:"Nihai Düzenleme ve Teslim",count:1,hours:30,total:30}],contributionMatrix:matrix(domains.management),qualityChecks:checks(true),publicQualityChecklist:false};
for(const c of[...academic,project]){if(c.weeklyTopics.length!==15||new Set(c.weeklyTopics.map(fold)).size!==15)throw new Error(`${c.code}: 15 benzersiz hafta yok`);if(c.code!=="SKY7XX"&&c.weeklyTopics.some(x=>forbidden.test(x)))throw new Error(`${c.code}: yasak haftalık başlık`);if(c.outcomes.length!==5||c.contributionMatrix.some(r=>r.values.length!==11||r.values.some(v=>v<1||v>5)))throw new Error(`${c.code}: DÖÇ-PÇ geçersiz`);if(c.workloads.reduce((s,x)=>s+x.total,0)!==c.ects*30||!c.workloads.every(x=>Number.isInteger(x.hours*2)))throw new Error(`${c.code}: AKTS geçersiz`);if(c.qualityChecks.length!==21||c.publicQualityChecklist!==false)throw new Error(`${c.code}: kalite kontrolü geçersiz`)}
if(academic.length!==49)throw new Error(`49 akademik ders bekleniyordu; bulunan ${academic.length}`);
const packageValue=c=>{const{academicYear,programCode,type,term,status,source,...v}=c;return v};
const emit=(file,name,value)=>writeFileSync(path.join(root,"lib/data",file),`// Hedef programın gerçek OBS dersleri ve mevcut LEE_DBP PÇ yapısı temel alınmıştır; program profili değiştirilmemiştir.\nimport type { CoursePackage } from "./coursePackages";\n\nexport const ${name}: CoursePackage[] = ${JSON.stringify(value.map(packageValue),null,2)};\n`);
emit("siyasetKamuYonetimiTezsizCoursePackages.ts","siyasetKamuYonetimiTezsizCoursePackages",academic);emit("siyasetKamuYonetimiTezsizCommonCoursePackages.ts","siyasetKamuYonetimiTezsizCommonCoursePackages",[project]);
const normalized=[...academicRows.map(row=>{const src=sourceByCode.get(row.code);return{...row,name:natural(src?.course?.name||row.name),theory:Number(src?.assignment?.theory??row.theory),practice:Number(src?.assignment?.practice??row.practice),credit:Number(src?.assignment?.local_credit??row.credit),ects:Number(src?.assignment?.ects??row.ects),instructor:row.instructor?instructor(row.instructor):undefined}}),{academicYear:"2026-2027",programCode:"",department,programName,level,code:"SKY7XX",name:"Bitirme Projesi",type:"Zorunlu",credit:0,ects:30,theory:0,practice:0,term:"Güz",instructor:"Öğrencinin Danışmanı",status:"İncelemede",source:"official_excel"}];
const rest=allOfficial.filter(x=>!(x.department===department&&x.programName===programName&&x.level===level)),idx=rest.findIndex(x=>x.department===department&&x.programName===programName&&x.level==="Tezli Yüksek Lisans");rest.splice(idx<0?rest.length:idx,0,...normalized);writeFileSync(officialPath,`${JSON.stringify(rest,null,2)}\n`);
console.log(JSON.stringify({sourceAssignments:sourceByCode.size,academic:academic.length,common:1,official:normalized.length,programOutcomes:pcs.length}));
