import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root=process.cwd(), department="Yönetim Organizasyon", programName="Yönetim Organizasyon", level="Tezsiz Yüksek Lisans";
const sourcePath=process.argv[2]||"C:/Users/asus/OneDrive/Desktop/e-enstitü/bologna-lisansustu-2026-08-17-ders-verileri.json";
const officialPath=path.join(root,"data/courses/2026-2027.json"), allOfficial=JSON.parse(readFileSync(officialPath,"utf8"));
const official=allOfficial.filter(x=>x.department===department&&x.programName===programName&&x.level===level);
const fold=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i").replace(/\s+/g," ").trim();
const clean=s=>String(s||"").replace(/\s+/g," ").trim();
const sentence=s=>{const t=clean(s);if(!t||t!==t.toLocaleUpperCase("tr-TR"))return t;const l=t.toLocaleLowerCase("tr-TR");return l[0].toLocaleUpperCase("tr-TR")+l.slice(1);};
const cleanInstructor=s=>clean((s||"Atama Bekliyor").replace(/^Yrd\.?\s*Doç\.?\s*Dr\.?/iu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+|\b\S+@\S+\b/giu," "));
const db=new DatabaseSync(path.join(root,"local-volume/data/dbp.sqlite"),{readOnly:true});
const profileRow=db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name=? AND level=?").get(programName,level);
const programOutcomes=JSON.parse(profileRow?.outcomes_json||"[]");
if(programOutcomes.length!==11)throw new Error(`11 mevcut PÇ bekleniyordu; bulunan ${programOutcomes.length}`);

const source=JSON.parse(readFileSync(sourcePath,"utf8")).data;
const sourceProgram=source.programs.find(x=>fold(x.name)==="yonetim ve organizasyon tezsiz yuksek lisans (i.o.)");
if(!sourceProgram)throw new Error("Yönetim ve Organizasyon tezsiz kaynak programı bulunamadı.");
const sourceCourses=new Map(source.courses.map(x=>[x.id,x]));
const sourceByCode=new Map(source.programCourses.filter(x=>x.program_id===sourceProgram.id).map(a=>{const c=sourceCourses.get(a.course_id);return[c.code,{course:c,assignment:a}];}));
const cells=row=>(row||[]).map(x=>clean(typeof x==="object"?(x?.text??x?.value??""):x));
const tables=c=>c?.package?.tables||[];
const findTable=(c,keys)=>tables(c).find(t=>{const h=fold(cells(t.rows?.[0]).join(" "));return keys.every(k=>h.includes(k));});
const detail=(c,label)=>{for(const t of tables(c))for(const r of t.rows||[]){const a=cells(r);if(fold(a[0]).includes(label)&&a.slice(1).join(" "))return clean(a.slice(1).join(" "));}return"";};
const sourceResources=c=>{const t=tables(c).find(x=>fold(x.title)==="ders kaynaklari");return(t?.rows||[]).map(r=>cells(r).filter(Boolean).join(": ")).filter(Boolean).join("; ");};

const domains={
 research:{label:"bilimsel araştırma ve yayın etiği",primary:[1,6,7,9,10],secondary:[0,2,3,5,8],sdgs:[4,16,17],topics:["Yönetim ve organizasyon alanında bilimsel bilginin niteliği","Araştırma problemi ve sorularının yapılandırılması","Alan yazını tarama ve kaynak değerlendirme stratejileri","Kuramsal çerçeve ve araştırma modeli","Nitel araştırma tasarımları","Nicel araştırma tasarımları","Karma yöntem yaklaşımları","Örnekleme ve veri kaynakları","Veri toplama araçlarının değerlendirilmesi","Yönetim araştırmalarında veri çözümleme","Geçerlik, güvenirlik ve araştırma kalitesi","Bilimsel yazım ve kaynak gösterme","Araştırma ve yayın etiği","Bulguların raporlanması","Araştırma tasarımının bütüncül değerlendirilmesi"]},
 organization:{label:"yönetim ve örgüt tasarımı",primary:[0,1,2,5,6],secondary:[3,4,8,9,10],sdgs:[4,8,9],topics:["Yönetim ve organizasyonun temel kavramları","Yönetim düşüncesinin tarihsel gelişimi","Klasik yönetim yaklaşımları","Davranışsal yönetim yaklaşımları","Sistem ve durumsallık yaklaşımları","Örgüt yapısının temel unsurları","İş bölümü, yetki ve koordinasyon","Örgütsel çevre ve paydaşlar","Örgüt tasarımı seçenekleri","Yönetim işlevlerinin bütünleştirilmesi","Çağdaş yönetim yaklaşımları","Örgütsel etkinlik ve performans","Etik ve sosyal sorumluluk","Yönetim yaklaşımlarının karşılaştırılması","Örgütsel sorunların bütüncül değerlendirilmesi"]},
 behavior:{label:"örgütsel davranış ve insan ilişkileri",primary:[1,4,5,9],secondary:[0,2,6,8,10],sdgs:[3,4,8],topics:["Örgütsel davranışın kapsamı","Bireysel farklılıklar ve kişilik","Algı, tutum ve iş değerleri","Motivasyon kuramları","İş tatmini ve örgütsel bağlılık","Grup dinamikleri ve takım süreçleri","Örgütsel iletişim","Liderlik ve etkileme süreçleri","Güç, politika ve örgütsel adalet","Çatışma ve müzakere","Örgüt kültürü ve iklimi","Stres ve iyi oluş","Etik davranış ve kapsayıcılık","Güncel örgütsel davranış araştırmaları","İnsan ve örgüt davranışının bütüncül analizi"]},
 leadership:{label:"liderlik ve yönetsel etkileme",primary:[1,4,5,10],secondary:[0,2,3,6,9],sdgs:[4,5,8],topics:["Liderlik kavramı ve yöneticilik ilişkisi","Liderlik araştırmalarının tarihsel gelişimi","Özellik ve davranış yaklaşımları","Durumsal liderlik yaklaşımları","Dönüşümcü ve etkileşimci liderlik","Etik ve hizmetkâr liderlik","Lider-üye etkileşimi","Güç, otorite ve etkileme","Takım liderliği","Kültürler arası liderlik","Değişim sürecinde liderlik","Liderlik gelişimi ve yetkinlikler","Liderlikte etik ikilemler","Güncel liderlik araştırmalarının karşılaştırılması","Liderlik uygulamalarının bütüncül değerlendirilmesi"]},
 strategy:{label:"stratejik yönetim ve işletme politikaları",primary:[1,3,5,6,8],secondary:[0,2,9,10],sdgs:[4,8,9],topics:["Stratejik yönetimin kapsamı","Misyon, vizyon ve stratejik amaçlar","Dış çevre ve sektör analizi","Kaynaklar ve örgütsel yetenekler","Rekabet üstünlüğü yaklaşımları","Kurumsal ve iş birimi stratejileri","Stratejik seçeneklerin geliştirilmesi","Stratejik kararların değerlendirilmesi","Stratejinin uygulanması","Örgüt yapısı ve stratejik uyum","Performans ölçümü ve stratejik kontrol","Belirsizlik ve senaryo analizi","Etik, sürdürülebilirlik ve paydaş sorumluluğu","Güncel strateji örneklerinin karşılaştırılması","Stratejik seçeneklerin bütüncül değerlendirilmesi"]},
 decision:{label:"karar verme ve problem çözme",primary:[1,3,5,6],secondary:[0,2,4,8,9,10],sdgs:[4,8,9],topics:["Yönetsel karar problemlerinin niteliği","Problem tanımlama ve kök neden analizi","Amaç, ölçüt ve kısıtların belirlenmesi","Karar ortamları ve belirsizlik","Karar verme modelleri","Nitel problem çözme teknikleri","Nicel karar teknikleri","Alternatiflerin geliştirilmesi","Alternatiflerin karşılaştırılması","Duyarlılık ve senaryo analizi","Grup kararları ve katılım","Karar yanlılıkları ve davranışsal etkiler","Etik ve sosyal etkilerin değerlendirilmesi","Yönetim örneklerinin çözümlenmesi","Karar sonuçlarının bütüncül yorumlanması"]},
 innovation:{label:"girişimcilik, teknoloji ve yenilik yönetimi",primary:[0,1,3,5,7,8],secondary:[2,6,9,10],sdgs:[4,8,9],topics:["Girişimcilik ve yenilik kavramları","Fırsatların belirlenmesi","Yaratıcılık süreçleri","Yenilik türleri ve modelleri","Teknoloji öngörüsü","İş modeli geliştirme","Kaynak ve yeteneklerin değerlendirilmesi","Yenilik portföyü ve proje seçimi","Örgütsel yaratıcılık iklimi","Teknoloji edinme ve ticarileştirme","Girişimcilik ekosistemleri","Yenilik performansının ölçülmesi","Etik, sürdürülebilirlik ve toplumsal etki","Güncel girişimcilik uygulamalarının karşılaştırılması","Yenilik kararlarının bütüncül değerlendirilmesi"]},
 hr:{label:"insan kaynakları, performans ve kariyer yönetimi",primary:[0,1,4,5,6],secondary:[2,3,8,9,10],sdgs:[4,5,8],topics:["Stratejik insan kaynakları yönetimi","İş analizi ve yetkinlikler","İnsan kaynağı planlaması","Seçme ve yerleştirme","Eğitim ve geliştirme","Performans yönetimi","Kariyer yönetimi","Ücretlendirme ve ödüllendirme","Çalışan katılımı ve bağlılık","Yetenek yönetimi","Çalışma ilişkileri","İnsan kaynakları analitiği","Eşitlik, etik ve sosyal sorumluluk","Güncel insan kaynakları uygulamaları","İnsan kaynakları sisteminin bütüncül değerlendirilmesi"]},
 change:{label:"örgütsel değişim, gelişim ve öğrenme",primary:[0,1,4,5,6,8],secondary:[2,3,9,10],sdgs:[4,8,9],topics:["Örgütsel değişimin kavramsal temelleri","Değişim gereksiniminin belirlenmesi","Örgütsel tanı yaklaşımları","Değişim modelleri","Değişime direnç","Katılım ve iletişim","Örgüt geliştirme müdahaleleri","Takım ve süreç geliştirme","Örgütsel öğrenme","Bilgi yönetimi ve kurumsal hafıza","Değişim liderliği","Değişim sonuçlarının değerlendirilmesi","Etik ve çalışan refahı","Güncel değişim örneklerinin karşılaştırılması","Örgütsel gelişim sürecinin bütüncül değerlendirilmesi"]},
 communication:{label:"örgütsel iletişim ve çatışma yönetimi",primary:[1,4,5,10],secondary:[0,2,6,8,9],sdgs:[4,8,16],topics:["İletişim süreci ve örgütsel bağlam","İletişim kanalları ve ağları","Algı ve anlamlandırma","Yönetsel iletişim","Takım ve grup iletişimi","Kültürler arası iletişim","Çatışmanın kaynakları","Çatışma türleri ve düzeyleri","Çatışma yönetimi stilleri","Müzakere süreçleri","Güç ve politik davranış","Kriz iletişimi","Etik iletişim ve kapsayıcılık","Örgütsel vakaların karşılaştırılması","İletişim ve çatışmanın bütüncül değerlendirilmesi"]},
 culture:{label:"kültür, küreselleşme ve uluslararası işletmecilik",primary:[0,1,2,4,8],secondary:[3,5,9,10],sdgs:[4,8,17],topics:["Kültür ve yönetim ilişkisi","Ulusal ve örgütsel kültür","Türkiye'de yönetim düşüncesinin gelişimi","Kültürel boyut yaklaşımları","Küreselleşme ve işletmeler","Uluslararası iş çevresinin analizi","Çok uluslu işletme stratejileri","Kültürler arası yönetim","Küresel insan kaynakları uygulamaları","Bilgi ve öğrenmenin sınır ötesi yönetimi","Küresel değer zincirleri","Uluslararası riskler","Etik ve sosyal sorumluluk","Ülke ve işletme örneklerinin karşılaştırılması","Kültürel ve küresel etkilerin bütüncül değerlendirilmesi"]},
 quality:{label:"kalite ve sürdürülebilir yönetim",primary:[0,1,3,5,6,9],secondary:[2,4,8,10],sdgs:[8,9,12],topics:["Kalite ve sürdürülebilir yönetimin temelleri","Müşteri ve paydaş odaklılık","Süreç yaklaşımı","Sürekli iyileştirme","Kalite araç ve teknikleri","Toplam kalite yönetimi ilkeleri","Performans göstergeleri","Standartlar ve kurumsal sistemler","Yeşil yönetim uygulamaları","Kaynak verimliliği","Çevresel ve sosyal performans","Sürdürülebilirlik raporlaması","Etik ve paydaş sorumluluğu","Uygulama örneklerinin karşılaştırılması","Yönetim sisteminin bütüncül değerlendirilmesi"]},
 family:{label:"aile işletmelerinde yönetim",primary:[0,1,3,4,5],secondary:[2,8,9,10],sdgs:[4,8,16],topics:["Aile işletmelerinin özellikleri","Aile, mülkiyet ve işletme sistemleri","Aile işletmelerinde yönetişim","Rol ve beklenti çatışmaları","Profesyonelleşme","Stratejik yönetim","İnsan kaynakları uygulamaları","Kurumsallaşma","Nesiller arası geçiş","Halefiyet planlaması","Aile konseyi ve iletişim","Finansal ve yönetsel kontrol","Etik ve sosyal sorumluluk","Aile işletmesi örneklerinin karşılaştırılması","Sürdürülebilirliğin bütüncül değerlendirilmesi"]}
};
function domainFor(name){const n=fold(name);if(/bilimsel arastirma|yayin etigi/.test(n))return domains.research;if(/stratejik/.test(n))return domains.strategy;if(/karar verme|problem cozme/.test(n))return domains.decision;if(/girisimcilik|yenilik|yaraticilik|teknoloji/.test(n))return domains.innovation;if(/insan kaynaklari|performans|kariyer|motivasyon/.test(n))return domains.hr;if(/degisim|orgut gelistirme|ogrenen orgut|bilgi yonetimi/.test(n))return domains.change;if(/iletisim|catisma|guc|politika/.test(n))return domains.communication;if(/liderlik|otorite/.test(n))return domains.leadership;if(/kultur|kuresellesme|uluslararasi/.test(n))return domains.culture;if(/kalite|yesil yonetim/.test(n))return domains.quality;if(/aile isletme/.test(n))return domains.family;if(/davranis/.test(n))return domains.behavior;return domains.organization;}
const checklist=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=hasSource=>checklist.map((item,i)=>({item,status:!hasSource&&[1,19,20].includes(i)?"Doğrulanmalı":[3,5,6,7,8,9,10,11,12,13,14,15,16,18].includes(i)?"Revize Edildi":"Uygun"}));
const outcomesFor=d=>[`${sentence(d.topics[0])} ile ilgili ileri kavramları analiz eder.`,`${sentence(d.topics[2])} bağlamındaki veri ve kanıtları eleştirel değerlendirir.`,`${sentence(d.topics[7])} ile ilişkili yönetsel veya teknik örnekleri karşılaştırır.`,`${sentence(d.topics[11])} için uygun çözümleme yaklaşımını uygular.`,`${sentence(d.topics[14])} temelinde gerekçeli çözüm önerisi geliştirir.`];
const matrixFor=d=>Array.from({length:5},(_,r)=>({outcome:`DÖÇ${r+1}`,values:programOutcomes.map((_,c)=>d.primary.includes(c)?[4,5,4,4,5][r]:d.secondary.includes(c)?[2,3,3,2,3][r]:[1,2,1,2,1][r])}));
const forbidden=/^(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|arasınav|vize|yarıyıl\s+sonu\s+sınavı|final)$/iu;
const normalizeTopic=(value,courseName)=>{let t=sentence(value),n=clean(courseName);if(n&&fold(t).startsWith(`${fold(n)}:`))t=sentence(clean(t.slice(n.length+1)));return t;};
const weeklyTopics=(c,d)=>{const t=findTable(c,["hafta","konu"]),raw=(t?.rows||[]).slice(1).map(cells).map(r=>normalizeTopic(r[1],c?.name)).filter(x=>x&&!forbidden.test(x));const seen=new Set();return[...raw,...d.topics].filter(x=>{const k=fold(x);if(!k||seen.has(k))return false;seen.add(k);return true;}).slice(0,15);};
const assessmentsFor=c=>{const t=findTable(c,["yariyil","katki"])||tables(c).find(x=>fold(x.title)==="degerlendirme olcutleri");const rows=(t?.rows||[]).slice(1).map(cells).filter(r=>r[0]&&!fold(r[0]).startsWith("toplam")).map(r=>({name:sentence(r[0]),count:Number(r[1])||1,weight:Number(String(r.at(-1)).replace(/[^0-9.,]/g,"").replace(",","."))||0})).filter(x=>x.weight>0);return rows.length?rows:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}];};
const workloadsFor=(ects,theory,practice,ass)=>{const target=ects*30,rows=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of ass){const n=fold(a.name);if(n.includes("odev"))rows.push({name:"Ödev Hazırlığı",count:a.count,hours:8,total:a.count*8});else if(n.includes("proje"))rows.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))rows.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))rows.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25});}let left=target-rows.reduce((s,x)=>s+x.total,0),h=Math.max(0,Math.floor(left/15*2)/2);rows.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:h,total:15*h});left=target-rows.reduce((s,x)=>s+x.total,0);if(left)rows.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:left,total:left});return rows;};
const resourcesFor=(c,d)=>sourceResources(c)||`Koçel, İşletme Yöneticiliği; Robbins ve Judge, Örgütsel Davranış; ${d.label} alanındaki güncel uluslararası standartlar ve hakemli araştırmalar.`;

const projectCodes=new Set(["YON701","YON702","YON7XX"]),researchAliases=new Set(["YON703","BES704"]);
const academicRows=official.filter(x=>!projectCodes.has(x.code)&&x.code!=="BES704"&&!/DANIŞMANLIK|UZMANLIK ALAN/iu.test(x.name));
const academic=academicRows.map(row=>{const src=sourceByCode.get(row.code),c=src?.course,d=domainFor(row.name),theory=Number(src?.assignment?.theory??row.theory),practice=Number(src?.assignment?.practice??row.practice),ects=Number(src?.assignment?.ects??row.ects)||6,ass=assessmentsFor(c),name=row.code==="YON703"?"Bilimsel araştırma yöntemleri ve yayın etiği":sentence(c?.name||row.name);return{code:row.code,...(row.code==="YON703"?{aliases:["YON703","BES704"]}:{}),name,department,programName,language:c?.language||"Türkçe",level,teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",instructor:cleanInstructor(row.instructor||detail(c,"dersi verenler")),theory,practice,credit:Number(src?.assignment?.local_credit??row.credit),ects,prerequisites:"Yok",purpose:sentence(detail(c,"dersin amaci"))||`Bu dersin, öğrencilerin ${d.label} alanındaki ileri bilgileri yönetim ve organizasyon bağlamında çözümlemelerine katkı sağlaması amaçlanmaktadır.`,content:sentence(detail(c,"dersin icerigi"))||`${sentence(d.topics.slice(0,10).join("; "))} başlıkları Yönetim ve Organizasyon bağlamında ele alınmaktadır.`,methods:sentence(detail(c,"dersin yontem"))||"Kuramsal anlatım, yönlendirilmiş tartışma, örnek olay incelemesi, veri ve süreç çözümlemesi ile bireysel çalışma.",resources:resourcesFor(c,d),sdgs:d.sdgs.map(String),outcomes:outcomesFor(d),weeklyTopics:weeklyTopics(c,d),assessments:ass,workloads:workloadsFor(ects,theory,practice,ass),contributionMatrix:matrixFor(d),...(c?.source_url?{sourceUrl:c.source_url}:{}),qualityChecks:checks(Boolean(c?.source_url)),publicQualityChecklist:false};});
const projectSource=sourceByCode.get("YON702")?.course,projectDomain=domains.organization;
const project={code:"YON7XX",aliases:["YON701","YON702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin ileri yönetim ve organizasyon bilgisini gerçek bir örgütsel problem üzerinde bütünleştirerek bilimsel ve etik ölçütlere uygun bir bitirme projesi yürütmesini sağlamak.",content:"Örgütsel problemin belirlenmesi, alan yazını ve kurumsal verilerin incelenmesi, yöntem ile çalışma planının geliştirilmesi, yönetsel bulguların çözümlenmesi, sonuçların örgütsel bağlamda yorumlanması ve projenin akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışman görüşmesi, literatür ve örgütsel veri incelemesi, vaka veya süreç çözümlemesi, akademik yazım ve yapılandırılmış geri bildirim.",resources:resourcesFor(projectSource,projectDomain),sdgs:["4","8","9"],outcomes:["Örgütsel bir yönetim problemini uygulanabilir proje sorusuna dönüştürür.","Proje problemine ilişkin akademik ve mesleki kaynakları eleştirel değerlendirir.","Projenin amacına uygun veri, yöntem ve çalışma planı geliştirir.","Yönetsel bulguları örgütsel bağlamda yorumlar.","Bitirme projesini bilimsel yazım ve etik ilkelerine uygun raporlar."],weeklyTopics:["Proje alanının ve kapsamının belirlenmesi","Örgütsel yönetim probleminin sınırlandırılması","Amaç ve proje sorularının geliştirilmesi","Literatür tarama stratejisinin oluşturulması","Kuramsal ve mesleki kaynakların değerlendirilmesi","Paydaş, süreç ve bilgi gereksinimlerinin belirlenmesi","Yöntem ile çalışma planının geliştirilmesi","Veri kaynaklarının ve çözümleme birimlerinin yapılandırılması","Etik, gizlilik ve veri güvenliği gereksinimlerinin değerlendirilmesi","Yönetsel verilerin düzenlenmesi","Bulguların çözümlenmesi ve yorumlanması","Bulguların alan yazını ve örgütsel gereksinimlerle karşılaştırılması","Çözüm önerileri ve mesleki çıkarımların geliştirilmesi","Akademik metin, atıf ve kaynakça düzeninin denetlenmesi","Bitirme projesinin teslimi ve değerlendirilmesi"],assessments:[{name:"Başarılı / Başarısız",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışman Görüşmeleri",count:15,hours:2,total:30},{name:"Literatür ve Veri İncelemesi",count:15,hours:20,total:300},{name:"Çözümleme ve Raporlama",count:15,hours:36,total:540},{name:"Nihai Düzenleme ve Teslim",count:1,hours:30,total:30}],contributionMatrix:matrixFor(projectDomain),...(projectSource?.source_url?{sourceUrl:projectSource.source_url}:{}),qualityChecks:checks(Boolean(projectSource?.source_url)),publicQualityChecklist:false};
if(academic.length!==35)throw new Error(`35 akademik ders bekleniyordu; bulunan ${academic.length}`);
for(const c of [...academic,project]){if(c.weeklyTopics.length!==15||new Set(c.weeklyTopics.map(fold)).size!==15)throw new Error(`${c.code}: 15 benzersiz hafta yok`);if(c.code!=="YON7XX"&&c.weeklyTopics.some(x=>forbidden.test(x)))throw new Error(`${c.code}: yasak başlık`);if(c.outcomes.length!==5||c.contributionMatrix.some(r=>r.values.length!==11||r.values.some(v=>v<1||v>5)))throw new Error(`${c.code}: DÖÇ-PÇ`);if(c.workloads.reduce((s,x)=>s+x.total,0)!==c.ects*30||!c.workloads.every(x=>Number.isInteger(x.hours*2)))throw new Error(`${c.code}: iş yükü`);if(c.assessments.some(x=>/Ödev/iu.test(x.name))&&!c.workloads.some(x=>/Ödev/iu.test(x.name)))throw new Error(`${c.code}: ödev iş yükünde değil`);if(c.qualityChecks.length!==21||c.publicQualityChecklist!==false)throw new Error(`${c.code}: kontrol`);}
const emit=(file,name,value)=>writeFileSync(path.join(root,"lib/data",file),`// Yönetim ve Organizasyon tezsiz resmî müfredatı, gerçek OBS paketleri ve mevcut 11 LEE_DBP PÇ'si temel alınmıştır; program profili değiştirilmemiştir.\nimport type { CoursePackage } from "./coursePackages";\n\nexport const ${name}: CoursePackage[] = ${JSON.stringify(value,null,2)};\n`);
emit("yonetimOrganizasyonTezsizCoursePackages.ts","yonetimOrganizasyonTezsizCoursePackages",academic);emit("yonetimOrganizasyonTezsizCommonCoursePackages.ts","yonetimOrganizasyonTezsizCommonCoursePackages",[project]);
const normalized=[...academicRows.map(row=>{const src=sourceByCode.get(row.code);return{...row,name:row.code==="YON703"?"Bilimsel araştırma yöntemleri ve yayın etiği":sentence(src?.course?.name||row.name),...(row.code==="YON703"?{term:"Güz ve Bahar"}:{}),theory:Number(src?.assignment?.theory??row.theory),practice:Number(src?.assignment?.practice??row.practice),credit:Number(src?.assignment?.local_credit??row.credit),ects:Number(src?.assignment?.ects??row.ects),instructor:row.instructor?cleanInstructor(row.instructor):undefined};}),{academicYear:"2026-2027",programCode:"",department,programName,level,code:"YON7XX",name:"Bitirme Projesi",type:"Zorunlu",credit:0,ects:30,theory:0,practice:0,term:"Güz ve Bahar",instructor:"Öğrencinin Danışmanı",status:"İncelemede",source:"official_excel"}];
const rest=allOfficial.filter(x=>!(x.department===department&&x.programName===programName&&x.level===level));const at=rest.findIndex(x=>x.department===department&&x.programName===programName&&x.level==="Tezli Yüksek Lisans");rest.splice(at<0?rest.length:at,0,...normalized);writeFileSync(officialPath,`${JSON.stringify(rest,null,2)}\n`);
console.log(JSON.stringify({sourceAssignments:sourceByCode.size,academic:academic.length,common:1,official:normalized.length,outcomes:programOutcomes.length,missing:academic.filter(x=>!x.sourceUrl).map(x=>x.code)}));
