from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COURSE_DATA = ROOT / "data" / "courses" / "2026-2027.json"
OFFICIAL_COURSES_TS = ROOT / "lib" / "data" / "officialCourses.ts"
LOCAL_PREVIEW_DATA = ROOT / "local-preview" / "program-data-local.js"


FULL_TO_SHORT_LEVEL = {
    "Tezsiz Yüksek Lisans": "Tezsiz YL",
    "Tezsiz YÃ¼ksek Lisans": "Tezsiz YL",
    "Tezli Yüksek Lisans": "Tezli YL",
    "Tezli YÃ¼ksek Lisans": "Tezli YL",
    "Doktora": "Doktora",
}


def read_courses() -> list[dict[str, object]]:
    return json.loads(COURSE_DATA.read_text(encoding="utf-8"))


def js_value(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_course(course: dict[str, object]) -> str:
    ordered_keys = [
        "academicYear",
        "programCode",
        "department",
        "programName",
        "level",
        "code",
        "name",
        "type",
        "credit",
        "ects",
        "theory",
        "practice",
        "term",
        "instructor",
        "status",
        "source",
    ]
    parts: list[str] = []
    for key in ordered_keys:
        if key in course and course[key] is not None and (key != "instructor" or course[key] != ""):
            parts.append(f"{key}: {js_value(course[key])}")
    return "  { " + ", ".join(parts) + " },"


def local_course(course: dict[str, object]) -> str:
    row = dict(course)
    row["level"] = FULL_TO_SHORT_LEVEL.get(str(row.get("level", "")), row.get("level", ""))
    ordered_keys = [
        "academicYear",
        "programCode",
        "department",
        "programName",
        "level",
        "code",
        "name",
        "type",
        "credit",
        "ects",
        "theory",
        "practice",
        "term",
        "status",
        "instructor",
        "source",
    ]
    row = {
        key: row[key]
        for key in ordered_keys
        if key in row and row[key] is not None and (key != "instructor" or row[key] != "")
    }
    return "  " + json.dumps(row, ensure_ascii=False, separators=(",", ": ")) + ","


def write_official_courses_ts(courses: list[dict[str, object]]) -> None:
    body = "\n".join(ts_course(course) for course in courses)
    content = f'''import type {{ LeeProgram, ProgramLevel }} from "./programs";

export type OfficialCourse = {{
  academicYear: "2026-2027";
  programCode: string;
  department: string;
  programName: string;
  level: ProgramLevel;
  code: string;
  name: string;
  type: "Zorunlu" | "Seçmeli";
  credit: number;
  ects: number;
  theory: number;
  practice: number;
  term: "Güz" | "Bahar";
  instructor?: string;
  status: "Taslak" | "İncelemede" | "Onaylandı" | "Atama Bekliyor";
  source: "official_excel";
}};

// AUTO-GENERATED FILE.
// Source of truth: data/courses/2026-2027.json
// Do not edit this file while importing Excel. Run: npm run dbp:generate-data
export const OFFICIAL_COURSES: OfficialCourse[] = [
{body}
];

const same = (left: string, right: string) =>
  left.trim().toLocaleLowerCase("tr-TR") === right.trim().toLocaleLowerCase("tr-TR");

export const officialCoursesForProgram = (program: LeeProgram) =>
  OFFICIAL_COURSES.filter((course) =>
    same(course.department, program.department) &&
    same(course.programName, program.programName),
  );

export const hasOfficialCoursesForProgram = (program: LeeProgram) =>
  officialCoursesForProgram(program).length > 0;
'''
    OFFICIAL_COURSES_TS.write_text(content, encoding="utf-8")


def write_local_preview_courses(courses: list[dict[str, object]]) -> None:
    text = LOCAL_PREVIEW_DATA.read_text(encoding="utf-8")
    start = text.index("window.LEE_DBP_OFFICIAL_COURSES=[")
    marker = "window.LEE_DBP_OFFICIAL_COURSES_FOR_ROW"
    marker_index = text.index(marker, start)
    end = text.rfind("];", start, marker_index) + 2
    if end < start + 2:
        raise ValueError("local-preview official course array end marker could not be found")
    body = "\n".join(local_course(course) for course in courses)
    replacement = (
        "window.LEE_DBP_OFFICIAL_COURSES=[\n"
        "// AUTO-GENERATED FROM data/courses/2026-2027.json. Do not edit by hand.\n"
        f"{body}\n"
        "];"
    )
    LOCAL_PREVIEW_DATA.write_text(text[:start] + replacement + text[end:], encoding="utf-8")


def main() -> None:
    courses = read_courses()
    write_official_courses_ts(courses)
    write_local_preview_courses(courses)
    print(f"Generated {len(courses)} courses into TypeScript and local preview data.")


if __name__ == "__main__":
    main()
