import { readFileSync } from "node:fs";

const sourcePath = process.argv[2] || process.env.BOLOGNA_DERS_JSON;
if (!sourcePath) throw new Error("Kullanım: node scripts/generate_fizik_doktora_course_packages.mjs <ders-verileri.json>");
let source = readFileSync(new URL("./generate_fizik_tezli_course_packages.mjs", import.meta.url), "utf8");
source = source
  .replace('fold(p.name)==="fizik tezli yuksek lisans"', 'fold(p.name)==="fizik doktora"')
  .replace(/const pcs=\[[\s\S]*?\];\nconst raw=/, `const pcs=[
"İleri fizik bilgilerini özgün araştırma problemlerinin çözümünde eleştirel biçimde sentezler.",
"Karmaşık fiziksel olgulara yönelik özgün araştırma soruları ve hipotezler geliştirir.",
"Fizik araştırmaları için yenilikçi kuramsal, deneysel veya hesaplamalı yöntemler geliştirir.",
"Karmaşık fizik verilerini ileri matematiksel, istatistiksel ve hesaplamalı yöntemlerle analiz eder.",
"Araştırma bulgularını güncel uluslararası fizik literatürü bağlamında eleştirel olarak değerlendirir.",
"Fizik alanında bağımsız ve özgün bilimsel araştırmaları tasarlar ve yürütür.",
"Özgün araştırma sonuçlarıyla fizik bilim alanına yeni ve doğrulanabilir bilgi kazandırır.",
"Karmaşık fizik problemlerinde farklı bilim ve mühendislik disiplinlerini bütünleştirir.",
"Araştırmalarda bilimsel etik, açık bilim ve araştırma bütünlüğü ilkelerini uygular.",
"Özgün araştırma sonuçlarını uluslararası yayınlarda ve akademik ortamlarda savunur.",
"Fizik araştırmalarının teknolojik, çevresel ve toplumsal etkilerine yönelik stratejiler geliştirir."
];
const raw=`)
  .replace('l.includes(\'level: "Tezli Yüksek Lisans"\')', 'l.includes(\'level: "Doktora"\')')
  .replace('const common=/^(DAN80[1-4]|FZK80[1-8]|FZK89[89])$/u;', 'const common=/^(DAN90[1-8]|FZK90[1-9]|FZK910|FZK91[2-8])$/u;')
  .replaceAll('level:"Tezli Yüksek Lisans"', 'level:"Doktora"')
  .replace('["quiz","kisa sinav","odev","proje","sunum","konu tekrari","genel tekrar","ara sinav","vize","final","yariyil sonu"]', '["quiz","kisa sinav","odev","proje","sunum","konu tekrari","genel tekrar","ara sinav","arasinav","vize","final","yariyil sonu"]')
  .replace('instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor"', 'instructor:clean((detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor").replace(/https?:\\/\\/\\S+|\\S+@\\S+/gu,""))')
  .replace(/const specs=\[[\s\S]*?\n\];\nconst commons=/, `const specs=[
{code:"DAN9XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin doktora araştırmasını bilimsel özgünlük, yöntem, etik, yayın ve zaman yönetimi bakımından yönlendirmek.",content:"Doktora araştırma planı, ileri fizik literatürü, özgün problem, yöntem geliştirme, veri yönetimi, araştırma bütünlüğü, yayın stratejisi ve ilerleme izlemesi.",stages:["Doktora çalışma planının oluşturulması","Fizik uzmanlık alanının sınırlandırılması","İleri literatür tarama stratejisinin değerlendirilmesi","Özgün araştırma probleminin netleştirilmesi","Etik ve güvenlik gerekliliklerinin incelenmesi","Hipotez ve araştırma tasarımının değerlendirilmesi","Veri üretim planının izlenmesi","Araştırma kayıtları ve kalite güvencesi","Bulguların eleştirel ön değerlendirmesi","İleri analiz yaklaşımının gözden geçirilmesi","Bilimsel yayın planının oluşturulması","Kaynak ve araştırma bütünlüğü denetimi","Araştırma sınırlılıklarının değerlendirilmesi","Doktora ilerlemesi ve özgün katkının izlenmesi","Sonraki dönem araştırma hedeflerinin kararlaştırılması"]},
{code:"FZK9XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin doktora tez alanındaki güncel fizik literatürünü eleştirel biçimde sentezlemesini ve özgün araştırmasının kuramsal, deneysel veya hesaplamalı temelini geliştirmesini sağlamak.",content:"Doktora tez alanına özgü fizik kuramları, araştırma boşluğu, ileri yöntemler, ölçüm ve veri analizi, bilimsel özgünlük, güvenlik ve araştırma etiği.",stages:["Doktora tez alanının bilimsel kapsamı","Güncel fizik literatürünün eleştirel sınıflandırılması","Kuramsal yaklaşımların sentezlenmesi","Uluslararası literatürde araştırma boşluğunun belirlenmesi","Özgün araştırma sorularının geliştirilmesi","Hipotezlerin bilimsel temellendirilmesi","İleri kuramsal yöntemlerin karşılaştırılması","Deneysel ve hesaplamalı tasarımın değerlendirilmesi","Ölçüm ve veri üretim yöntemlerinin geliştirilmesi","Belirsizlik, veri kalitesi ve tekrarlanabilirlik","İleri analiz seçeneklerinin karşılaştırılması","Fiziksel sonuçların kuramsal yorumlanması","Etik ve laboratuvar güvenliği riskleri","Özgün katkı ve sınırlılıkların tartışılması","Kuramsal ve yöntemsel çerçevenin bütünleştirilmesi"]},
{code:"FZK909",name:"SEMİNER",theory:3,practice:0,credit:0,ects:6,purpose:"Fizikte ileri bir bilimsel problemi eleştirel literatür senteziyle inceleme, akademik metne dönüştürme ve doktora düzeyinde savunma becerisi kazandırmak.",content:"İleri literatür tarama, kanıt değerlendirme, özgün fizik problemi, bilimsel metin, kuramsal ve deneysel bulguların sentezi, akademik tartışma ve bilimsel iletişim.",stages:["Seminer konusunun özgünlük ve kapsam bakımından belirlenmesi","İleri araştırma sorusunun geliştirilmesi","Sistematik literatür tarama stratejisinin kurulması","Kaynakların kanıt düzeyi bakımından değerlendirilmesi","Literatürün kavramsal sınıflandırılması","Kuramsal ve deneysel kanıtların karşılaştırılması","Seminer metninin bilimsel yapısının oluşturulması","Yöntem ve bulguların eleştirel sentezi","Denklem, tablo ve görsellerin düzenlenmesi","Doktora düzeyinde tartışmanın yapılandırılması","Özgün fizik çıkarımlarının geliştirilmesi","Atıf ve kaynakça bütünlüğünün denetlenmesi","Akademik anlatım tasarımının geliştirilmesi","Bilimsel savunmanın uygulanması","Geri bildirimle nihai metnin geliştirilmesi"]},
{code:"FZK917",name:"DOKTORA YETERLİK",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin fizikte ileri bilgi, bilimsel problem çözme, özgün araştırma tasarlama ve bağımsız araştırma yürütme yeterliliğini bütüncül olarak geliştirmek.",content:"İleri fizik kuramları, disiplinler arası sentez, özgün problem ve hipotez, kuramsal, deneysel ve hesaplamalı yöntemler, ileri veri analizi, etik, güvenlik ve bilimsel savunma.",stages:["Yeterlik kapsamındaki fizik alanlarının belirlenmesi","İleri kuramsal bilginin sistematik incelenmesi","Fizik alt alanları arasındaki ilişkilerin sentezi","Karmaşık problemlerin bilimsel çözümlemesi","Özgün araştırma sorusu geliştirme","Hipotezlerin eleştirel değerlendirilmesi","Kuramsal modellerin karşılaştırılması","Deney ve hesaplama yöntemlerinin seçimi","Ölçüm belirsizliği ve geçerlik ölçütleri","İleri matematiksel ve istatistiksel analiz","Bulguların fiziksel bağlamda yorumlanması","Bilimsel etik ve araştırma bütünlüğü","Güvenlik ve toplumsal etkilerin değerlendirilmesi","Bilimsel argümanın yazılı yapılandırılması","Bilimsel argümanın sözlü savunulması"]},
{code:"FZK91X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin fizik alanında özgün ve bağımsız bir doktora araştırmasını etik ilkelere uygun biçimde yürütmesi, yayımlaması ve savunmasını sağlamak.",content:"Özgün fizik problemi, ileri literatür sentezi, kuramsal model, deney veya hesaplama, veri üretimi, belirsizlik ve ileri analiz, bilimsel yayın, tez yazımı ve savunma.",stages:["Özgün araştırma probleminin kesinleştirilmesi","İleri literatür çerçevesinin güncellenmesi","Araştırma amaç ve hipotezlerinin yapılandırılması","Yenilikçi model veya deney planının kesinleştirilmesi","Etik ve güvenlik süreçlerinin tamamlanması","Veri üretim sürecinin planlanması","Araştırma kayıtları ve kalite kontrolü","Deney veya hesaplama sürecinin izlenmesi","Verilerin düzenlenmesi ve doğrulanması","İleri analizlerin yürütülmesi","Bulguların fiziksel açıdan yorumlanması","Özgün katkının literatürle karşılaştırılması","Bilimsel yayın ve tez bölümlerinin yazımı","Tez metninin bütünlük ve etik denetimi","Doktora savunması ve bilimsel katkının sunulması"]}
];
const commons=`)
  .replace('s.code==="FZK806"', 's.code==="FZK909"')
  .replaceAll('fizikTezliCoursePackages.ts', 'fizikDoktoraCoursePackages.ts')
  .replaceAll('fizikCommonCoursePackages.ts', 'fizikDoktoraCommonCoursePackages.ts')
  .replaceAll('fizikTezliCoursePackages', 'fizikDoktoraCoursePackages')
  .replaceAll('fizikCommonCoursePackages', 'fizikDoktoraCommonCoursePackages');
process.argv[2] = sourcePath;
await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
