import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root=process.cwd(), department="Muhasebe ve Finansman", programName="Muhasebe ve Finansman", level="Tezsiz Yüksek Lisans";
const official=JSON.parse(readFileSync(path.join(root,"data/courses/2026-2027.json"),"utf8")).filter(x=>x.department===department&&x.programName===programName&&x.level===level);
const db=new DatabaseSync(path.join(root,"local-volume/data/dbp.sqlite"),{readOnly:true});
const row=db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name=? AND level=?").get(programName,level);
const programOutcomes=JSON.parse(row?.outcomes_json||"[]");
if(programOutcomes.length!==11) throw new Error(`11 mevcut PÇ bekleniyordu; bulunan ${programOutcomes.length}`);

const titles={MUF730:"İşletmelerde Sermaye Yapısı ve Sermaye Maliyeti"};
const research=new Set(["MUF703","MUF704"]), projectCodes=new Set(["MUF701","MUF702"]);
const profiles={
  research:["bilimsel bilgi ve araştırma etiği","araştırma probleminin yapılandırılması","nicel ve nitel araştırma tasarımları","veri toplama ve çözümleme","akademik raporlama ve yayın etiği"],
  accounting:["muhasebe bilgi sisteminin yapısı","hesap ve kayıt düzeni","ölçüm ve değerleme yaklaşımları","finansal raporlama uygulamaları","muhasebe bilgilerinin karar süreçlerinde kullanımı"],
  finance:["finansal yönetimin amaçları","paranın zaman değeri ve nakit akışları","risk ve getiri ölçümü","finansman ve yatırım kararları","finansal sonuçların yorumlanması"],
  audit:["denetimin amacı ve kapsamı","denetim planlaması ve risk değerlendirmesi","kanıt toplama teknikleri","iç kontrol ve güvence süreçleri","denetim bulgularının raporlanması"],
  law:["mesleki düzenlemelerin kaynakları","hak, yükümlülük ve sorumluluklar","uygulama usulleri ve belgeler","uyuşmazlık ve yaptırım mekanizmaları","güncel mevzuatın mesleki kararlara etkisi"],
  markets:["finansal sistemin yapısı","piyasa araçları ve kurumları","fiyatlama, risk ve getiri ilişkisi","portföy ve yatırım kararları","piyasa düzenlemeleri ve yatırımcı korunması"],
  cost:["maliyet kavramları ve sınıflandırma","maliyet ölçüm sistemleri","bütçeleme ve sapma analizi","stratejik maliyet yönetimi","maliyet bilgilerinin karar süreçlerinde kullanımı"],
  ethics:["meslek etiğinin temel ilkeleri","etik tehditler ve çıkar çatışmaları","bağımsızlık ve mesleki özen","etik ikilemlerin çözümlenmesi","kamu yararı ve hesap verebilirlik"],
  systems:["muhasebe bilgi sisteminin bileşenleri","iş süreçleri ve belge akışı","veri tabanı ve iç kontrol","kurumsal sistemlerle bütünleşme","dijital raporlama ve bilgi güvenliği"],
  math:["finansal hesaplamaların temelleri","basit ve bileşik faiz","anüite ve borç amortismanı","menkul kıymet değerleme hesapları","finansal karar modelleri"],
  banking:["bankacılık sisteminin yapısı","banka bilançosu ve fon kaynakları","kredi ve yatırım işlemleri","likidite, sermaye ve risk yönetimi","bankacılık performansının değerlendirilmesi"],
  project:["yatırım fikri ve fizibilite çerçevesi","nakit akışlarının tahmini","iskonto edilmiş nakit akışı yöntemleri","risk ve duyarlılık analizi","yatırım kararının bütüncül değerlendirilmesi"],
  tax:["vergi hukukunun temel ilkeleri","gelir ve kurum kazançlarının vergilendirilmesi","katma değer ve diğer harcama vergileri","beyan, tarh ve tahsil süreçleri","vergi uyuşmazlıkları ve güncel mevzuat"],
};
function profileFor(name){const n=name.toLocaleLowerCase("tr-TR");if(n.includes("araştırma"))return profiles.research;if(n.includes("etik")||n.includes("ahlak"))return profiles.ethics;if(n.includes("denetim"))return profiles.audit;if(n.includes("mevzuat")||n.includes("hukuk"))return profiles.law;if(n.includes("vergi"))return profiles.tax;if(n.includes("maliyet")||n.includes("bütçe"))return profiles.cost;if(n.includes("bilgi sistem"))return profiles.systems;if(n.includes("matematik"))return profiles.math;if(n.includes("banka"))return profiles.banking;if(n.includes("yatırım proj"))return profiles.project;if(n.includes("piyasa")||n.includes("portföy")||n.includes("menkul")||n.includes("türev"))return profiles.markets;if(n.includes("muhasebe")||n.includes("hesap plan"))return profiles.accounting;return profiles.finance;}
const checklist=["Ders adı ve kodları doğrulandı mı?","Tüm OBS bağlantıları gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const qualityChecks=()=>checklist.map((item,i)=>({item,status:[1,19,20].includes(i)?"Doğrulanmalı":[3,5,6,7,8,9,10,11,12,13,14,15,16,18].includes(i)?"Revize Edildi":"Uygun",...([1,19,20].includes(i)?{note:"Kesin OBS ayrıntı bağlantısı bulunmadığından resmî katalog kimliği korunmuş; eksik akademik alanlar handoff ölçütleri ve LEE_DBP'deki güncel 11 PÇ temelinde öneri niteliğinde tamamlanmıştır."}:{})}));
const sentenceCase=s=>s.charAt(0).toLocaleUpperCase("tr-TR")+s.slice(1).toLocaleLowerCase("tr-TR");
const instructor=s=>(s||"Atama Bekliyor").replace(/^Yrd\.?\s*Doç\.?\s*Dr\.?/iu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+|\b\S+@\S+\b/giu," ").replace(/\s+/g," ").trim();
function outcomeMatrix(kind){let primary=[0,1,2,4,7], secondary=[3,5,6,8,9,10];if(kind===profiles.audit||kind===profiles.law||kind===profiles.ethics){primary=[2,6,8,9,10];secondary=[0,1,4,7];}else if(kind===profiles.finance||kind===profiles.markets||kind===profiles.math||kind===profiles.banking||kind===profiles.project){primary=[0,1,2,3,4,7];secondary=[5,8,9,10];}else if(kind===profiles.research){primary=[2,4,5,7,8,10];secondary=[0,1,3,6,9];}return Array.from({length:5},(_,r)=>({outcome:`DÖÇ${r+1}`,values:programOutcomes.map((_,c)=>primary.includes(c)?[4,4,5,4,5][r]:secondary.includes(c)?[2,3,2,3,2][r]:[1,2,1,2,1][r])}));}
function weeks(parts){return [`${sentenceCase(parts[0])}: kapsam ve temel kavramlar`,`${sentenceCase(parts[0])}: kuramsal yaklaşımlar`,`${sentenceCase(parts[0])}: mesleki uygulama alanları`,`${sentenceCase(parts[1])}: temel ilkeler`,`${sentenceCase(parts[1])}: yöntem ve teknikler`,`${sentenceCase(parts[1])}: örnek olayların çözümlenmesi`,`${sentenceCase(parts[2])}: kavramsal çerçeve`,`${sentenceCase(parts[2])}: hesaplama ve uygulamalar`,`${sentenceCase(parts[2])}: sonuçların yorumlanması`,`${sentenceCase(parts[3])}: karar ölçütleri`,`${sentenceCase(parts[3])}: risk ve kontrol boyutu`,`${sentenceCase(parts[3])}: mesleki örneklerin karşılaştırılması`,`${sentenceCase(parts[4])}: güncel gelişmeler`,`${sentenceCase(parts[4])}: etik ve düzenleyici etkiler`,`${sentenceCase(parts[4])}: bütüncül mesleki değerlendirme`];}
const workload=ects=>[{name:"Ders Süresi",count:15,hours:3,total:45},{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:6,total:90},{name:"Ara Sınav Hazırlığı",count:1,hours:20,total:20},{name:"Yarıyıl Sonu Sınavı Hazırlığı",count:1,hours:ects*30-155,total:ects*30-155}];
const academic=official.filter(x=>!projectCodes.has(x.code)&&x.code!=="MUF704").map(course=>{const name=titles[course.code]||sentenceCase(course.name),parts=profileFor(name);const outcomes=[`${sentenceCase(parts[0])} ile ilgili ileri kavramları analiz eder.`,`${sentenceCase(parts[1])} kapsamında uygun yöntemleri uygular.`,`${sentenceCase(parts[2])} ile ilgili verileri karşılaştırır ve yorumlar.`,`${sentenceCase(parts[3])} için uygulanabilir karar seçenekleri geliştirir.`,`${sentenceCase(parts[4])} bağlamındaki sonuçları mesleki ve etik ölçütlerle değerlendirir.`];const assessments=[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}];return {code:course.code,aliases:research.has(course.code)?["MUF703","MUF704"]:undefined,name,department,programName,language:"Türkçe",level,teachingMode:"Yüz Yüze",instructor:instructor(course.instructor),theory:3,practice:0,credit:3,ects:6,prerequisites:"Yok",purpose:`Öğrencinin ${parts[0]}, ${parts[1]} ve ${parts[3]} alanlarında ileri düzey mesleki çözümleme ve karar verme becerisi geliştirmesini sağlamak.`,content:`Ders; ${parts.join(", ")} konularını muhasebe ve finans uygulamalarıyla ilişkilendirerek ele alır.`,methods:"Anlatım, yönlendirilmiş tartışma, vaka çözümlemesi, finansal veri ve belge incelemesi ile bireysel çalışma.",resources:"Kamu Gözetimi Kurumu düzenlemeleri; Sermaye Piyasası Kurulu mevzuatı ve istatistikleri; Türkiye Muhasebe Standartları; Borsa İstanbul ve TCMB veri kaynakları; güncel hakemli muhasebe ve finans literatürü.",sdgs:["4","8","16"],outcomes,weeklyTopics:weeks(parts),assessments,workloads:workload(6),contributionMatrix:outcomeMatrix(parts),qualityChecks:qualityChecks(),publicQualityChecklist:false};});
const projectOutcomes=["Muhasebe veya finans alanında uygulanabilir bir proje problemi yapılandırır.","Proje problemine ilişkin mesleki ve akademik kaynakları eleştirel değerlendirir.","Proje amacına uygun veri ve çözümleme yaklaşımını planlar.","Proje bulgularını mesleki, finansal ve etik ölçütlerle yorumlar.","Bitirme projesini akademik yazım ilkelerine uygun biçimde raporlar."];
const project={code:"MUF7XX",aliases:["MUF701","MUF702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Proje Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin muhasebe ve finans alanındaki ileri bilgi ve becerilerini mesleki bir problem üzerinde bütünleştirerek bilimsel ve etik ölçütlere uygun bir bitirme projesi yürütmesini sağlamak.",content:"Proje probleminin belirlenmesi, kaynak ve veri incelemesi, çözümleme yaklaşımının planlanması, bulguların yorumlanması ve sonuçların akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışmanlık görüşmesi, literatür ve veri incelemesi, mesleki çözümleme, akademik raporlama ve yapılandırılmış geri bildirim.",resources:"Enstitü proje yazım ilkeleri; KGK, SPK, Borsa İstanbul ve TCMB kaynakları; ilgili güncel hakemli yayınlar.",sdgs:["4","8","16"],outcomes:projectOutcomes,weeklyTopics:["Proje alanının ve kapsamının belirlenmesi","Mesleki problemin sınırlandırılması","Proje amacı ve sorularının yapılandırılması","Kaynak tarama stratejisinin oluşturulması","Alan yazınının tematik sınıflandırılması","Kuramsal ve uygulamalı çerçevenin kurulması","Veri kaynaklarının ve göstergelerin belirlenmesi","Çözümleme yaklaşımı ile iş planının yapılandırılması","Etik, veri güvenliği ve izin gerekliliklerinin değerlendirilmesi","Muhasebe veya finans verilerinin düzenlenmesi","Bulguların çözümlenmesi ve yorumlanması","Bulguların alan yazınıyla karşılaştırılması","Mesleki ve yönetsel çıkarımların geliştirilmesi","Akademik metin, atıf ve kaynakça düzeni","Bitirme projesinin bütüncül değerlendirilmesi"],assessments:[{name:"Bitirme Projesi",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışmanlık",count:15,hours:2,total:30},{name:"Literatür ve Veri İncelemesi",count:15,hours:20,total:300},{name:"Çözümleme ve Raporlama",count:15,hours:38,total:570}],contributionMatrix:outcomeMatrix(profiles.research),qualityChecks:qualityChecks(),publicQualityChecklist:false};
if(academic.length!==34) throw new Error(`34 akademik ders bekleniyordu; bulunan ${academic.length}`);
for(const c of [...academic,project]){if(c.weeklyTopics.length!==15)throw new Error(`${c.code}: 15 hafta yok`);if(c.code!=="MUF7XX"&&c.weeklyTopics.some(x=>/(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|final)/iu.test(x)))throw new Error(`${c.code}: yasak başlık`);if(c.workloads.reduce((s,x)=>s+x.total,0)!==c.ects*30)throw new Error(`${c.code}: iş yükü`);if(c.contributionMatrix.some(r=>r.values.length!==11||r.values.some(v=>v<1||v>5)))throw new Error(`${c.code}: matris`);}
const emit=(file,name,value)=>writeFileSync(path.join(root,"lib/data",file),`import type { CoursePackage } from "./coursePackages";\n\nexport const ${name}: CoursePackage[] = ${JSON.stringify(value,null,2)};\n`);
emit("muhasebeFinansmanTezsizCoursePackages.ts","muhasebeFinansmanTezsizCoursePackages",academic);
emit("muhasebeFinansmanTezsizCommonCoursePackages.ts","muhasebeFinansmanTezsizCommonCoursePackages",[project]);
console.log(JSON.stringify({official:official.length,academic:academic.length,common:1,outcomes:programOutcomes.length}));
