import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="ekoturizm rehberligi tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["Ekoturizm ve sürdürülebilirlik kuramlarını analiz eder ve uygular.","Disiplinler arası ekoturizm sorunlarına özgün çözümler geliştirir.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Ekoturizm faaliyetlerindeki riskleri analiz eder ve yönetir.","Sürdürülebilir ekoturizm uygulamaları tasarlar ve değerlendirir.","Ekoturizm politika ve mevzuatını eleştirel değerlendirir.","Etik, çevresel ve sürdürülebilirlik ilkelerini uygular.","Dijital ve analitik araçları ekoturizm çalışmalarında kullanır.","Saha ve akademik çalışmalarda liderlik ve iş birliği yapar.","Bilimsel ve mesleki çalışmalarını etkili biçimde sunar.","Güncel ulusal ve uluslararası gelişmeleri izler ve mesleki uygulamalara aktarır."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Ekoturizm Rehberliği ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/ekoloji|ekosistem|flora|fauna|biyolojik|botanik|cevre|kirlilik/u.test(n))return{label:"ekoloji ve koruma",core:[1,5,7],sdgs:["13","14","15"],terms:["ekolojik sistemler","biyolojik çeşitlilik","habitat ve tür ilişkileri","çevresel baskılar","koruma yaklaşımları","saha gözlemi","etki değerlendirmesi","sürdürülebilir yönetim"]};
 if(/tarim|kirsal|gastronomi|mutfak/u.test(n))return{label:"kırsal kalkınma ve yerel değerler",core:[2,5,7],sdgs:["2","8","12"],terms:["kırsal alan ve yerel ekonomi","tarımsal üretim","yerel kültür ve gastronomi","toplum katılımı","turizm ürünü geliştirme","taşıma kapasitesi","sürdürülebilir değer zinciri","kırsal kalkınma"]};
 if(/kultur|tarih|muze|medeniyet|sanat/u.test(n))return{label:"kültürel miras ve yorumlama",core:[2,5,10],sdgs:["4","11","12"],terms:["somut ve somut olmayan miras","kültürel peyzaj","koruma ilkeleri","miras yorumlama","ziyaretçi deneyimi","yerel kimlik","etik temsil","sürdürülebilir kullanım"]};
 if(/yonetim|isletme|girisim|pazarlama|seyahat|endustri/u.test(n))return{label:"ekoturizm işletmeciliği ve yönetimi",core:[2,5,9],sdgs:["8","9","12"],terms:["turizm işletmesi","stratejik planlama","girişimcilik","pazar ve ziyaretçi analizi","ürün geliştirme","paydaş yönetimi","kalite ve performans","sürdürülebilir işletmecilik"]};
 if(/veri|analiz|arastirma/u.test(n))return{label:"sosyal bilim araştırmaları",core:[3,8,10],sdgs:["4","9","17"],terms:["araştırma problemi","araştırma deseni","örnekleme","veri toplama","veri kalitesi","analiz yaklaşımı","bulguların yorumlanması","bilimsel raporlama"]};
 if(/ilk yardim|hayatta|risk/u.test(n))return{label:"doğa faaliyetlerinde risk ve güvenlik",core:[4,5,9],sdgs:["3","8","15"],terms:["risk tanımlama","doğa koşulları","ilk değerlendirme","temel yaşam desteği","yaralanma ve aciller","rota güvenliği","kriz iletişimi","olay sonrası değerlendirme"]};
 if(/ingilizce/u.test(n))return{label:"mesleki yabancı dil iletişimi",core:[10,9,11],sdgs:["4","8","17"],terms:["ekoturizm terminolojisi","ziyaretçi karşılama","rota ve alan tanıtımı","doğal miras anlatımı","kültürel miras anlatımı","risk iletişimi","mesleki yazışma","rehberlik söylemi"]};
 return{label:"ekoturizm rehberliği",core:[1,5,11],sdgs:["8","12","15"],terms:["ekoturizm kavramı","sürdürülebilirlik ilkeleri","ziyaretçi ve destinasyon","doğal ve kültürel değerler","rehberlik yaklaşımı","paydaş katılımı","etki ve riskler","güncel uygulamalar"]};};
const generatedWeeks=(name,d)=>{const s=prose(name);return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbidden=/\b(quiz|kısa sınav|odev|ödev|proje|sunum|konu tekrarı|genel tekrar|ara sınav|vize|final|yarıyıl sonu)\b/iu;
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|ETR80[1-8]|ETR85[5-6]|BES802)$/u;
const academic=official.filter((o)=>!common.test(o.code)&&o.code!=="EKOTURİZM SEÇ-2").map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbidden.test(clean(x[1]))).map((x)=>x[1])),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Ekoturizm Rehberliği ABD",programName:"Ekoturizm Rehberliği",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:detail(c,"dersin amaci")||`${cap(sub)} alanındaki yaklaşımları sürdürülebilirlik ilkeleriyle değerlendirme yetkinliği kazandırmak.`,content:detail(c,"dersin icerigi")||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:detail(c,"dersin yontem ve teknikleri")||"Kuramsal anlatım, bilimsel kaynak incelemesi, örnek olay çözümlemesi ve akademik tartışma.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"UN Tourism sürdürülebilir turizm kaynakları; IUCN korunan alan rehberleri; güncel hakemli ekoturizm literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin ekoturizm araştırmasını bilimsel yöntem, sürdürülebilirlik ve etik ilkeler doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, ekoturizm literatürü, araştırma problemi, yöntem, saha etiği, veri yönetimi, ilerleme ve raporlama.",stages:["Akademik çalışma planı","Ekoturizm araştırma alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Sürdürülebilirlik ve etik gereklilikler","Araştırma tasarımının değerlendirilmesi","Saha ve veri toplama planı","Araştırma kayıtlarının kontrolü","Bulguların ön değerlendirmesi","Analiz yaklaşımının gözden geçirilmesi","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Akademik ilerleme izlemesi","Sonraki dönem çalışma planı"]},
{code:"ETR8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili ileri ekoturizm literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal-yöntemsel altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü ekoturizm literatürü, sürdürülebilirlik kuramları, araştırma problemi, yöntem, saha bağlamı, etki değerlendirmesi ve etik.",stages:["Tez alanının bilimsel kapsamı","İleri ekoturizm literatürü","Sürdürülebilirlik kuramları","Araştırma boşluğunun tanımlanması","Araştırma soruları","Kuramsal varsayımlar","Araştırma desenleri","Örnekleme yaklaşımı","Saha ve veri kaynakları","Veri kalite ölçütleri","Analiz seçenekleri","Bulguların yorum çerçevesi","Etik ve çevresel riskler","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"ETR806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Ekoturizm alanındaki bilimsel bir problemi literatüre dayalı inceleme, akademik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, araştırma problemi, kanıt sentezi, bilimsel metin, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Literatür tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Ekoturizm kanıtlarının karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve bulguların sentezi","Tablo ve görsellerin düzenlenmesi","Bilimsel tartışmanın yapılandırılması","Sonuç ve çıkarımlar","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel anlatımın uygulanması","Geri bildirimle nihai düzenleme"]},
{code:"ETR855",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Ekoturizm araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, analiz etme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, sosyal bilim araştırma desenleri, örnekleme, veri toplama, analiz, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve ekoturizm araştırması","Araştırma problemi ve hipotez","Nicel araştırma desenleri","Nitel araştırma desenleri","Örnekleme","Veri toplama araçları","Geçerlik ve güvenirlik","Veri analizi yaklaşımları","Bulguların yorumlanması","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Saha etiği ve katılımcı hakları","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"ETR81X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin ekoturizm alanında bağımsız bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün ekoturizm araştırma problemi, literatür sentezi, araştırma tasarımı, saha etiği, veri üretimi, analiz, sürdürülebilirlik bağlamında yorum, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve hipotezlerin yapılandırılması","Yöntem ve örnekleme planı","Etik ve saha izinleri","Veri toplama planı","Saha kayıtları ve kalite kontrolü","Veri toplama sürecinin izlenmesi","Verilerin düzenlenmesi","Analizlerin yürütülmesi","Bulguların ekoturizm açısından yorumlanması","Bulguların literatürle karşılaştırılması","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="ETR806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="ETR855"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Ekoturizm Rehberliği ABD",programName:"Ekoturizm Rehberliği",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="ETR855"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="ETR855"?"Doç. Dr. ÖNDER YAYLA":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, akademik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"UN Tourism ve IUCN kaynakları; güncel hakemli ekoturizm literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","ekoturizmTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const ekoturizmTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","ekoturizmCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const ekoturizmCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));
