import { readFileSync } from "node:fs";

const sourcePath = process.argv[2] || process.env.BOLOGNA_DERS_JSON;
if (!sourcePath) throw new Error("Kullanım: node scripts/generate_gida_muhendisligi_doktora_course_packages.mjs <ders-verileri.json>");

let source = readFileSync(new URL("./generate_gida_muhendisligi_tezli_course_packages.mjs", import.meta.url), "utf8");
source = source
  .replace('fold(p.name)==="gida muhendisligi tezli yuksek lisans"', 'fold(p.name)==="gida muhendisligi doktora"')
  .replace(/const pcs=\[[\s\S]*?\];\nconst raw=/, `const pcs=[
"İleri gıda mühendisliği bilgilerini özgün araştırma problemlerinde eleştirel biçimde sentezler.",
"Karmaşık gıda problemlerine yönelik özgün araştırma soruları ve hipotezler geliştirir.",
"Gıda araştırmaları için yenilikçi proses, analiz ve deneysel yöntemler geliştirir.",
"Karmaşık gıda verilerini ileri analitik ve istatistiksel yöntemlerle analiz eder.",
"Araştırma bulgularını güncel uluslararası gıda literatürü bağlamında eleştirel değerlendirir.",
"Gıda mühendisliği alanında bağımsız ve özgün bilimsel araştırmaları tasarlar ve yürütür.",
"Özgün araştırma sonuçlarıyla gıda bilimi ve teknolojisine yeni bilgi kazandırır.",
"Karmaşık gıda problemlerinde farklı bilim ve mühendislik disiplinlerini bütünleştirir.",
"Araştırmalarda bilimsel etik, gıda güvenliği ve araştırma bütünlüğü ilkelerini uygular.",
"Özgün araştırma sonuçlarını uluslararası yayınlarda ve akademik ortamlarda savunur.",
"Gıda teknolojilerinin sağlık, çevre ve toplumsal etkilerine yönelik stratejiler geliştirir."
];
const raw=`)
  .replace('l.includes(\'level: "Tezli Yüksek Lisans"\')', 'l.includes(\'level: "Doktora"\')')
  .replace('"konu tekrari","genel tekrar"', '"tekrar"')
  .replaceAll('DOKTORA YETERLİLİK', 'DOKTORA YETERLİK')
  .replace('const common=/^(DAN80[1-4]|GMB80[1-8]|GMB85[36])$/u;', 'const common=/^(DAN90[1-8]|GMB90[1-9]|GMB910|GMB91[2-8])$/u;')
  .replaceAll('level:"Tezli Yüksek Lisans"', 'level:"Doktora"')
  .replace('!src&&i===1?"Doğrulanmalı"', '!src&&(i===1||i===20)?"Doğrulanmalı"')
  .replace('name=c?.name||o.name.replace(/\\.\\.\\.$/u,"").trim()', 'name=clean(c?.name||o.name.replace(/\\.\\.\\.$/u,"").trim())')
  .replace(
    'const domain=(name)=>{const n=fold(name);',
    `const domain=(name)=>{const n=fold(name);
 if(/gelisim ve ogrenme/u.test(n))return{label:"öğrenme kuramları ve akademik gelişim",core:[5,8,10],sdgs:["4","10","16"],terms:["gelişim ve öğrenmenin kuramsal temelleri","bilişsel gelişim yaklaşımları","öğrenme kuramlarının karşılaştırılması","bireysel farklılıklar ve öğrenme","üst düzey düşünme süreçleri","yetişkin öğrenmesi","öğrenme ortamlarının değerlendirilmesi","akademik gelişim ve etik"]};
 if(/ogretimde planlama ve degerlendirme/u.test(n))return{label:"öğretim tasarımı ve değerlendirme",core:[3,4,10],sdgs:["4","10","16"],terms:["öğretim tasarımının kuramsal temelleri","öğrenme çıktılarının yapılandırılması","program ve ders planlama yaklaşımları","öğretim stratejilerinin seçimi","ölçme araçlarının geliştirilmesi","geçerlik ve güvenirlik","değerlendirme verilerinin analizi","öğretim kalitesinin iyileştirilmesi"]};`)
  .replace('const specs=[', `const generatedOverrides={
"PFE901":{purpose:"Gelişim ve öğrenme kuramlarını doktora düzeyindeki öğretim, araştırma ve akademik rehberlik süreçleri bağlamında eleştirel değerlendirme yetkinliği kazandırmak.",content:"Bilişsel, duyuşsal ve sosyal gelişim; davranışçı, bilişsel, yapılandırmacı ve yetişkin öğrenmesi yaklaşımları; bireysel farklılıklar, üst düzey düşünme ve kapsayıcı öğrenme ortamları.",methods:"Kuramsal anlatım, karşılaştırmalı kuram incelemesi, akademik tartışma, vaka analizi ve bilimsel kaynak değerlendirmesi.",resources:"Gelişim psikolojisi, öğrenme psikolojisi ve yetişkin öğrenmesi alanındaki temel eserler; güncel hakemli eğitim araştırmaları.",outcomes:["Gelişim ve öğrenme kuramlarını doktora düzeyinde eleştirel karşılaştırır.","Bireysel farklılıkların öğrenme süreçlerine etkilerini analiz eder.","Üst düzey düşünmeyi destekleyen öğrenme yaklaşımlarını değerlendirir.","Kapsayıcı öğrenme ortamları için bilimsel gerekçeli stratejiler geliştirir.","Öğrenme araştırmalarını etik ve yöntemsel ölçütlerle yorumlar."]},
"PFE902":{purpose:"Doktora düzeyinde öğrenme çıktısı temelli öğretim tasarlama ve geçerli, güvenilir değerlendirme süreçleri geliştirme yetkinliği kazandırmak.",content:"Öğretim tasarımı, öğrenme çıktıları, program ve ders planlama, öğretim stratejileri, ölçme aracı geliştirme, geçerlik, güvenirlik, değerlendirme verilerinin analizi ve kalite iyileştirme.",methods:"Kuramsal anlatım, öğretim tasarımı incelemesi, ölçme aracı çözümlemesi, veri yorumlama, vaka analizi ve akademik tartışma.",resources:"Öğretim tasarımı, program geliştirme ve eğitimde ölçme-değerlendirme alanındaki temel eserler; güncel hakemli eğitim araştırmaları.",outcomes:["Öğrenme çıktısı temelli öğretim tasarımlarını eleştirel değerlendirir.","Program amaçlarıyla uyumlu öğretim stratejileri geliştirir.","Geçerli ve güvenilir ölçme araçlarının özelliklerini analiz eder.","Değerlendirme verilerini öğretim kalitesini geliştirmek için yorumlar.","Doktora düzeyine uygun bir ders ve değerlendirme planı tasarlar."]},
"GMB968":{purpose:"Gıda mühendisliği alanında özgün araştırmaları bilimsel yöntem, araştırma bütünlüğü ve yayın etiği ilkelerine uygun biçimde tasarlama ve değerlendirme yetkinliği kazandırmak.",content:"Araştırma problemi ve hipotez, deneysel tasarım, örnekleme, analitik yöntem seçimi ve doğrulama, veri analizi, bilimsel yazım, araştırma bütünlüğü, yazarlık, hakemlik ve yayın etiği.",methods:"Kuramsal anlatım, araştırma tasarımı çözümlemesi, makale incelemesi, veri yorumlama, etik vaka analizi ve akademik tartışma.",resources:"Gıda mühendisliği araştırma yöntemleri ve deneysel tasarım kaynakları; araştırma bütünlüğü ve yayın etiği kılavuzları; güncel hakemli alan literatürü.",outcomes:["Özgün gıda araştırma problemlerini ve hipotezlerini geliştirir.","Deneysel tasarım ve örnekleme yaklaşımlarını eleştirel değerlendirir.","Analitik yöntemlerin geçerlik ve güvenirlik ölçütlerini analiz eder.","Araştırma verilerini uygun bilimsel yöntemlerle yorumlar.","Araştırma ve yayın süreçlerinde etik ilkeleri gerekçelendirerek uygular."]}
};
for(const item of academic){if(generatedOverrides[item.code])Object.assign(item,generatedOverrides[item.code]);}
const specs=[`)
  .replace(/const specs=\[[\s\S]*?\];\nconst commons=/, `const specs=[
{code:"DAN9XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin doktora araştırmasını bilimsel özgünlük, yöntem, etik, yayın ve zaman yönetimi bakımından yönlendirmek.",content:"Doktora araştırma planı, ileri gıda mühendisliği literatürü, özgün problem, yöntem geliştirme, veri yönetimi, araştırma bütünlüğü, yayın stratejisi ve ilerleme izlemesi.",stages:["Doktora çalışma planının oluşturulması","Gıda mühendisliği uzmanlık alanının sınırlandırılması","İleri literatür tarama stratejisinin değerlendirilmesi","Özgün araştırma probleminin netleştirilmesi","Etik, gıda güvenliği ve biyogüvenlik gereklilikleri","Hipotez ve araştırma tasarımının değerlendirilmesi","Deneysel çalışma ve veri üretim planı","Araştırma kayıtları ve kalite güvencesi","Bulguların eleştirel ön değerlendirmesi","İleri analiz yaklaşımının gözden geçirilmesi","Bilimsel yayın planının oluşturulması","Kaynak ve araştırma bütünlüğü denetimi","Araştırma sınırlılıklarının değerlendirilmesi","Doktora ilerlemesi ve özgün katkının izlenmesi","Sonraki dönem araştırma hedeflerinin kararlaştırılması"]},
{code:"GMB9XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin doktora tez alanındaki güncel gıda mühendisliği literatürünü eleştirel biçimde sentezlemesini ve özgün araştırmasının kuramsal, deneysel ve analitik temelini geliştirmesini sağlamak.",content:"Doktora tez alanına özgü gıda bilimi ve proses kuramları, araştırma boşluğu, ileri deneysel ve analitik yöntemler, veri kalitesi, gıda güvenliği, sürdürülebilirlik ve araştırma etiği.",stages:["Doktora tez alanının bilimsel kapsamı","Güncel gıda mühendisliği literatürünün eleştirel sınıflandırılması","Kuramsal ve teknolojik yaklaşımların sentezlenmesi","Uluslararası literatürde araştırma boşluğunun belirlenmesi","Özgün araştırma sorularının geliştirilmesi","Hipotezlerin bilimsel temellendirilmesi","İleri proses ve analiz yöntemlerinin karşılaştırılması","Deneysel tasarımın değerlendirilmesi","Numune, ölçüm ve veri üretim yöntemleri","Belirsizlik, veri kalitesi ve tekrarlanabilirlik","İleri analiz seçeneklerinin karşılaştırılması","Bulguların gıda mühendisliği açısından yorumlanması","Gıda güvenliği, sürdürülebilirlik ve etik riskler","Özgün katkı ve sınırlılıkların tartışılması","Kuramsal ve yöntemsel çerçevenin bütünleştirilmesi"]},
{code:"GMB909",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Gıda mühendisliğinde ileri bir bilimsel problemi eleştirel literatür senteziyle inceleme, akademik metne dönüştürme ve doktora düzeyinde savunma becerisi kazandırmak.",content:"İleri literatür tarama, kanıt değerlendirme, özgün gıda mühendisliği problemi, bilimsel metin, deneysel ve analitik bulguların sentezi, akademik tartışma ve bilimsel iletişim.",stages:["Seminer konusunun özgünlük ve kapsam bakımından belirlenmesi","İleri araştırma sorusunun geliştirilmesi","Sistematik literatür tarama stratejisinin kurulması","Kaynakların kanıt düzeyi bakımından değerlendirilmesi","Literatürün kavramsal sınıflandırılması","Deneysel ve analitik kanıtların karşılaştırılması","Seminer metninin bilimsel yapısının oluşturulması","Yöntem ve bulguların eleştirel sentezi","Tablo ve görsellerin düzenlenmesi","Doktora düzeyinde tartışmanın yapılandırılması","Özgün gıda mühendisliği çıkarımlarının geliştirilmesi","Atıf ve kaynakça bütünlüğünün denetlenmesi","Akademik anlatım tasarımının geliştirilmesi","Bilimsel savunmanın uygulanması","Geri bildirimle nihai metnin geliştirilmesi"]},
{code:"GMB917",name:"DOKTORA YETERLİLİK",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin ileri gıda mühendisliği bilgisi, bilimsel problem çözme, özgün araştırma tasarlama ve bağımsız araştırma yürütme yeterliliğini bütüncül olarak değerlendirmek.",content:"İleri gıda bilimi ve mühendisliği bilgisi, disiplinler arası sentez, özgün problem ve hipotez, proses ve analiz yöntemleri, ileri veri analizi, gıda güvenliği, etik ve bilimsel savunma.",stages:["Yeterlik kapsamındaki gıda mühendisliği alanlarının belirlenmesi","İleri alan bilgisinin sistematik incelenmesi","Gıda bilimi ve mühendisliği alt alanlarının sentezi","Karmaşık gıda problemlerinin bilimsel çözümlemesi","Özgün araştırma sorusu geliştirme","Hipotezlerin eleştirel değerlendirilmesi","Proses ve analiz modellerinin karşılaştırılması","Deneysel yöntem ve örnekleme seçimi","Ölçüm belirsizliği ve geçerlik ölçütleri","İleri analitik ve istatistiksel çözümleme","Bulguların gıda literatürü bağlamında yorumlanması","Bilimsel etik ve araştırma bütünlüğü","Gıda güvenliği ve toplumsal etkilerin değerlendirilmesi","Bilimsel argümanın yazılı yapılandırılması","Bilimsel argümanın sözlü savunulması"]},
{code:"GMB91X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin gıda mühendisliği alanında özgün ve bağımsız bir doktora araştırmasını etik ilkelere uygun biçimde yürütmesi, yayımlaması ve savunmasını sağlamak.",content:"Özgün gıda mühendisliği problemi, ileri literatür sentezi, proses veya deney tasarımı, veri üretimi, doğrulama ve ileri analiz, bilimsel yayın, tez yazımı ve savunma.",stages:["Özgün araştırma probleminin kesinleştirilmesi","İleri literatür çerçevesinin güncellenmesi","Araştırma amaç ve hipotezlerinin yapılandırılması","Yenilikçi proses veya deney planının kesinleştirilmesi","Etik, gıda güvenliği ve biyogüvenlik süreçleri","Veri üretim sürecinin planlanması","Araştırma kayıtları ve kalite kontrolü","Deneysel veya analitik sürecin izlenmesi","Verilerin düzenlenmesi ve doğrulanması","İleri analizlerin yürütülmesi","Bulguların gıda mühendisliği açısından yorumlanması","Özgün katkının literatürle karşılaştırılması","Bilimsel yayın ve tez bölümlerinin yazımı","Tez metninin bütünlük ve etik denetimi","Doktora savunması ve bilimsel katkının sunulması"]}
];
const commons=`)
  .replace('s.code==="GMB806"', 's.code==="GMB909"')
  .replaceAll('gidaMuhendisligiTezliCoursePackages.ts', 'gidaMuhendisligiDoktoraCoursePackages.ts')
  .replaceAll('gidaMuhendisligiCommonCoursePackages.ts', 'gidaMuhendisligiDoktoraCommonCoursePackages.ts')
  .replaceAll('gidaMuhendisligiTezliCoursePackages', 'gidaMuhendisligiDoktoraCoursePackages')
  .replaceAll('gidaMuhendisligiCommonCoursePackages', 'gidaMuhendisligiDoktoraCommonCoursePackages');

process.argv[2] = sourcePath;
await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
