import { readFileSync } from "node:fs";

const sourcePath = process.argv[2] || process.env.BOLOGNA_DERS_JSON;
if (!sourcePath) throw new Error("Kullanım: node scripts/generate_kimya_doktora_course_packages.mjs <ders-verileri.json>");

let source = readFileSync(new URL("./generate_kimya_tezli_course_packages.mjs", import.meta.url), "utf8");
source = source
  .replace('fold(x.name)==="kimya tezli yuksek lisans"', 'fold(x.name)==="kimya doktora"')
  .replace('Kimya Tezli Yüksek Lisans programı bulunamadı.', 'Kimya Doktora programı bulunamadı.')
  .replace(/const pc=\[[\s\S]*?\];\nconst official=/, `const pc=[
"İleri kimya bilgilerini özgün araştırma problemlerinin çözümünde eleştirel biçimde sentezler.",
"Karmaşık kimyasal problemlere yönelik özgün araştırma soruları ve hipotezler geliştirir.",
"Kimya araştırmaları için yenilikçi deneysel, analitik ve kuramsal yöntemler geliştirir.",
"Karmaşık kimyasal verileri ileri analitik ve istatistiksel yöntemlerle analiz eder.",
"Araştırma bulgularını güncel uluslararası kimya literatürü bağlamında eleştirel değerlendirir.",
"Kimya alanında bağımsız ve özgün bilimsel araştırmaları tasarlar ve yürütür.",
"Özgün araştırma sonuçlarıyla kimya bilim alanına yeni bilgi kazandırır.",
"Karmaşık kimya problemlerinde farklı bilim alanlarının bilgi ve yöntemlerini bütünleştirir.",
"Araştırmalarda bilimsel etik, kimyasal güvenlik ve araştırma bütünlüğü ilkelerini uygular.",
"Özgün araştırma sonuçlarını uluslararası yayınlarda ve akademik ortamlarda savunur.",
"Kimyasal süreçlerin çevresel ve toplumsal etkilerine yönelik sürdürülebilir stratejiler geliştirir."
];
const official=`)
  .replace('x.level==="Tezli Yüksek Lisans"', 'x.level==="Doktora"')
  .replace('const common=/^(DAN80[1-4]|KİM80[1-8]|KİM8(39|40))$/u', 'const common=/^(DAN90[1-8]|KİM90[1-9]|KİM910|KİM91[2-8])$/u')
  .replace('const academics=official.filter((o)=>!common.test(o.code)).map', 'const academics=official.filter((o)=>!common.test(o.code)&&o.code!=="KİM932").map')
  .replace('const common=/^(DAN90[1-8]|KİM90[1-9]|KİM910|KİM91[2-8])$/u,forbidden=/(quiz|ödev|proje|sunum|konu tekrarı|genel tekrar|ara\\s*sınav|arasınav|yarıyıl sonu sınavı)/iu;', 'const common=/^(DAN90[1-8]|KİM90[1-9]|KİM910|KİM91[2-8])$/u,forbidden=/^(quiz|ödev|proje|sunum|konu tekrarı|genel tekrar|ara\\s*sınav|arasınav|vize(?: sınavı)?|yarıyıl sonu sınavı|final(?: sınavı)?)$/iu;')
  .replaceAll('level:"Tezli Yüksek Lisans"', 'level:"Doktora"')
  .replace('const outcomes=(name,d)=>{const s=clean(name).toLocaleLowerCase("tr-TR");return[`${start(s)} kapsamındaki ileri kuramsal bilgileri analiz eder.`,`${start(d.label)} yaklaşımlarını karşılaştırır.`,`${start(s)} kapsamında uygun iktisadi modeli uygular.`,`${start(s)} bulgularını ekonomik ve toplumsal etkileriyle değerlendirir.`,`${start(s)} alanındaki kanıtlara dayalı politika çıkarımları geliştirir.`]};', 'const outcomes=(name,d)=>{const s=clean(name).toLocaleLowerCase("tr-TR");return[`${start(s)} kapsamındaki ileri kimya bilgilerini eleştirel biçimde analiz eder.`,`${start(d.label)} alanındaki kuramsal ve deneysel yaklaşımları karşılaştırır.`,`${start(s)} kapsamında uygun araştırma veya analiz yöntemini uygular.`,`${start(s)} bulgularını bilimsel, güvenlik ve çevresel boyutlarıyla değerlendirir.`,`${start(s)} alanındaki kanıtlardan özgün araştırma çıkarımları geliştirir.`]};')
  .replace('alanındaki kuramsal yaklaşımları, ampirik kanıtları ve politika sonuçlarını lisansüstü düzeyde değerlendirme yetkinliği kazandırmayı amaçlamaktadır.', 'alanındaki ileri kuramsal ve deneysel yaklaşımları doktora düzeyinde eleştirel değerlendirme ve özgün araştırma problemi geliştirme yetkinliği kazandırmayı amaçlamaktadır.')
  .replace('Dersin gerçek OBS kaynakları; güncel iktisat literatürü, hakemli makaleler ve ilgili ulusal/uluslararası veri kaynakları.', 'Dersin gerçek OBS kaynakları; güncel kimya literatürü, hakemli makaleler ve ilgili ulusal/uluslararası kimyasal veri kaynakları.')
  .replace('instructor:s.code==="KİM839"?"Prof. Dr. SABRİ ULUKANLI":"Öğrencinin Danışmanı"', 'instructor:"Öğrencinin Danışmanı"')
  .replace('s.code==="KİM839"', 'false')
  .replace('!source&&i===1?"Doğrulanmalı"', '!source&&(i===1||i===20)?"Doğrulanmalı"')
  .replace('const commonSpecs=[', `const generatedOverrides={
"PFE901":{purpose:"Gelişim ve öğrenme kuramlarını doktora düzeyindeki öğretim, araştırma ve akademik rehberlik süreçleri bağlamında eleştirel değerlendirme yetkinliği kazandırmak.",content:"Bilişsel, duyuşsal ve sosyal gelişim; davranışçı, bilişsel, yapılandırmacı ve yetişkin öğrenmesi yaklaşımları; bireysel farklılıklar, üst düzey düşünme ve kapsayıcı öğrenme ortamları.",methods:"Kuramsal anlatım, karşılaştırmalı kuram incelemesi, akademik tartışma, vaka analizi ve bilimsel kaynak değerlendirmesi.",resources:"Gelişim psikolojisi, öğrenme psikolojisi ve yetişkin öğrenmesi alanındaki temel eserler ile güncel hakemli eğitim araştırmaları.",outcomes:["Gelişim ve öğrenme kuramlarını doktora düzeyinde eleştirel karşılaştırır.","Bireysel farklılıkların öğrenme süreçlerine etkilerini analiz eder.","Üst düzey düşünmeyi destekleyen öğrenme yaklaşımlarını değerlendirir.","Kapsayıcı öğrenme ortamları için bilimsel gerekçeli stratejiler geliştirir.","Öğrenme araştırmalarını etik ve yöntemsel ölçütlerle yorumlar."]},
"PFE902":{purpose:"Doktora düzeyinde öğrenme çıktısı temelli öğretim tasarlama ve geçerli, güvenilir değerlendirme süreçleri geliştirme yetkinliği kazandırmak.",content:"Öğretim tasarımı, öğrenme çıktıları, program ve ders planlama, öğretim stratejileri, ölçme aracı geliştirme, geçerlik, güvenirlik, değerlendirme verilerinin analizi ve kalite iyileştirme.",methods:"Kuramsal anlatım, öğretim tasarımı incelemesi, ölçme aracı çözümlemesi, veri yorumlama, vaka analizi ve akademik tartışma.",resources:"Öğretim tasarımı, program geliştirme ve eğitimde ölçme-değerlendirme alanındaki temel eserler ile güncel hakemli eğitim araştırmaları.",outcomes:["Öğrenme çıktısı temelli öğretim tasarımlarını eleştirel değerlendirir.","Program amaçlarıyla uyumlu öğretim stratejileri geliştirir.","Geçerli ve güvenilir ölçme araçlarının özelliklerini analiz eder.","Değerlendirme verilerini öğretim kalitesini geliştirmek için yorumlar.","Doktora düzeyine uygun bir ders ve değerlendirme planı tasarlar."]},
"KİM931":{aliases:["KİM931","KİM932"],purpose:"Kimya alanındaki özgün araştırmaları bilimsel yöntem, kimyasal güvenlik, araştırma bütünlüğü ve yayın etiği ilkelerine uygun biçimde tasarlama ve değerlendirme yetkinliği kazandırmak.",content:"Araştırma problemi ve hipotez, deneysel tasarım, örnekleme, analitik yöntem seçimi ve doğrulama, veri analizi, bilimsel yazım, kimyasal güvenlik, araştırma bütünlüğü, yazarlık, hakemlik ve yayın etiği.",methods:"Kuramsal anlatım, araştırma tasarımı çözümlemesi, makale incelemesi, veri yorumlama, güvenlik ve etik vaka analizi ile akademik tartışma.",resources:"Kimya araştırma yöntemleri ve deneysel tasarım kaynakları; kimyasal güvenlik, araştırma bütünlüğü ve yayın etiği kılavuzları; güncel hakemli kimya literatürü.",outcomes:["Özgün kimya araştırma problemlerini ve hipotezlerini geliştirir.","Deneysel tasarım ve örnekleme yaklaşımlarını eleştirel değerlendirir.","Analitik yöntemlerin geçerlik ve güvenirlik ölçütlerini analiz eder.","Kimyasal araştırma verilerini uygun bilimsel yöntemlerle yorumlar.","Araştırma ve yayın süreçlerinde etik ve güvenlik ilkelerini uygular."]},
"KİM925":{purpose:"Farmasötik etkin maddelerin çok basamaklı sentezlerini yapı–etki ilişkileri, seçicilik ve yöntem geliştirme ölçütleriyle eleştirel değerlendirme ve özgün sentez stratejileri geliştirme yetkinliği kazandırmak.",content:"Farmasötik etkin madde sınıfları, hedef molekül ve retrosentetik çözümleme, karbon–karbon ve karbon–heteroatom bağ oluşumları, çapraz eşleşme tepkimeleri, heterohalka sentezleri, stereoseçicilik, reaksiyon koşullarının seçimi, saflaştırma, yapı doğrulama, güvenlik ve sürdürülebilir sentez.",methods:"Kuramsal anlatım, retrosentetik problem çözme, güncel sentez makalelerinin eleştirel incelenmesi, reaksiyon mekanizması çözümlemesi ve sentez rotası karşılaştırması.",resources:"Ankara Üniversitesi Kimya Bölümü İlaç Aktif Maddelerinin Sentezi ders içeriği; Ege Üniversitesi Aktif Farmasötik Bileşiklerin Sentezi ders kataloğu; Sakarya Üniversitesi ilaç aktif maddeleri sentezi ders bilgi paketi; güncel hakemli medisinal kimya ve organik sentez makaleleri.",outcomes:["Farmasötik etkin maddelerin sentez rotalarını retrosentetik olarak analiz eder.","Bağ oluşumu ve fonksiyonel grup dönüşümlerini eleştirel karşılaştırır.","Seçicilik ve güvenlik ölçütlerine uygun sentez yöntemini gerekçelendirir.","Çok basamaklı sentezlerde verim ve yapı doğrulama verilerini değerlendirir.","Bir etkin madde için bilimsel gerekçeli özgün sentez stratejisi geliştirir."],weeklyTopics:["Farmasötik etkin maddeler ve doktora düzeyinde sentez problemi","Hedef molekül analizi ve retrosentetik yaklaşım","Fonksiyonel grup dönüşümleri ve kemoseçicilik","Karbon–karbon bağı oluşturan temel sentez stratejileri","Karbon–heteroatom bağı oluşumları","Palladyum katalizli çapraz eşleşme tepkimeleri","Heterohalkalı farmasötik yapıların sentez ilkeleri","Stereokimya ve enantiyoseçici sentez","Koruyucu grup stratejisinin sentez rotasına etkisi","Çok basamaklı sentezlerde sıra ve verim optimizasyonu","İlaç etkin maddelerinde saflaştırma yaklaşımları","Spektroskopik yapı doğrulama ve safsızlık değerlendirmesi","Sentez ölçeklendirme, güvenlik ve atık yönetimi","Güncel farmasötik sentez rotalarının eleştirel karşılaştırılması","Özgün sentez stratejisinin bütünleştirilmesi"]},
"KİM927":{purpose:"Karmaşık organik sentezlerde koruyucu grup seçimini işlevsel grup uyumluluğu, seçicilik, kararlılık ve uzaklaştırma koşulları bakımından eleştirel değerlendirme yetkinliği kazandırmak.",content:"Koruyucu grup stratejisinin temelleri; hidroksil, diol, tiyol, karbonil, karboksil, amin, alkin ve fosfat gruplarının korunması; ortogonal koruma, takma–çıkarma koşulları, seçicilik, atom ve adım ekonomisi ile güncel sentez uygulamaları.",methods:"Kuramsal anlatım, reaksiyon mekanizması çözümlemesi, sentez rotası karşılaştırması, literatür incelemesi ve koruyucu grup stratejisi tasarımı.",resources:"Ankara Üniversitesi Kimya Bölümü Organik Kimyada Koruyucu Gruplar ders içeriği; Greene's Protective Groups in Organic Synthesis; Kocienski, Protecting Groups; güncel hakemli organik sentez makaleleri.",outcomes:["Koruyucu grupların reaktivite ve seçicilik üzerindeki etkilerini analiz eder.","İşlevsel gruplara uygun koruma ve uzaklaştırma yöntemlerini karşılaştırır.","Ortogonal koruyucu grup stratejilerini bilimsel ölçütlerle değerlendirir.","Karmaşık sentez rotalarında güvenlik ve sürdürülebilirlik etkilerini yorumlar.","Bir hedef molekül için gerekçeli koruyucu grup stratejisi tasarlar."],weeklyTopics:["Organik sentezde koruyucu grup stratejisinin bilimsel temeli","Koruyucu grup seçiminde reaktivite, seçicilik ve kararlılık","Hidroksil gruplarının korunması","Diol grupları ve seçici koruma yaklaşımları","Tiyol gruplarının korunması","Karbonil gruplarının korunması","Karboksil grupları ve ester temelli koruma","Amin gruplarının korunması","Uç alkinlerin korunması","Fosfat gruplarının korunması","Koruyucu grupların seçici uzaklaştırılması","Ortogonal koruyucu grup stratejileri","Çok basamaklı sentezlerde koruma–uzaklaştırma sırası","Atom ekonomisi, güvenlik ve sürdürülebilirlik değerlendirmesi","Güncel organik sentezlerde koruyucu grup stratejilerinin bütünleştirilmesi"]}
};
for(const item of academics){if(generatedOverrides[item.code])Object.assign(item,generatedOverrides[item.code]);}
const commonSpecs=[`)
  .replace(/const commonSpecs=\[[\s\S]*?\];\nconst processStages=/, `const commonSpecs=[
{code:"DAN9XX",aliases:["DAN901","DAN902","DAN903","DAN904","DAN905","DAN906","DAN907","DAN908"],name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,core:[2,6,9,10,7]},
{code:"KİM9XX",aliases:["KİM901","KİM902","KİM903","KİM904","KİM905","KİM906","KİM907","KİM908"],name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,core:[1,3,5,6,7]},
{code:"KİM909",aliases:["KİM909","KİM910"],name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,core:[2,5,8,10,7]},
{code:"KİM917",aliases:["KİM917","KİM918"],name:"DOKTORA YETERLİK",theory:0,practice:0,credit:0,ects:24,core:[1,2,3,4,10]},
{code:"KİM91X",aliases:["KİM912","KİM913","KİM914","KİM915","KİM916"],name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,core:[2,6,7,9,10]}
];
const processStages=`)
  .replace(/const processStages=\{[\s\S]*?\};\nconst commonPackages=/, `const processStages={
DAN9XX:["Doktora çalışma planının oluşturulması","Kimya uzmanlık alanının sınırlandırılması","İleri literatür tarama stratejisinin değerlendirilmesi","Özgün kimyasal araştırma probleminin netleştirilmesi","Kuramsal çerçevenin eleştirel değerlendirilmesi","Deneysel veya analitik yöntem seçiminin gözden geçirilmesi","Kimyasal güvenlik ve etik gerekliliklerin değerlendirilmesi","Araştırma kayıtları ile kalite güvencesinin izlenmesi","Bulguların eleştirel ön değerlendirmesi","İleri analiz yaklaşımının gözden geçirilmesi","Bilimsel yayın planının oluşturulması","Kaynak ve araştırma bütünlüğü denetimi","Araştırma sınırlılıklarının değerlendirilmesi","Doktora ilerlemesi ve özgün katkının izlenmesi","Sonraki dönem araştırma hedeflerinin kararlaştırılması"],
KİM9XX:["Doktora tez alanının bilimsel kapsamı","Güncel kimya literatürünün eleştirel sınıflandırılması","Kuramsal ve deneysel yaklaşımların sentezlenmesi","Uluslararası literatürde araştırma boşluğunun belirlenmesi","Özgün araştırma sorularının geliştirilmesi","Hipotezlerin kimyasal ilkelerle temellendirilmesi","İleri deneysel ve analitik yöntemlerin karşılaştırılması","Araştırma tasarımının değerlendirilmesi","Ölçüm ve veri üretim yöntemlerinin geliştirilmesi","Belirsizlik, veri kalitesi ve tekrarlanabilirlik","İleri analiz seçeneklerinin karşılaştırılması","Bulguların kimyasal açıdan yorumlanması","Kimyasal güvenlik, sürdürülebilirlik ve etik riskler","Özgün katkı ve sınırlılıkların tartışılması","Kuramsal ve yöntemsel çerçevenin bütünleştirilmesi"],
KİM909:["Seminer konusunun özgünlük ve kapsam bakımından belirlenmesi","İleri araştırma sorusunun geliştirilmesi","Sistematik literatür tarama stratejisinin kurulması","Kaynakların kanıt düzeyi bakımından değerlendirilmesi","Literatürün kavramsal sınıflandırılması","Kuramsal ve deneysel kanıtların karşılaştırılması","Seminer metninin bilimsel yapısının oluşturulması","Yöntem ve bulguların eleştirel sentezi","Kimyasal gösterim, tablo ve görsellerin düzenlenmesi","Doktora düzeyinde tartışmanın yapılandırılması","Özgün kimya çıkarımlarının geliştirilmesi","Atıf ve kaynakça bütünlüğünün denetlenmesi","Akademik anlatım tasarımının geliştirilmesi","Bilimsel savunmanın yürütülmesi","Geri bildirimle nihai metnin geliştirilmesi"],
KİM917:["Yeterlik kapsamındaki kimya alanlarının belirlenmesi","İleri kimya bilgisinin sistematik incelenmesi","Kimya alt alanlarının disiplinler arası sentezi","Karmaşık kimyasal problemlerin bilimsel çözümlemesi","Özgün araştırma sorusu geliştirme","Hipotezlerin eleştirel değerlendirilmesi","Kuramsal ve deneysel modellerin karşılaştırılması","Deneysel ve analitik yöntem seçimi","Ölçüm belirsizliği ve geçerlik ölçütleri","İleri kimyasal veri çözümleme yaklaşımları","Bulguların uluslararası kimya literatürü bağlamında yorumlanması","Bilimsel etik, kimyasal güvenlik ve araştırma bütünlüğü","Çevresel ve toplumsal etkilerin değerlendirilmesi","Bilimsel argümanın yazılı yapılandırılması","Bilimsel argümanın sözlü savunulması"],
KİM91X:["Özgün kimyasal araştırma probleminin kesinleştirilmesi","İleri literatür çerçevesinin güncellenmesi","Araştırma amaç ve hipotezlerinin yapılandırılması","Yenilikçi deneysel, analitik veya kuramsal planın kesinleştirilmesi","Etik ve kimyasal güvenlik süreçlerinin tamamlanması","Veri üretim sürecinin planlanması","Araştırma kayıtları ve kalite kontrolü","Deneysel veya kuramsal çözümlemenin yürütülmesi","Verilerin düzenlenmesi ve doğrulanması","İleri analizlerin yürütülmesi","Bulguların kimyasal açıdan yorumlanması","Özgün katkının literatürle karşılaştırılması","Bilimsel yayın ve tez bölümlerinin yazımı","Tez metninin bütünlük ve etik denetimi","Doktora savunması ve bilimsel katkının sunulması"]
};
const commonPackages=`)
  .replace('const commonPackages=commonSpecs.map', 'const commonPackages=commonSpecs.map')
  .replace('contributionMatrix:matrix(d),qualityChecks', 'contributionMatrix:matrix({...d,core:s.core||d.core}),qualityChecks')
  .replaceAll('kimyaTezliCoursePackages.ts', 'kimyaDoktoraCoursePackages.ts')
  .replaceAll('kimyaCommonCoursePackages.ts', 'kimyaDoktoraCommonCoursePackages.ts')
  .replaceAll('kimyaTezliCoursePackages', 'kimyaDoktoraCoursePackages')
  .replaceAll('kimyaCommonCoursePackages', 'kimyaDoktoraCommonCoursePackages');

process.argv[2] = sourcePath;
await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
