import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root=process.cwd(), department="Türk Dili ve Edebiyatı ABD", programName="Türk Dili ve Edebiyatı", level="Tezsiz Yüksek Lisans";
const officialPath=path.join(root,"data/courses/2026-2027.json");
const allOfficial=JSON.parse(readFileSync(officialPath,"utf8"));
const official=allOfficial.filter(x=>x.department===department&&x.programName===programName&&x.level===level);
const db=new DatabaseSync(path.join(root,"local-volume/data/dbp.sqlite"),{readOnly:true});
const row=db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name=? AND level=?").get(programName,level);
const programOutcomes=JSON.parse(row?.outcomes_json||"[]");
if(programOutcomes.length!==11) throw new Error(`11 mevcut PÇ bekleniyordu; bulunan ${programOutcomes.length}`);

const projectCodes=new Set(["TDE701","TDE702","TDE7XX"]);
const profiles={
  research:["bilimsel bilgi ve araştırma etiği","araştırma probleminin yapılandırılması","nitel ve nicel araştırma yaklaşımları","kaynak, veri ve metin çözümleme","akademik yazım ve yayın etiği"],
  oral:["sözlü anlatım geleneği ve türleri","anlatıcı, icra ortamı ve dinleyici ilişkisi","sözlü anlatıların yapı ve işlevleri","alan araştırması ve metin çözümleme","sözlü kültür ürünlerinin eğitim ve aktarımı"],
  ottoman:["Osmanlı Türkçesinin yazı sistemi","ses, şekil ve söz varlığı özellikleri","gramer yapıları ve söz dizimi","farklı türlerde Osmanlı Türkçesi metinleri","çeviri yazı ve metin çözümleme ilkeleri"],
  classical:["klasik Türk şiirinin estetik ve tarihsel çerçevesi","nazım şekilleri, türler ve söz sanatları","şair, metin ve dönem ilişkisi","manzum metinlerin şerh ve tahlili","klasik edebiyat metinlerinin karşılaştırmalı yorumu"],
  language:["Türkçenin dil bilgisel yapısı","ses ve şekil bilgisi süreçleri","sözcük bilgisi ve söz dizimi","dil verilerinin sınıflandırılması","Türkçe örneklerin bilimsel çözümlemesi"],
  mythology:["Türk mitolojisinin kavramsal çerçevesi","mit, ritüel ve sembol ilişkisi","Türk destan geleneği ve tipleri","mitolojik unsurların metinlerdeki işlevi","mit ve destanların kültürel sürekliliği"],
  history:["Türk dilinin tarihsel dönemleri","tarihî lehçe ve yazı dilleri","ses, şekil ve söz varlığı değişmeleri","tarihî metinlerin karşılaştırılması","Türk dilinin gelişimindeki süreklilik ve dönüşüm"],
  comparative:["karşılaştırmalı edebiyatın kuramsal temelleri","metinler arası ilişkiler ve etkilenme","tema, tür ve biçim karşılaştırmaları","ulusal ve dünya edebiyatı bağlamları","karşılaştırmalı çözümleme ve yorum"],
  linguistics:["dilbilimin temel kavram ve kuramları","dilin ses, biçim ve söz dizimi düzeyleri","anlam, kullanım ve söylem ilişkileri","dil verilerinde çözümleme yöntemleri","dilbilimsel bulguların yorumlanması"],
  theory:["edebiyat biliminin temel kavramları","edebî tür, biçim ve anlatım teknikleri","edebiyat kuramları ve eleştiri yaklaşımları","kuramsal kavramların metne uygulanması","edebî yorumların karşılaştırılması"],
  western:["Batı edebiyatındaki düşünsel ve estetik dönüşümler","edebî akımların tarihsel koşulları","akımların temel kavram ve temsilcileri","akımların tür ve biçim üzerindeki etkileri","Türk ve Batı edebiyatları arasındaki etkileşim"],
  culture:["dil ile kültür arasındaki karşılıklı ilişki","dilsel göstergeler ve kültürel anlam","kimlik, bellek ve söylem","kültürel verilerin dil üzerinden çözümlenmesi","dil ve kültür araştırmalarında güncel yaklaşımlar"],
  poetry:["şiir çözümlemesinin kavramsal araçları","ses, ritim, imge ve söz sanatları","şiirde yapı, tema ve söyleyiş","farklı dönemlerden şiir örneklerinin tahlili","şiir yorumlarının gerekçelendirilmesi"],
};
const fold=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const sentence=s=>{const t=String(s||"").replace(/\s+/g," ").trim();if(!t||t!==t.toLocaleUpperCase("tr-TR"))return t;const l=t.toLocaleLowerCase("tr-TR");return l[0].toLocaleUpperCase("tr-TR")+l.slice(1);};
const cleanInstructor=s=>(s||"Atama Bekliyor").replace(/^Yrd\.?\s*Doç\.?\s*Dr\.?/iu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+|\b\S+@\S+\b/giu," ").replace(/\s+/g," ").trim();
function profileFor(name){const n=fold(name);if(n.includes("bilimsel arastirma"))return profiles.research;if(n.includes("sozlu anlatim"))return profiles.oral;if(n.includes("osmanli turkcesi"))return profiles.ottoman;if(n.includes("eski turk edebiyati"))return profiles.classical;if(n.includes("ses")||n.includes("sozcuk")||n.includes("soz dizimi"))return profiles.language;if(n.includes("mitoloji")||n.includes("destan"))return profiles.mythology;if(n.includes("gelisim evreleri"))return profiles.history;if(n.includes("karsilastirmali"))return profiles.comparative;if(n.includes("dilbilim"))return profiles.linguistics;if(n.includes("terim")||n.includes("kuram"))return profiles.theory;if(n.includes("bati edebiyati")||n.includes("edebi akim"))return profiles.western;if(n.includes("dil ve kultur"))return profiles.culture;if(n.includes("siir"))return profiles.poetry;return profiles.theory;}
const checklist=["Ders adı ve kodları doğrulandı mı?","Tüm OBS bağlantıları gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const qualityChecks=()=>checklist.map((item,i)=>({item,status:[1,19,20].includes(i)?"Doğrulanmalı":[3,5,6,7,8,9,10,11,12,13,14,15,16,18].includes(i)?"Revize Edildi":"Uygun",...([1,19,20].includes(i)?{note:"Kesin OBS ders paketi bağlantısı bulunmadığından resmî müfredat kimliği korunmuş; eksik akademik alanlar handoff ölçütleri ve LEE_DBP'deki güncel 11 PÇ temelinde öneri niteliğinde tamamlanmıştır."}:{})}));
function matrix(kind){let primary=[0,1,2,3,4,5,7,9],secondary=[6,8,10];if(kind===profiles.research){primary=[2,3,6,7,8,9,10];secondary=[0,1,4,5];}else if(kind===profiles.language||kind===profiles.linguistics){primary=[0,3,5,7,9];secondary=[1,2,4,6,8,10];}else if(kind===profiles.mythology||kind===profiles.culture||kind===profiles.comparative){primary=[1,2,4,5,7,10];secondary=[0,3,6,8,9];}return Array.from({length:5},(_,r)=>({outcome:`DÖÇ${r+1}`,values:programOutcomes.map((_,c)=>primary.includes(c)?[4,4,5,4,5][r]:secondary.includes(c)?[2,3,2,3,2][r]:[1,2,1,2,1][r])}));}
const cap=s=>s.charAt(0).toLocaleUpperCase("tr-TR")+s.slice(1);
function weeks(p){return [`${cap(p[0])}: kapsam ve temel kavramlar`,`${cap(p[0])}: tarihsel ve kuramsal çerçeve`,`${cap(p[0])}: kaynak ve metin türleri`,`${cap(p[1])}: temel ilkeler`,`${cap(p[1])}: örneklerin çözümlenmesi`,`${cap(p[1])}: farklı yaklaşımların karşılaştırılması`,`${cap(p[2])}: kavramsal yapı`,`${cap(p[2])}: metin veya dil verilerine uygulama`,`${cap(p[2])}: bulguların yorumlanması`,`${cap(p[3])}: yöntem ve teknikler`,`${cap(p[3])}: seçilmiş örneklerin incelenmesi`,`${cap(p[3])}: bağlam ve işlev ilişkisi`,`${cap(p[4])}: güncel tartışmalar`,`${cap(p[4])}: etik ve kültürel boyutlar`,`${cap(p[4])}: bütüncül akademik değerlendirme`];}
const assessments=[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}];
const workload=ects=>[{name:"Ders Süresi",count:15,hours:3,total:45},{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:6,total:90},{name:"Ara Sınav Hazırlığı",count:1,hours:20,total:20},{name:"Yarıyıl Sonu Sınavı Hazırlığı",count:1,hours:ects*30-155,total:ects*30-155}];
const academicRows=official.filter(x=>!projectCodes.has(x.code)&&!/DANIŞMANLIK|UZMANLIK ALAN/iu.test(x.name));
const academic=academicRows.map(course=>{const name=sentence(course.name),p=profileFor(name);return {code:course.code,name,department,programName,language:"Türkçe",level,teachingMode:"Yüz Yüze",instructor:cleanInstructor(course.instructor),theory:Number(course.theory)||3,practice:Number(course.practice)||0,credit:Number(course.credit)||3,ects:Number(course.ects)||6,prerequisites:"Yok",purpose:`Öğrencinin ${p[0]}, ${p[1]} ve ${p[3]} alanlarında ileri düzey çözümleme, karşılaştırma ve yorumlama becerisi geliştirmesini sağlamak.`,content:`Ders; ${p.join(", ")} konularını Türk dili ve edebiyatı araştırmalarının tarihsel, kültürel ve kuramsal bağlamlarıyla ilişkilendirerek ele alır.`,methods:"Kuramsal anlatım, yönlendirilmiş tartışma, kaynak ve metin incelemesi, karşılaştırmalı çözümleme, bireysel çalışma ve yapılandırılmış geri bildirim.",resources:"Türk Dil Kurumu yayınları ve sözlükleri; Türkiye Yazma Eserler Kurumu Başkanlığı koleksiyonları; alanın temel başvuru eserleri; TÜBİTAK ULAKBİM TR Dizin ve güncel hakemli Türk dili ve edebiyatı araştırmaları.",sdgs:["4","10","11"],outcomes:[`${cap(p[0])} ile ilgili ileri kavramları analiz eder.`,`${cap(p[1])} kapsamında kaynak ve metinleri eleştirel değerlendirir.`,`${cap(p[2])} ile ilişkili dilsel veya edebî örnekleri karşılaştırır.`,`${cap(p[3])} için uygun çözümleme yaklaşımını uygular.`,`${cap(p[4])} temelinde gerekçeli akademik yorum geliştirir.`],weeklyTopics:weeks(p),assessments,workloads:workload(Number(course.ects)||6),contributionMatrix:matrix(p),qualityChecks:qualityChecks(),publicQualityChecklist:false};});
const project={code:"TDE7XX",aliases:["TDE701","TDE702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin Türk dili ve edebiyatı alanındaki ileri bilgi, kaynak kullanma ve çözümleme becerilerini mesleki bir problem üzerinde bütünleştirerek bilimsel ve etik ölçütlere uygun bir bitirme projesi yürütmesini sağlamak.",content:"Proje probleminin belirlenmesi, alan yazını ve kaynakların değerlendirilmesi, yöntem ile çalışma planının geliştirilmesi, dilsel veya edebî verilerin çözümlenmesi, sonuçların tarihsel ve kültürel bağlamda yorumlanması ve projenin akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışman görüşmesi, kaynak ve metin incelemesi, dilsel veya edebî çözümleme, akademik yazım ve yapılandırılmış geri bildirim.",resources:"Enstitü bitirme projesi ilkeleri; Türk Dil Kurumu ve Türkiye Yazma Eserler Kurumu Başkanlığı kaynakları; konuya ilişkin birincil metinler ve güncel hakemli araştırmalar.",sdgs:["4","10","11"],outcomes:["Türk dili veya edebiyatı alanında uygulanabilir bir proje problemi yapılandırır.","Proje problemine ilişkin birincil ve ikincil kaynakları eleştirel değerlendirir.","Projenin amacına uygun yöntem ve çalışma planı geliştirir.","Dilsel veya edebî bulguları tarihsel ve kültürel bağlamda yorumlar.","Bitirme projesini bilimsel yazım ve etik ilkelerine uygun raporlar."],weeklyTopics:["Proje alanının ve kapsamının belirlenmesi","Dilsel veya edebî problemin sınırlandırılması","Amaç ve araştırma sorularının geliştirilmesi","Alan yazını tarama stratejisinin oluşturulması","Birincil metin ve kaynakların belirlenmesi","Kaynakların eleştirel değerlendirilmesi","Kuramsal çerçeve ile yöntemin geliştirilmesi","Çalışma planının ve çözümleme birimlerinin yapılandırılması","Metin veya dil verilerinin toplanması","Dilsel veya edebî verilerin çözümlenmesi","Bulguların tarihsel ve kültürel bağlamda yorumlanması","Bulguların alan yazınıyla karşılaştırılması","Proje raporunun yapılandırılması","Bilimsel yazım, atıf ve etik uygunluk denetimi","Bitirme projesinin teslimi ve değerlendirilmesi"],assessments:[{name:"Başarılı / Başarısız",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışman Görüşmeleri",count:15,hours:2,total:30},{name:"Kaynak ve Metin İncelemesi",count:15,hours:20,total:300},{name:"Çözümleme ve Raporlama",count:15,hours:36,total:540},{name:"Nihai Düzenleme ve Teslim",count:1,hours:30,total:30}],contributionMatrix:matrix(profiles.research),qualityChecks:qualityChecks(),publicQualityChecklist:false};
if(academic.length!==23) throw new Error(`23 akademik ders bekleniyordu; bulunan ${academic.length}`);
const forbidden=/(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|arasınav|vize|yarıyıl\s+sonu\s+sınavı|final)/iu;
for(const c of [...academic,project]){if(c.weeklyTopics.length!==15||new Set(c.weeklyTopics.map(fold)).size!==15)throw new Error(`${c.code}: 15 benzersiz hafta yok`);if(c.code!=="TDE7XX"&&c.weeklyTopics.some(x=>forbidden.test(x)))throw new Error(`${c.code}: yasak başlık`);if(c.outcomes.length!==5||c.contributionMatrix.some(r=>r.values.length!==11||r.values.some(v=>v<1||v>5)))throw new Error(`${c.code}: DÖÇ-PÇ`);if(c.workloads.reduce((s,x)=>s+x.total,0)!==c.ects*30||!c.workloads.every(x=>Number.isInteger(x.hours*2)))throw new Error(`${c.code}: iş yükü`);if(c.qualityChecks.length!==21||c.publicQualityChecklist!==false)throw new Error(`${c.code}: kontrol`);}
const emit=(file,name,value)=>writeFileSync(path.join(root,"lib/data",file),`// Türk Dili ve Edebiyatı tezsiz resmî müfredatı ve mevcut 11 LEE_DBP PÇ'si temel alınmıştır; program profili değiştirilmemiştir.\nimport type { CoursePackage } from "./coursePackages";\n\nexport const ${name}: CoursePackage[] = ${JSON.stringify(value,null,2)};\n`);
emit("turkDiliEdebiyatiTezsizCoursePackages.ts","turkDiliEdebiyatiTezsizCoursePackages",academic);
emit("turkDiliEdebiyatiTezsizCommonCoursePackages.ts","turkDiliEdebiyatiTezsizCommonCoursePackages",[project]);
const normalized=[...academicRows.map(x=>({...x,name:sentence(x.name),instructor:x.instructor?cleanInstructor(x.instructor):undefined})),{academicYear:"2026-2027",programCode:"",department,programName,level,code:"TDE7XX",name:"Bitirme Projesi",type:"Zorunlu",credit:0,ects:30,theory:0,practice:0,term:"Güz",instructor:"Öğrencinin Danışmanı",status:"İncelemede",source:"official_excel"}];
const rest=allOfficial.filter(x=>!(x.department===department&&x.programName===programName&&x.level===level));
const at=rest.findIndex(x=>x.department===department&&x.programName===programName&&x.level==="Tezli Yüksek Lisans");rest.splice(at<0?rest.length:at,0,...normalized);writeFileSync(officialPath,`${JSON.stringify(rest,null,2)}\n`);
console.log(JSON.stringify({official:official.length,academic:academic.length,common:1,outcomes:programOutcomes.length}));
