import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="felsefe ve din bilimleri tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["Felsefe ve din bilimlerindeki ileri düzey bilgileri analiz eder.","Alanına özgü araştırma yöntemlerini uygular.","Felsefi ve dinî kavram ve kuramları karşılaştırır ve değerlendirir.","Bilimsel kaynakları eleştirel biçimde değerlendirir ve kullanır.","Dinî ve felsefi problemleri disiplinler arası yaklaşımla analiz eder.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Bilimsel bulguları yazılı ve sözlü olarak sunar.","Sosyal bilimlerin verilerini alan çalışmalarına bütünleştirir.","Bilimsel araştırma ve yayın etiği ilkelerini uygular.","Din ve düşünce olgularını toplumsal sorumluluk açısından değerlendirir.","Güncel bilimsel ve düşünsel gelişmeleri izler ve çalışmalarına uygular."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Felsefe ve Din Bilimleri ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/psikoloji|psikanaliz|psiko-sosyal|kimlik/u.test(n))return{label:"din psikolojisi",core:[1,3,5],sdgs:["3","4","10"],terms:["din psikolojisinin kavramsal çerçevesi","tarihsel ve kuramsal yaklaşımlar","dindarlık ve kişilik","dinî gelişim","dinî başa çıkma","kimlik ve anlam","psikolojik uyum","güncel din psikolojisi araştırmaları"]};
 if(/sosyoloji|toplum|kurum|devlet|ekonomi|medya|hareket/u.test(n))return{label:"din sosyolojisi",core:[3,5,8],sdgs:["4","10","16"],terms:["din ve toplum ilişkisi","klasik sosyolojik yaklaşımlar","modernleşme ve sekülerleşme","dinî kurumlar","kimlik ve toplumsal değişim","din ve kamusal alan","saha araştırması yaklaşımları","güncel toplumsal olgular"]};
 if(/egitim|ogretim|ogrenme/u.test(n))return{label:"din eğitimi",core:[1,5,10],sdgs:["4","10","16"],terms:["din eğitiminin kavramsal temelleri","öğrenme kuramları","dinî gelişim ve öğrenme","öğretim programları","aile ve yaygın din eğitimi","değerler eğitimi","eğitim tarihi belgeleri","güncel din eğitimi sorunları"]};
 if(/dinler tarihi|yahudi|kilise|halk inan|turk dini/u.test(n))return{label:"dinler tarihi",core:[3,4,11],sdgs:["4","10","16"],terms:["dinler tarihinin kavramları","tarihsel kaynaklar","karşılaştırmalı yöntem","dinî geleneklerin oluşumu","metin ve ritüel çözümlemesi","dinler arası etkileşim","yerel inanışlar","güncel dinler tarihi tartışmaları"]};
 if(/felsefe|ahlak|tanri|kelam|gazali/u.test(n))return{label:"İslam felsefesi ve din felsefesi",core:[1,3,5],sdgs:["4","16","17"],terms:["felsefi kavram çözümlemesi","klasik düşünce kaynakları","akıl ve vahiy ilişkisi","varlık ve bilgi problemleri","Tanrı ve insan ilişkisi","ahlak ve siyaset düşüncesi","felsefe-kelam etkileşimi","güncel felsefi tartışmalar"]};
 if(/metod|arastirma|bilimsel/u.test(n))return{label:"sosyal bilimlerde araştırma",core:[2,4,6],sdgs:["4","16","17"],terms:["bilimsel bilgi ve araştırma problemi","nitel ve nicel desenler","metin ve söylem çözümlemesi","örnekleme ve veri toplama","veri çözümleme","geçerlik ve güvenirlik","araştırma etiği","bilimsel raporlama"]};
 return{label:"felsefe ve din bilimleri",core:[1,3,5],sdgs:["4","10","16"],terms:["temel kavram ve kuramlar","tarihsel kaynaklar","karşılaştırmalı yaklaşım","metin çözümlemesi","disiplinler arası yorum","araştırma yöntemleri","etik ve toplumsal sorumluluk","güncel düşünsel tartışmalar"]};};
const generatedWeeks=(name,d)=>{const s=prose(name);return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbidden=/\b(quiz|kısa sınav|odev|ödev|proje|sunum|konu tekrarı|genel tekrar|ara sınav|vize|final|yarıyıl sonu)\b/iu;
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|FDB80[1-8]|BES80[1-2])$/u;
const academic=official.filter((o)=>!common.test(o.code)).map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbidden.test(clean(x[1]))).map((x)=>x[1])),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Felsefe ve Din Bilimleri ABD",programName:"Felsefe ve Din Bilimleri",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:detail(c,"dersin amaci")||`${cap(sub)} alanındaki temel metinleri ve ileri kuramsal yaklaşımları analiz etme, karşılaştırma ve bilimsel ölçütlerle yorumlama yetkinliği kazandırmak.`,content:detail(c,"dersin icerigi")||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:detail(c,"dersin yontem ve teknikleri")||"Kuramsal anlatım, kaynak ve metin çözümlemesi, karşılaştırmalı tartışma ve araştırma bulgularının değerlendirilmesi.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"Felsefe ve din bilimleri alanındaki temel kaynaklar; güncel hakemli alan literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin felsefe ve din bilimleri alanındaki lisansüstü araştırmasını bilimsel yöntem, etik ilkeler ve akademik takvim doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, literatür taraması, araştırma problemi, yöntem seçimi, etik, ilerleme izlemesi ve bilimsel raporlama.",stages:["Akademik çalışma planı","Uzmanlık alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Araştırma soruları ve hedefler","Yöntem seçeneklerinin değerlendirilmesi","Kaynak ve veri planı","Araştırma ve yayın etiği","İlerleme kayıtlarının değerlendirilmesi","Çözümleme yaklaşımının gözden geçirilmesi","Bulguların yorumlanması","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Sonraki dönem çalışma planı"]},
{code:"FDB8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili felsefe ve din bilimleri literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal ve yöntemsel altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü güncel literatür, temel metinler, kavram ve kuramlar, araştırma problemi, yöntem seçimi, yorumlama, etik ve akademik yazım.",stages:["Tez alanının bilimsel kapsamı","Temel ve güncel kaynaklar","Kuramsal çerçeve ve kavramlar","Araştırma boşluğunun tanımlanması","Araştırma sorularının geliştirilmesi","Tarihsel bağlamın kurulması","Karşılaştırmalı yaklaşım seçenekleri","Metin ve veri çözümleme yöntemleri","Kaynak eleştirisi","Bulguların kuramsal yorumu","Alternatif görüşlerin karşılaştırılması","Disiplinler arası bağlantılar","Etik ve toplumsal sorumluluk","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"FDB806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Felsefe ve din bilimleri alanındaki bilimsel bir problemi literatüre dayalı inceleme, akademik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, problemin yapılandırılması, kavramsal ve tarihsel kanıtların sentezi, bilimsel yazım, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Literatür tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Kavram ve kuramların karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve kanıtların sentezi","Tarihsel bağlamın yapılandırılması","Bilimsel tartışmanın geliştirilmesi","Sonuç ve alan çıkarımları","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel savununun yapılandırılması","Geri bildirimle nihai düzenleme"]},
{code:"BES801",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Felsefe ve din bilimleri araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, çözümleme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, sosyal bilim araştırma desenleri, metin ve saha araştırması, veri toplama ve çözümleme, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve alan araştırması","Araştırma problemi ve soruları","Nitel araştırma desenleri","Nicel araştırma desenleri","Tarihsel ve karşılaştırmalı yöntem","Metin ve söylem çözümlemesi","Örnekleme ve veri toplama","Geçerlik ve güvenirlik","Veri çözümleme yaklaşımları","Bulguların yorumlanması","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"FDB81X",name:"YÜKSEK LİSANS TEZİ",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin felsefe ve din bilimleri alanında özgün bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün araştırma problemi, literatür sentezi, kuramsal çerçeve, yöntem, kaynak ve veri çözümlemesi, bulguların yorumu, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve araştırma sorularının yapılandırılması","Kuramsal çerçevenin geliştirilmesi","Yöntem ve çözümleme planı","Etik gereklilikler","Kaynak veya veri toplama","Veri ve kaynakların düzenlenmesi","Çözümlemelerin yürütülmesi","Bulguların kuramsal yorumu","Bulguların literatürle karşılaştırılması","Sonuçların toplumsal açıdan değerlendirilmesi","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}
];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="FDB806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="BES801"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Felsefe ve Din Bilimleri ABD",programName:"Felsefe ve Din Bilimleri",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="BES801"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="BES801"?"Prof. Dr. HÜSNÜ EZBER BODUR":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, matematiksel modelleme, teknik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"Felsefe ve din bilimleri alanındaki temel kaynaklar; güncel hakemli alan literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","felsefeDinTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const felsefeDinTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","felsefeDinCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const felsefeDinCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));



