import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
const sourcePath=process.argv[2]||process.env.BOLOGNA_DERS_JSON;if(!sourcePath)throw new Error("Kaynak JSON yolu gerekli.");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();const unique=(a)=>[...new Set(a.map(clean).filter(Boolean))];
const prose=(v)=>clean(v).toLocaleLowerCase("tr-TR");const cap=(v)=>v?`${v[0].toLocaleUpperCase("tr-TR")}${v.slice(1)}`:v;
const naturalCase=(v="")=>{const text=clean(v);if(!text||text!==text.toLocaleUpperCase("tr-TR"))return text;return cap(text.toLocaleLowerCase("tr-TR")).replace(/^Iso\b/u,"ISO")};
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;const program=data.programs.find((p)=>fold(p.name)==="harita muhendisligi tezli yuksek lisans");if(!program)throw new Error("Program bulunamadı.");
const pcs=["Harita mühendisliğindeki ileri düzey bilgileri uygular.","Mekânsal ve jeodezik problemleri analiz eder ve modeller.","Harita mühendisliği problemlerine yenilikçi çözümler geliştirir.","Ölçme, analiz ve modelleme yöntemlerini seçer ve uygular.","Mekânsal verileri analiz eder ve yorumlar.","Bağımsız bilimsel araştırma tasarlar, yürütür ve raporlar.","Disiplinler arası ekiplerde liderlik yapar ve sorumluluk alır.","Bilimsel ve teknik çalışmalarını etkili biçimde sunar.","Bilimsel, mesleki ve etik ilkeleri uygular.","Harita mühendisliği çözümlerini toplumsal ve çevresel etkileriyle değerlendirir.","Güncel mekânsal teknolojileri izler ve çalışmalarına uygular."];
const raw=readFileSync(path.join(process.cwd(),"lib","data","officialCourses.ts"),"utf8");const gs=(l,k)=>l.match(new RegExp(`${k}: "([^"]*)"`))?.[1]||"";const gn=(l,k)=>Number(l.match(new RegExp(`${k}: ([0-9.]+)`))?.[1]||0);
const official=raw.split(/\r?\n/).filter((l)=>l.includes('department: "Harita Mühendisliği ABD"')&&l.includes('level: "Tezli Yüksek Lisans"')).map((l)=>({code:gs(l,"code"),name:gs(l,"name"),type:gs(l,"type"),theory:gn(l,"theory"),practice:gn(l,"practice"),credit:gn(l,"credit"),ects:gn(l,"ects"),term:gs(l,"term"),instructor:gs(l,"instructor")}));
const byId=new Map(data.courses.map((c)=>[c.id,c]));const assignments=data.programCourses.filter((a)=>a.program_id===program.id).map((assignment)=>({assignment,course:byId.get(assignment.course_id)})).filter((x)=>x.course);const byCode=new Map(assignments.map((x)=>[x.course.code,x]));
const cells=(r)=>Array.isArray(r)?r.map(clean):[];const table=(c,heads)=>(c?.package?.tables||[]).find((t)=>{const h=cells(t.rows?.[0]).map(fold);return heads.every((x)=>h.some((v)=>v.includes(x)))});
const detail=(c,label)=>{const t=(c?.package?.tables||[]).find((x)=>fold(x.title)==="dersin detaylari"&&x.rows?.some((r)=>fold(r?.[0])===label));return clean(t?.rows?.find((r)=>fold(r?.[0])===label)?.[1])};
const domain=(name)=>{const n=fold(name);
 if(/cografi|cbs|mekansal|istatistik|programlama/u.test(n))return{label:"coğrafi bilgi sistemleri ve mekânsal analiz",core:[2,4,5],sdgs:["9","11","13"],terms:["mekânsal veri modelleri","koordinat ve referans sistemleri","veri tabanı tasarımı","mekânsal sorgulama","çok ölçütlü karar analizi","mekânsal istatistik","model doğrulama","karar destek uygulamaları"]};
 if(/fotogrametri|goruntu|3b|hava araci|uzaktan algilama/u.test(n))return{label:"fotogrametri ve uzaktan algılama",core:[3,4,11],sdgs:["9","11","13"],terms:["algılayıcı ve görüntü geometrisi","radyometrik ve geometrik düzeltme","görüntü eşleme","sayısal yüzey modelleri","nesne çıkarımı","sınıflandırma yöntemleri","doğruluk analizi","üç boyutlu mekânsal ürünler"]};
 if(/gnss|jeodezi|deformasyon|olcme|zaman ser/u.test(n))return{label:"jeodezi ve konum belirleme",core:[2,4,5],sdgs:["9","11","13"],terms:["jeodezik referans sistemleri","GNSS gözlemleri","ölçme hataları ve dengeleme","zaman serisi bileşenleri","deformasyon modelleri","atmosferik etkiler","belirsizlik analizi","ölçme sonuçlarının yorumlanması"]};
 if(/tasinmaz|kadastro|kamulastirma|imar|arazi|kentsel|sehir|kirsal/u.test(n))return{label:"arazi ve taşınmaz yönetimi",core:[2,3,10],sdgs:["11","16","17"],terms:["mülkiyet ve kadastro sistemi","arazi yönetimi politikaları","taşınmaz değerleme yöntemleri","imar ve planlama mevzuatı","kamulaştırma süreçleri","kentsel ve kırsal düzenleme","mekânsal karar ölçütleri","toplumsal ve çevresel etkiler"]};
 if(/arastirma|bilimsel/u.test(n))return{label:"bilimsel harita mühendisliği araştırmaları",core:[5,6,9],sdgs:["4","9","17"],terms:["araştırma problemi","bilimsel araştırma tasarımı","mekânsal veri kaynakları","örnekleme ve ölçme planı","veri kalite güvencesi","analiz ve model doğrulama","bilimsel raporlama","araştırma ve yayın etiği"]};
 return{label:"ileri harita mühendisliği",core:[1,3,11],sdgs:["9","11","13"],terms:["harita mühendisliği probleminin tanımlanması","mekânsal veri gereksinimleri","ölçme ve veri üretim yöntemleri","koordinat ve referans sistemleri","analiz ve modelleme","doğruluk ve belirsizlik","toplumsal ve çevresel etkiler","güncel mekânsal teknolojiler"]};};
const generatedWeeks=(name,d)=>{const s=prose(name).replace(/projeleri?/giu,"çalışmaları").replace(/sunumu?/giu,"anlatımı");return unique([`${cap(s)}: kapsam ve temel kavramlar`,...d.terms.map(cap),`${cap(s)} alanında planlama`,`${cap(s)} alanında risk ve etik`,`${cap(s)} uygulamalarında paydaşlar`,`${cap(s)} uygulamalarında kalite ve sürdürülebilirlik`,`${cap(s)} alanındaki güncel yaklaşımlar`,`${cap(s)} bilgilerinin bütünleştirilmesi`]).filter((x)=>!forbiddenWeekTopic(x)).slice(0,15)};
const outcomes=(name,d)=>{const s=prose(name);return[`${cap(s)} kapsamındaki temel ve ileri yaklaşımları analiz eder.`,`${cap(d.label)} alanındaki uygulamaları karşılaştırır.`,`${cap(s)} için sürdürülebilir bir uygulama yaklaşımı geliştirir.`,`${cap(s)} faaliyetlerindeki etkileri ve riskleri değerlendirir.`,`${cap(s)} bulgularını etik ve bilimsel ölçütlerle yorumlar.`]};
const matrix=(d)=>{const p=[[1,d.core[0]],[2,5,d.core[1]],[1,5,d.core[0]],[4,7,d.core[1]],[3,7,d.core[2]]].map((x)=>[...new Set(x)]),s=[[2,11],[1,6,11],[2,4,9],[2,5,6,9],[5,9,10,11]];return p.map((t,r)=>({outcome:`DÖÇ${r+1}`,values:pcs.map((_,i)=>t.includes(i+1)?(r===2?5:4):s[r].includes(i+1)?3:1+(i+r)%2)}))};
const forbiddenWeekTopic=(value)=>["quiz","kisa sinav","odev","proje","sunum","konu tekrari","genel tekrar","ara sinav","arasinav","arasınav","vize","final","yariyil sonu"].some((term)=>fold(value).includes(term));
const assessments=(c)=>{const t=table(c,["yariyil calismalari","katki"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="degerlendirme olcutleri");const r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Math.min(15,Number(x[1])||1),weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,aa)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of aa){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let rem=target-r.reduce((x,y)=>x+y.total,0),out=Math.max(0,Math.floor(rem/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:out,total:out*15});rem=target-r.reduce((x,y)=>x+y.total,0);if(rem)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:rem,total:rem});return r};
const checkItems=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=(src)=>checkItems.map((item,i)=>({item,status:!src&&i===1?"Doğrulanmalı":[3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun"}));
const common=/^(DAN80[1-4]|HRM80[1-8]|HRM809)$/u;
const academic=official.filter((o)=>!common.test(o.code)).map((o)=>{const src=byCode.get(o.code),c=src?.course,name=c?.name||o.name.replace(/\.\.\.$/u,"").trim(),d=domain(name),sub=prose(name),has=Boolean(c?.source_url);const wt=table(c,["hafta","konu"])||(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders konulari"),sw=unique((wt?.rows||[]).slice(1).filter((x)=>x?.[1]&&!forbiddenWeekTopic(clean(x[1]))).map((x)=>naturalCase(x[1]))),weeks=unique([...sw,...generatedWeeks(name,d)]).slice(0,15);const aa=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),ects=Number(src?.assignment?.ects??o.ects??6)||6;const rt=(c?.package?.tables||[]).find((x)=>fold(x.title)==="ders kaynaklari");return{code:o.code,name,department:"Harita Mühendisliği ABD",programName:"Harita Mühendisliği",language:c?.language||"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",theory,practice,credit:Number(src?.assignment?.local_credit??o.credit??theory),ects,prerequisites:"Yok",instructor:detail(c,"dersi verenler")||o.instructor||"Atama Bekliyor",purpose:naturalCase(detail(c,"dersin amaci"))||`${cap(sub)} alanındaki ileri yaklaşımları bilimsel ölçütlerle analiz etme ve harita mühendisliği uygulamalarına aktarma yetkinliği kazandırmak.`,content:naturalCase(detail(c,"dersin icerigi"))||`${cap(sub)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:naturalCase(detail(c,"dersin yontem ve teknikleri"))||"Kuramsal anlatım, bilimsel kaynak incelemesi, örnek olay çözümlemesi, uygulama verilerinin değerlendirilmesi ve akademik tartışma.",resources:(rt?.rows||[]).map((x)=>cells(x).filter(Boolean).join(": ")).join("; ")||"Harita mühendisliği ve mekânsal bilgi teknolojileri alanındaki temel kaynaklar; güncel hakemli alan literatürü.",sdgs:d.sdgs,outcomes:outcomes(name,d),weeklyTopics:weeks,assessments:aa,workloads:workloads(ects,theory,practice,aa),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(has),publicQualityChecklist:false}});
const specs=[
{code:"DAN8XX",name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,purpose:"Öğrencinin harita mühendisliği araştırmasını bilimsel yöntem, sürdürülebilirlik ve etik ilkeler doğrultusunda planlamasına ve izlemesine rehberlik etmek.",content:"Akademik planlama, harita mühendisliği literatürü, araştırma problemi, yöntem, saha etiği, veri yönetimi, ilerleme ve raporlama.",stages:["Akademik çalışma planı","Harita mühendisliği araştırma alanının sınırlandırılması","Literatür tarama stratejisi","Araştırma probleminin netleştirilmesi","Sürdürülebilirlik ve etik gereklilikler","Araştırma tasarımının değerlendirilmesi","Saha ve veri toplama planı","Araştırma kayıtlarının kontrolü","Bulguların ön değerlendirmesi","Analiz yaklaşımının gözden geçirilmesi","Bilimsel yazım planı","Kaynak ve atıf denetimi","Araştırma sınırlılıkları","Akademik ilerleme izlemesi","Sonraki dönem çalışma planı"]},
{code:"HRM8XX",name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,purpose:"Öğrencinin tez konusu ile ilişkili ileri harita mühendisliği literatürünü eleştirel değerlendirmesini ve araştırmasının kuramsal-yöntemsel altyapısını derinleştirmesini sağlamak.",content:"Tez alanına özgü harita mühendisliği ve mekânsal bilgi teknolojileri literatürü, araştırma problemi, kuramsal çerçeve, ölçme ve modelleme yöntemleri, veri kalitesi, sürdürülebilirlik ve etik.",stages:["Tez alanının bilimsel kapsamı","İleri harita mühendisliği literatürü","Kuramsal yaklaşımlar","Araştırma boşluğunun tanımlanması","Araştırma soruları","Kuramsal varsayımlar","Deneysel araştırma desenleri","Örnekleme yaklaşımı","Saha, ölçme ve mekânsal veri kaynakları","Veri kalite ölçütleri","Analiz seçenekleri","Bulguların harita mühendisliği açısından yorumlanması","Mesleki etik, veri güvenliği ve çevresel riskler","Araştırma sınırlılıkları","Kuramsal ve yöntemsel bütünleştirme"]},
{code:"HRM806",name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,purpose:"Harita mühendisliği alanındaki bilimsel bir problemi literatüre dayalı inceleme, akademik metne dönüştürme ve bilimsel ortamda savunma becerisi kazandırmak.",content:"Literatür tarama, araştırma problemi, kanıt sentezi, bilimsel metin, akademik anlatım ve tartışma.",stages:["Seminer konusunun belirlenmesi","Araştırma sorusunun geliştirilmesi","Literatür tarama stratejisi","Kaynak güvenilirliğinin değerlendirilmesi","Literatürün tematik sınıflandırılması","Harita mühendisliği kanıtlarının karşılaştırılması","Metin iskeletinin oluşturulması","Yöntem ve bulguların sentezi","Tablo ve görsellerin düzenlenmesi","Bilimsel tartışmanın yapılandırılması","Sonuç ve çıkarımlar","Atıf ve kaynakça denetimi","Akademik anlatım tasarımı","Bilimsel anlatımın uygulanması","Geri bildirimle nihai düzenleme"]},
{code:"HRM809",name:"BİLİMSEL ARAŞTIRMA YÖNTEMLERİ VE YAYIN ETİĞİ",theory:3,practice:0,credit:3,ects:6,purpose:"Harita mühendisliği araştırmalarını bilimsel yöntem ve yayın etiği ilkelerine uygun tasarlama, yürütme, analiz etme ve raporlama yeterliliği kazandırmak.",content:"Araştırma problemi, deneysel tasarım, örnekleme ve numune hazırlama, analitik veri toplama, istatistiksel çözümleme, yöntem doğrulama, bilimsel yazım, araştırma bütünlüğü ve yayın etiği.",stages:["Bilimsel bilgi ve harita mühendisliği araştırması","Araştırma problemi ve hipotez","Deneysel araştırma tasarımları","Değişken ve kontrol grupları","Örnekleme ve numune hazırlama","Analitik yöntem seçimi","Ölçüm güvenilirliği ve belirsizlik","İstatistiksel veri analizi","Yöntem doğrulama ve kalite güvencesi","Bulguların mühendislik açısından yorumlanması","Bilimsel makale yapısı","Kaynak ve atıf ilkeleri","Araştırma bütünlüğü","Yayın etiği ihlalleri","Araştırma tasarımının bütüncül değerlendirilmesi"]},
{code:"HRM81X",name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,purpose:"Öğrencinin harita mühendisliği alanında bağımsız bir araştırmayı etik ilkelere uygun tasarlaması, yürütmesi, çözümlemesi ve bilimsel olarak savunmasını sağlamak.",content:"Özgün harita mühendisliği araştırma problemi, literatür sentezi, araştırma tasarımı, saha etiği, veri üretimi, analiz, sürdürülebilirlik bağlamında yorum, tez yazımı ve savunma.",stages:["Araştırma probleminin kesinleştirilmesi","Literatür çerçevesinin güncellenmesi","Amaç ve hipotezlerin yapılandırılması","Yöntem ve örnekleme planı","Etik ve saha izinleri","Veri toplama planı","Saha kayıtları ve kalite kontrolü","Veri toplama sürecinin izlenmesi","Verilerin düzenlenmesi","Analizlerin yürütülmesi","Bulguların harita mühendisliği açısından yorumlanması","Bulguların literatürle karşılaştırılması","Tez bölümlerinin yazımı","Bütünlük ve etik denetimi","Savunma hazırlığı"]}];
const commons=specs.map((s)=>{const d=domain(s.name),aa=s.code==="HRM806"?[{name:"Seminer Metni ve Sunumu",count:1,weight:100}]:s.code==="HRM809"?[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]:[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Harita Mühendisliği ABD",programName:"Harita Mühendisliği",language:"Türkçe",level:"Tezli Yüksek Lisans",teachingMode:s.code==="HRM809"?"Yüz Yüze":"Bireysel Çalışma",prerequisites:"Yok",instructor:s.code==="HRM809"?"Dr. Öğr. Üyesi CEREN YAĞCI":"Öğrencinin Danışmanı",methods:"Literatür incelemesi, deneysel ve analitik verilerin çözümlemesi, mühendislik modellemesi, akademik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"Harita mühendisliği, geomatik, jeodezi, fotogrametri ve mekânsal bilgi teknolojileri alanındaki temel kaynaklar; güncel hakemli alan literatürü; Enstitü etik ve tez yazım yönergeleri.",sdgs:d.sdgs,outcomes:outcomes(s.name,d),weeklyTopics:s.stages,assessments:aa,workloads:workloads(s.ects,s.theory,s.practice,aa),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib","data","haritaMuhendisligiTezliCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const haritaMuhendisligiTezliCoursePackages: CoursePackage[] = ${JSON.stringify(academic,null,2)};\n`,"utf8");writeFileSync(path.join(process.cwd(),"lib","data","haritaMuhendisligiCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const haritaMuhendisligiCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commons,null,2)};\n`,"utf8");console.log(JSON.stringify({academic:academic.length,common:commons.length,missing:academic.filter((x)=>!x.sourceUrl).map((x)=>x.code),pc:pcs.length},null,2));





