import { readFileSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import path from "node:path";

const root=process.cwd(), department="Yönetim Bilişim Sistemleri ABD", programName="Yönetim Bilişim Sistemleri", level="Tezsiz Yüksek Lisans";
const sourcePath=process.argv[2]||"C:/Users/asus/OneDrive/Desktop/e-enstitü/bologna-lisansustu-2026-08-17-ders-verileri.json";
const officialPath=path.join(root,"data/courses/2026-2027.json"), allOfficial=JSON.parse(readFileSync(officialPath,"utf8"));
const official=allOfficial.filter(x=>x.department===department&&x.programName===programName&&x.level===level);
const fold=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i").replace(/\s+/g," ").trim();
const clean=s=>String(s||"").replace(/\s+/g," ").trim();
const sentence=s=>{const t=clean(s);if(!t||t!==t.toLocaleUpperCase("tr-TR"))return t;const l=t.toLocaleLowerCase("tr-TR");return l[0].toLocaleUpperCase("tr-TR")+l.slice(1);};
const cleanInstructor=s=>clean((s||"Atama Bekliyor").replace(/^Yrd\.?\s*Doç\.?\s*Dr\.?/iu,"Dr. Öğr. Üyesi").replace(/(?:https?:\/\/|www\.)\S+|\b\S+@\S+\b/giu," "));
const db=new DatabaseSync(path.join(root,"local-volume/data/dbp.sqlite"),{readOnly:true});
const profileRow=db.prepare("SELECT outcomes_json FROM program_profiles WHERE program_name=? AND level=?").get(programName,level);
const programOutcomes=JSON.parse(profileRow?.outcomes_json||"[]");
if(programOutcomes.length!==11)throw new Error(`11 mevcut PÇ bekleniyordu; bulunan ${programOutcomes.length}`);

const source=JSON.parse(readFileSync(sourcePath,"utf8")).data;
const sourceProgram=source.programs.find(x=>fold(x.name)==="yonetim bilisim sistemleri tezsiz yuksek lisans (i.o.)");
if(!sourceProgram)throw new Error("YBS tezsiz kaynak programı bulunamadı.");
const sourceCourses=new Map(source.courses.map(x=>[x.id,x]));
const sourceByCode=new Map(source.programCourses.filter(x=>x.program_id===sourceProgram.id).map(a=>{const c=sourceCourses.get(a.course_id);return[c.code,{course:c,assignment:a}];}));
const cells=row=>(row||[]).map(x=>clean(typeof x==="object"?(x?.text??x?.value??""):x));
const tables=c=>c?.package?.tables||[];
const findTable=(c,keys)=>tables(c).find(t=>{const h=fold(cells(t.rows?.[0]).join(" "));return keys.every(k=>h.includes(k));});
const detail=(c,label)=>{for(const t of tables(c))for(const r of t.rows||[]){const a=cells(r);if(fold(a[0]).includes(label)&&a.slice(1).join(" "))return clean(a.slice(1).join(" "));}return"";};
const sourceResources=c=>{const t=tables(c).find(x=>fold(x.title)==="ders kaynaklari");return(t?.rows||[]).map(r=>cells(r).filter(Boolean).join(": ")).filter(Boolean).join("; ");};

const domains={
 research:{label:"bilimsel araştırma ve yayın etiği",primary:[1,4,6,7,9,10],secondary:[0,2,3,5,8],sdgs:[4,16,17],topics:["Bilimsel bilgi ve Yönetim Bilişim Sistemleri araştırmasının niteliği","Araştırma problemi ve sorularının yapılandırılması","YBS alanında literatür tarama stratejileri","Kuramsal çerçeve ve araştırma modeli","Nitel araştırma tasarımları","Nicel araştırma tasarımları","Karma yöntem yaklaşımları","Veri kaynakları ve örnekleme","Veri toplama araçlarının değerlendirilmesi","YBS verilerinde çözümleme yaklaşımları","Geçerlik, güvenirlik ve araştırma kalitesi","Bilimsel yazım ve kaynak gösterme","Araştırma ve yayın etiği","Bulguların raporlanması","Araştırma tasarımının bütüncül değerlendirilmesi"]},
 management:{label:"yönetim ve örgüt",primary:[0,1,3,7,8],secondary:[2,6,9,10],sdgs:[4,8,9],topics:["Yönetim düşüncesinin kapsamı ve temel kavramlar","Klasik ve çağdaş yönetim yaklaşımları","Örgüt yapıları ve tasarım seçenekleri","Örgütsel çevre ve paydaş analizi","İnsan, teknoloji ve örgüt etkileşimi","İş bölümü, koordinasyon ve kontrol","Motivasyon, liderlik ve örgütsel davranış","Karar süreçleri ve bilgi gereksinimleri","Örgütsel değişim ve dönüşüm","Stratejik uyum ve kurumsal yetenekler","Dijitalleşmenin yönetim süreçlerine etkisi","Örgütsel performansın değerlendirilmesi","Etik ve toplumsal sorumluluk","Güncel yönetim yaklaşımlarının karşılaştırılması","Yönetim ve bilişim bilgisinin bütünleştirilmesi"]},
 systems:{label:"iş süreçleri ve bilgi sistemleri",primary:[0,1,2,3,7],secondary:[4,6,8,9,10],sdgs:[4,8,9],topics:["Bilgi sistemlerinin örgütsel rolü","İş süreçleri ve bilgi gereksinimleri","Sistem paydaşlarının belirlenmesi","Gereksinim toplama ve çözümleme","Süreç modelleme yaklaşımları","Sistem geliştirme yaşam döngüsü","Çözüm mimarisi ve tasarım ilkeleri","Veri, süreç ve kullanıcı bütünleşmesi","Sistem seçimi ve değerlendirme ölçütleri","Uygulama ve değişim yönetimi","Proje riskleri ve başarı faktörleri","Bilgi sistemi performansının ölçülmesi","Güvenlik, gizlilik ve etik gereksinimler","Kurumsal kullanım örneklerinin karşılaştırılması","Bilişim çözümünün bütüncül değerlendirilmesi"]},
 analytics:{label:"veri analitiği ve yapay zekâ",primary:[1,4,5,7],secondary:[0,2,3,6,8,9,10],sdgs:[4,9,12],topics:["Analitik problem ve veri gereksinimlerinin belirlenmesi","Veri kaynakları ve veri kalitesi","Veri ön işleme ve dönüştürme","Keşfedici veri çözümlemesi","Gözetimli öğrenme yaklaşımları","Gözetimsiz öğrenme yaklaşımları","Model seçimi ve kurma","Performans ölçütleri ve doğrulama","Sonuçların açıklanması ve yorumlanması","Karar desteği ve işletme uygulamaları","Büyük veri mimarileri ve analitik süreçler","Yapay zekâ çözümlerinin örgütsel etkileri","Önyargı, gizlilik ve etik riskler","Güncel analitik yaklaşımların karşılaştırılması","Analitik bulguların yönetsel değerlendirilmesi"]},
 marketing:{label:"pazarlama ve dijital iş",primary:[0,1,3,4,7],secondary:[2,6,8,9,10],sdgs:[4,8,12],topics:["Pazarlama yönetiminin kapsamı","Pazar ve müşteri bilgisinin yönetimi","Pazarlama araştırması problemi","Tüketici davranışı ve dijital temas noktaları","Pazar bölümlendirme ve hedefleme","Değer önerisi ve konumlandırma","Dijital pazarlama kanalları","Sosyal medya stratejisi","E-iş modelleri ve platformlar","Pazarlama verilerinin çözümlenmesi","Kampanya ve içerik performansı","Müşteri ilişkileri ve deneyim yönetimi","Gizlilik, etik ve tüketici hakları","Güncel dijital pazarlama uygulamaları","Pazarlama kararlarının bütüncül değerlendirilmesi"]},
 strategy:{label:"strateji, inovasyon ve girişimcilik",primary:[0,1,3,6,7,8],secondary:[2,4,9,10],sdgs:[4,8,9],topics:["Stratejik yönetimin kavramsal çerçevesi","Dış çevre ve sektör analizi","Kaynaklar, yetenekler ve rekabet üstünlüğü","Stratejik seçeneklerin geliştirilmesi","Teknoloji öngörüsü ve yol haritaları","İnovasyon türleri ve süreçleri","Girişim fırsatlarının değerlendirilmesi","İş modeli tasarımı","Dijital dönüşüm stratejileri","Teknoloji portföyü ve yatırım kararları","Proje ve risk yönetimi","Stratejinin uygulanması ve kontrolü","Etik, sürdürülebilirlik ve toplumsal etki","Güncel strateji ve inovasyon örnekleri","Stratejik kararların bütüncül değerlendirilmesi"]},
 decision:{label:"karar verme ve proje yönetimi",primary:[1,3,4,6,7],secondary:[0,2,5,8,9,10],sdgs:[4,8,9],topics:["Karar probleminin yapılandırılması","Amaç, ölçüt ve kısıtların belirlenmesi","Karar ortamında veri ve belirsizlik","Karar modellerinin sınıflandırılması","Çok ölçütlü karar yaklaşımları","Alternatiflerin değerlendirilmesi","Duyarlılık ve senaryo analizi","Proje kapsamı ve paydaş yönetimi","Zaman, maliyet ve kaynak planlama","Risklerin tanımlanması ve analizi","Proje izleme ve performans ölçümü","Karar destek sistemlerinin kullanımı","Etik ve yönetsel etkilerin değerlendirilmesi","Uygulama örneklerinin karşılaştırılması","Karar sonuçlarının bütüncül yorumlanması"]},
 knowledge:{label:"bilgi yönetimi ve dijital dönüşüm",primary:[0,1,3,7,8],secondary:[2,4,6,9,10],sdgs:[4,8,9],topics:["Veri, enformasyon ve bilgi kavramları","Örgütsel bilginin türleri","Bilginin oluşturulması ve paylaşılması","Bilgi yaşam döngüsü","Kurumsal hafıza ve öğrenen örgüt","Bilgi yönetimi stratejisi","Teknolojik altyapı ve bilgi platformları","Bilgi kalitesi ve erişilebilirlik","Toplumsal ve teknolojik dönüşüm","Dijital yetkinlikler ve örgütsel değişim","Bilgi güvenliği ve gizlilik","Bilgi yönetimi performansının ölçülmesi","Etik ve toplumsal etkiler","Güncel bilgi yönetimi yaklaşımları","Yönetim ve bilişim bilgisinin bütünleştirilmesi"]},
 technology:{label:"teknoloji tarihi ve toplumsal dönüşüm",primary:[0,3,8,9],secondary:[1,2,6,7,10],sdgs:[4,9,10],topics:["Bilim ve teknoloji kavramlarının tarihsel gelişimi","Teknolojik değişimi açıklayan yaklaşımlar","Sanayi devrimleri ve üretim sistemleri","Bilgi toplumunun oluşumu","Bilişim teknolojilerinin kurumsal gelişimi","İnternet ve platform ekonomisi","Otomasyon ve iş gücünün dönüşümü","Teknoloji, kültür ve gündelik yaşam","Dijital eşitsizlik ve erişim","Teknolojik yeniliklerin yönetişimi","Gizlilik, gözetim ve güvenlik","Yapay zekânın toplumsal etkileri","Etik ve düzenleyici tartışmalar","Güncel dönüşüm örneklerinin karşılaştırılması","Teknolojik dönüşümün bütüncül değerlendirilmesi"]},
 international:{label:"uluslararası işletmecilik",primary:[0,1,3,7,8],secondary:[2,4,9,10],sdgs:[4,8,17],topics:["Uluslararası işletmeciliğin kapsamı","Küresel iş çevresinin analizi","Kültürler arası yönetim","Uluslararası pazarlara giriş biçimleri","Çok uluslu işletme stratejileri","Küresel değer zincirleri","Uluslararası insan kaynakları yönetimi","Küresel bilgi sistemleri","Dijital platformlar ve sınır ötesi iş","Uluslararası risklerin değerlendirilmesi","Kurumsal yönetişim ve kontrol","Sürdürülebilirlik ve etik sorumluluk","Ülke ve sektör örneklerinin karşılaştırılması","Güncel küresel işletme eğilimleri","Uluslararası kararların bütüncül değerlendirilmesi"]}
};
function domainFor(name){const n=fold(name);if(/bilimsel arastirma|yayin etigi/.test(n))return domains.research;if(/veri madencil|makine ogren|yapay zeka|buyuk veri/.test(n))return domains.analytics;if(/pazarlama|sosyal medya|e- is|e-is/.test(n))return domains.marketing;if(/stratejik|stretejik|inovasyon|girisimcilik/.test(n))return domains.strategy;if(/karar verme|proje yonetimi/.test(n))return domains.decision;if(/sistem analizi|yonetim bilisim sistemleri/.test(n))return domains.systems;if(/bilgi yonetimi/.test(n))return domains.knowledge;if(/bilim ve teknoloji tarihi|toplumsal donusum/.test(n))return domains.technology;if(/uluslararasi/.test(n))return domains.international;return domains.management;}
const checklist=["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"];
const checks=hasSource=>checklist.map((item,i)=>({item,status:!hasSource&&[1,19,20].includes(i)?"Doğrulanmalı":[3,5,6,7,8,9,10,11,12,13,14,15,16,18].includes(i)?"Revize Edildi":"Uygun"}));
const outcomesFor=d=>[`${sentence(d.topics[0])} ile ilgili ileri kavramları analiz eder.`,`${sentence(d.topics[2])} bağlamındaki veri ve kanıtları eleştirel değerlendirir.`,`${sentence(d.topics[7])} ile ilişkili yönetsel veya teknik örnekleri karşılaştırır.`,`${sentence(d.topics[11])} için uygun çözümleme yaklaşımını uygular.`,`${sentence(d.topics[14])} temelinde gerekçeli çözüm önerisi geliştirir.`];
const matrixFor=d=>Array.from({length:5},(_,r)=>({outcome:`DÖÇ${r+1}`,values:programOutcomes.map((_,c)=>d.primary.includes(c)?[4,5,4,4,5][r]:d.secondary.includes(c)?[2,3,3,2,3][r]:[1,2,1,2,1][r])}));
const forbidden=/^(quiz|ödev|proje|sunum|konu\s+tekrar[ıi]|genel\s+tekrar|ara\s*sınav|arasınav|vize|yarıyıl\s+sonu\s+sınavı|final)$/iu;
const weeklyTopics=(c,d)=>{const t=findTable(c,["hafta","konu"]),raw=(t?.rows||[]).slice(1).map(cells).map(r=>sentence(r[1])).filter(x=>x&&!forbidden.test(x));const seen=new Set();return[...raw,...d.topics].filter(x=>{const k=fold(x);if(!k||seen.has(k))return false;seen.add(k);return true;}).slice(0,15);};
const assessmentsFor=c=>{const t=findTable(c,["yariyil","katki"])||tables(c).find(x=>fold(x.title)==="degerlendirme olcutleri");const rows=(t?.rows||[]).slice(1).map(cells).filter(r=>r[0]&&!fold(r[0]).startsWith("toplam")).map(r=>({name:sentence(r[0]),count:Number(r[1])||1,weight:Number(String(r.at(-1)).replace(/[^0-9.,]/g,"").replace(",","."))||0})).filter(x=>x.weight>0);return rows.length?rows:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}];};
const workloadsFor=(ects,theory,practice,ass)=>{const target=ects*30,rows=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of ass){const n=fold(a.name);if(n.includes("odev"))rows.push({name:"Ödev Hazırlığı",count:a.count,hours:8,total:a.count*8});else if(n.includes("proje"))rows.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))rows.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))rows.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25});}let left=target-rows.reduce((s,x)=>s+x.total,0),h=Math.max(0,Math.floor(left/15*2)/2);rows.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:h,total:15*h});left=target-rows.reduce((s,x)=>s+x.total,0);if(left)rows.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:left,total:left});return rows;};
const resourcesFor=(c,d)=>sourceResources(c)||`Laudon & Laudon, Management Information Systems; Turban, Pollard & Wood, Information Technology for Management; ${d.label} alanındaki güncel uluslararası standartlar ve hakemli araştırmalar.`;

const projectCodes=new Set(["YBS701","YBS702","YBS7XX"]),researchAliases=new Set(["YBS703","YBS704"]);
const academicRows=official.filter(x=>!projectCodes.has(x.code)&&x.code!=="YBS704"&&!/DANIŞMANLIK|UZMANLIK ALAN/iu.test(x.name));
const academic=academicRows.map(row=>{const src=sourceByCode.get(row.code),c=src?.course,d=domainFor(row.name),theory=Number(src?.assignment?.theory??row.theory),practice=Number(src?.assignment?.practice??row.practice),ects=Number(src?.assignment?.ects??row.ects)||6,ass=assessmentsFor(c),name=row.code==="YBS703"?"Bilimsel araştırma yöntemleri ve yayın etiği":sentence(c?.name||row.name);return{code:row.code,...(row.code==="YBS703"?{aliases:["YBS703","YBS704"]}:{}),name,department,programName,language:c?.language||"Türkçe",level,teachingMode:src?.assignment?.teaching_method||"Yüz Yüze",instructor:cleanInstructor(row.instructor||detail(c,"dersi verenler")),theory,practice,credit:Number(src?.assignment?.local_credit??row.credit),ects,prerequisites:"Yok",purpose:sentence(detail(c,"dersin amaci"))||`Bu dersin, öğrencilerin ${d.label} alanındaki ileri bilgileri yönetsel ve bilişimsel bir yaklaşımla çözümlemelerine katkı sağlaması amaçlanmaktadır.`,content:sentence(detail(c,"dersin icerigi"))||`${sentence(d.topics.slice(0,10).join("; "))} başlıkları Yönetim Bilişim Sistemleri bağlamında ele alınmaktadır.`,methods:sentence(detail(c,"dersin yontem"))||"Kuramsal anlatım, yönlendirilmiş tartışma, örnek olay incelemesi, veri ve süreç çözümlemesi ile bireysel çalışma.",resources:resourcesFor(c,d),sdgs:d.sdgs.map(String),outcomes:outcomesFor(d),weeklyTopics:weeklyTopics(c,d),assessments:ass,workloads:workloadsFor(ects,theory,practice,ass),contributionMatrix:matrixFor(d),...(c?.source_url?{sourceUrl:c.source_url}:{}),qualityChecks:checks(Boolean(c?.source_url)),publicQualityChecklist:false};});
const projectSource=sourceByCode.get("YBS702")?.course,projectDomain=domains.systems;
const project={code:"YBS7XX",aliases:["YBS701","YBS702"],name:"Bitirme Projesi",department,programName,language:"Türkçe",level,teachingMode:"Bireysel Proje Çalışması",instructor:"Öğrencinin Danışmanı",theory:0,practice:0,credit:0,ects:30,prerequisites:"Yok",purpose:"Öğrencinin yönetim ve bilişim alanındaki ileri bilgi ve çözümleme becerilerini örgütsel bir problem üzerinde bütünleştirerek bilimsel ve etik ölçütlere uygun bir bitirme projesi yürütmesini sağlamak.",content:"YBS probleminin belirlenmesi, kaynak ve veri incelemesi, yöntem ile çalışma planının geliştirilmesi, yönetsel ve bilişimsel bulguların çözümlenmesi, sonuçların örgütsel bağlamda yorumlanması ve projenin akademik biçimde raporlanması.",methods:"Bireysel proje çalışması, danışman görüşmesi, literatür ve veri incelemesi, süreç veya sistem çözümlemesi, akademik yazım ve yapılandırılmış geri bildirim.",resources:resourcesFor(projectSource,projectDomain),sdgs:["4","8","9"],outcomes:["Örgütsel bir bilişim problemini uygulanabilir proje sorusuna dönüştürür.","Proje problemine ilişkin akademik ve mesleki kaynakları eleştirel değerlendirir.","Projenin amacına uygun veri, yöntem ve çalışma planı geliştirir.","Yönetsel ve bilişimsel bulguları örgütsel bağlamda yorumlar.","Bitirme projesini bilimsel yazım ve etik ilkelerine uygun raporlar."],weeklyTopics:["Proje alanının ve kapsamının belirlenmesi","Örgütsel bilişim probleminin sınırlandırılması","Amaç ve proje sorularının geliştirilmesi","Literatür tarama stratejisinin oluşturulması","Kuramsal ve mesleki kaynakların değerlendirilmesi","Paydaş, süreç ve bilgi gereksinimlerinin belirlenmesi","Yöntem ile çalışma planının geliştirilmesi","Veri kaynaklarının ve çözümleme birimlerinin yapılandırılması","Etik, gizlilik ve veri güvenliği gereksinimlerinin değerlendirilmesi","Yönetsel ve bilişimsel verilerin düzenlenmesi","Bulguların çözümlenmesi ve yorumlanması","Bulguların alan yazını ve örgütsel gereksinimlerle karşılaştırılması","Çözüm önerileri ve mesleki çıkarımların geliştirilmesi","Akademik metin, atıf ve kaynakça düzeninin denetlenmesi","Bitirme projesinin teslimi ve değerlendirilmesi"],assessments:[{name:"Başarılı / Başarısız",count:1,weight:100}],workloads:[{name:"Proje Planlama ve Danışman Görüşmeleri",count:15,hours:2,total:30},{name:"Literatür ve Veri İncelemesi",count:15,hours:20,total:300},{name:"Çözümleme ve Raporlama",count:15,hours:36,total:540},{name:"Nihai Düzenleme ve Teslim",count:1,hours:30,total:30}],contributionMatrix:matrixFor(projectDomain),...(projectSource?.source_url?{sourceUrl:projectSource.source_url}:{}),qualityChecks:checks(Boolean(projectSource?.source_url)),publicQualityChecklist:false};
if(academic.length!==24)throw new Error(`24 akademik ders bekleniyordu; bulunan ${academic.length}`);
for(const c of [...academic,project]){if(c.weeklyTopics.length!==15||new Set(c.weeklyTopics.map(fold)).size!==15)throw new Error(`${c.code}: 15 benzersiz hafta yok`);if(c.code!=="YBS7XX"&&c.weeklyTopics.some(x=>forbidden.test(x)))throw new Error(`${c.code}: yasak başlık`);if(c.outcomes.length!==5||c.contributionMatrix.some(r=>r.values.length!==11||r.values.some(v=>v<1||v>5)))throw new Error(`${c.code}: DÖÇ-PÇ`);if(c.workloads.reduce((s,x)=>s+x.total,0)!==c.ects*30||!c.workloads.every(x=>Number.isInteger(x.hours*2)))throw new Error(`${c.code}: iş yükü`);if(c.assessments.some(x=>/Ödev/iu.test(x.name))&&!c.workloads.some(x=>/Ödev/iu.test(x.name)))throw new Error(`${c.code}: ödev iş yükünde değil`);if(c.qualityChecks.length!==21||c.publicQualityChecklist!==false)throw new Error(`${c.code}: kontrol`);}
const emit=(file,name,value)=>writeFileSync(path.join(root,"lib/data",file),`// YBS tezsiz resmî müfredatı, gerçek OBS paketleri ve mevcut 11 LEE_DBP PÇ'si temel alınmıştır; program profili değiştirilmemiştir.\nimport type { CoursePackage } from "./coursePackages";\n\nexport const ${name}: CoursePackage[] = ${JSON.stringify(value,null,2)};\n`);
emit("ybsTezsizCoursePackages.ts","ybsTezsizCoursePackages",academic);emit("ybsTezsizCommonCoursePackages.ts","ybsTezsizCommonCoursePackages",[project]);
const normalized=[...academicRows.map(row=>{const src=sourceByCode.get(row.code);return{...row,name:row.code==="YBS703"?"Bilimsel araştırma yöntemleri ve yayın etiği":sentence(src?.course?.name||row.name),...(row.code==="YBS703"?{term:"Güz ve Bahar"}:{}),theory:Number(src?.assignment?.theory??row.theory),practice:Number(src?.assignment?.practice??row.practice),credit:Number(src?.assignment?.local_credit??row.credit),ects:Number(src?.assignment?.ects??row.ects),instructor:row.instructor?cleanInstructor(row.instructor):undefined};}),{academicYear:"2026-2027",programCode:"",department,programName,level,code:"YBS7XX",name:"Bitirme Projesi",type:"Zorunlu",credit:0,ects:30,theory:0,practice:0,term:"Güz ve Bahar",instructor:"Öğrencinin Danışmanı",status:"İncelemede",source:"official_excel"}];
const rest=allOfficial.filter(x=>!(x.department===department&&x.programName===programName&&x.level===level));const at=rest.findIndex(x=>x.department===department&&x.programName===programName&&x.level==="Tezli Yüksek Lisans");rest.splice(at<0?rest.length:at,0,...normalized);writeFileSync(officialPath,`${JSON.stringify(rest,null,2)}\n`);
console.log(JSON.stringify({sourceAssignments:sourceByCode.size,academic:academic.length,common:1,official:normalized.length,outcomes:programOutcomes.length,missing:academic.filter(x=>!x.sourceUrl).map(x=>x.code)}));
