import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const sourcePath = process.argv[2] || process.env.BOLOGNA_DERS_JSON;
if (!sourcePath) throw new Error("Kullanım: node scripts/generate_makine_muhendisligi_doktora_course_packages.mjs <ders-verileri.json>");
const fold=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("tr-TR").replace(/ı/g,"i");
const clean=(v="")=>String(v).replace(/\s+/g," ").trim();
const title=(v="")=>{const s=clean(v).toLocaleLowerCase("tr-TR");return s?`${s[0].toLocaleUpperCase("tr-TR")}${s.slice(1)}`:s};
const data=JSON.parse(readFileSync(sourcePath,"utf8")).data;
const program=data.programs.find((x)=>fold(x.name)==="makine muhendisligi doktora");
if(!program)throw new Error("Makine Mühendisliği Doktora programı bulunamadı.");
const pc=[
"İleri makine mühendisliği bilgilerini özgün araştırma problemlerinin çözümünde eleştirel biçimde sentezler.",
"Karmaşık mühendislik problemlerine yönelik özgün araştırma soruları ve hipotezler geliştirir.",
"Makine mühendisliği araştırmaları için yenilikçi deneysel ve hesaplamalı yöntemler geliştirir.",
"Karmaşık mühendislik verilerini ileri analitik ve sayısal yöntemlerle analiz eder.",
"Araştırma bulgularını güncel uluslararası mühendislik literatürü bağlamında eleştirel değerlendirir.",
"Makine mühendisliği alanında bağımsız ve özgün bilimsel araştırmaları tasarlar ve yürütür.",
"Özgün araştırma sonuçlarıyla Makine Mühendisliği bilim alanına yeni bilgi kazandırır.",
"Karmaşık mühendislik problemlerinde farklı disiplinlerin bilgi ve yöntemlerini bütünleştirir.",
"Araştırmalarda mühendislik etiği, bilimsel dürüstlük ve sürdürülebilirlik ilkelerini uygular.",
"Özgün araştırma sonuçlarını uluslararası yayınlarda ve akademik ortamlarda savunur.",
"Mühendislik problemlerine yönelik yenilikçi, güvenli ve sürdürülebilir teknolojik çözümler geliştirir."
];
const official=JSON.parse(readFileSync(path.join(process.cwd(),"data","courses","2026-2027.json"),"utf8")).filter((x)=>x.department==="Makine Mühendisliği ABD"&&x.programName==="Makine Mühendisliği"&&x.level==="Doktora");
const cmap=new Map(data.courses.map((x)=>[x.id,x]));
const sourceByCode=new Map(data.programCourses.filter((x)=>x.program_id===program.id).map((a)=>{const c=cmap.get(a.course_id);return[c.code,{course:c,assignment:a}]}));
const cells=(row)=>Array.isArray(row)?row.map((x)=>clean(typeof x==="object"?(x?.text??x?.value??""):x)):[];
const tables=(c)=>c?.package?.tables||[];
const detail=(c,label)=>{for(const t of tables(c))for(const r of t.rows||[]){const a=cells(r);if(fold(a[0]).includes(fold(label))&&a.slice(1).join(" "))return clean(a.slice(1).join(" "))}return""};
const table=(c,keys)=>tables(c).find((t)=>{const h=fold(cells(t.rows?.[0]||[]).join(" "));return keys.every((k)=>h.includes(k))});
const domainFor=(name)=>{const n=fold(name);if(/gelisim|ogrenme/.test(n))return{label:"gelişim ve öğrenme",terms:["gelişim ve öğrenmenin bilimsel temelleri","bilişsel ve duyuşsal gelişim","davranışçı öğrenme yaklaşımları","bilişsel öğrenme yaklaşımları","yapılandırmacı öğrenme","yetişkin öğrenmesi","bireysel farklılıklar","kapsayıcı öğrenme ortamları"],core:[1,2,5,8,10],sdgs:[4,10]};if(/ogretimde|planlama|degerlendirme/.test(n))return{label:"öğretim tasarımı ve değerlendirme",terms:["program geliştirme kavramları","öğrenme çıktılarının yapılandırılması","içerik seçimi ve düzenlenmesi","öğretim stratejileri","öğretim materyalleri","ölçme araçlarının geliştirilmesi","geçerlik ve güvenirlik","değerlendirme verilerinin yorumlanması"],core:[2,4,5,8,10],sdgs:[4,10]};if(/arastirma|yayin|etik/.test(n))return{label:"bilimsel araştırma ve yayın etiği",terms:["araştırma problemi ve hipotez","deneysel ve hesaplamalı araştırma tasarımı","örnekleme ve veri üretimi","geçerlik ve güvenirlik","ileri veri analizi","bilimsel yazım","araştırma bütünlüğü","yayın etiği"],core:[2,4,6,9,10],sdgs:[4,9,16]};return{label:"ileri makine mühendisliği modelleme yöntemleri",terms:["mühendislik probleminin matematiksel tanımı","model varsayımları ve sınır koşulları","analitik modelleme yaklaşımları","sayısal çözüm yöntemleri","sonlu elemanlar ve hesaplamalı yöntemler","model doğrulama ve geçerleme","duyarlılık ve belirsizlik analizi","mühendislik sonuçlarının yorumlanması"],core:[1,2,3,4,6],sdgs:[9,12,13]}};
const weeks=(name,d)=>[`${title(name)} dersinin kapsamı ve doktora düzeyindeki araştırma problemleri`,...d.terms.map(title),`${title(d.label)} yaklaşımlarının eleştirel karşılaştırılması`,`${title(name)} kapsamında veri ve kanıtların değerlendirilmesi`,`${title(name)} uygulamalarında etik, güvenlik ve sürdürülebilirlik`,`${title(name)} alanındaki güncel uluslararası araştırmalar`,`${title(name)} için özgün araştırma yaklaşımının geliştirilmesi`,`${title(name)} bilgilerinin bilimsel bir çerçevede bütünleştirilmesi`].slice(0,15);
const outcomes=(name,d)=>[`${title(name)} kapsamındaki ileri kuramsal bilgileri eleştirel biçimde analiz eder.`,`${title(d.label)} alanındaki yöntemleri karşılaştırır.`,`${title(name)} için bilimsel gerekçeli bir model veya araştırma yaklaşımı geliştirir.`,`${title(name)} bulgularını güvenlik, etik ve sürdürülebilirlik ölçütleriyle değerlendirir.`,`${title(name)} alanındaki araştırma sonuçlarını bilimsel bütünlük içinde yorumlar ve savunur.`];
const matrix=(d)=>[[d.core[0],2,5],[d.core[1],3,4],[d.core[2],3,6],[5,8,11],[6,7,9,10]].map((targets,r)=>({outcome:`DÖÇ${r+1}`,values:pc.map((_,i)=>targets.includes(i+1)?5:(d.core.includes(i+1)?4:((i+r)%3===0?3:(i+r)%2+1)))}));
const assessments=(c)=>{const t=table(c,["yariyil","katki"])||tables(c).find((x)=>fold(x.title)==="degerlendirme olcutleri"),r=(t?.rows||[]).slice(1).map(cells).filter((x)=>x[0]&&Number(String(x.at(-1)).replace(",","."))>0).map((x)=>({name:x[0],count:Number(x[1])||1,weight:Number(String(x.at(-1)).replace(",","."))}));return r.length?r:[{name:"Ara Sınav",count:1,weight:40},{name:"Yarıyıl Sonu Sınavı",count:1,weight:60}]};
const workloads=(ects,theory,practice,ass)=>{const target=ects*30,r=[{name:"Ders Süresi",count:15,hours:theory+practice,total:15*(theory+practice)}];for(const a of ass){const n=fold(a.name);if(n.includes("odev"))r.push({name:"Ödev Hazırlığı",count:a.count,hours:6,total:a.count*6});else if(n.includes("proje"))r.push({name:"Proje Çalışması",count:a.count,hours:10,total:a.count*10});else if(n.includes("ara sinav"))r.push({name:"Ara Sınav Hazırlığı",count:a.count,hours:20,total:a.count*20});else if(n.includes("yariyil sonu"))r.push({name:"Yarıyıl Sonu Sınavı Hazırlığı",count:a.count,hours:25,total:a.count*25})}let left=target-r.reduce((s,x)=>s+x.total,0),h=Math.max(0,Math.floor(left/15*2)/2);r.splice(1,0,{name:"Sınıf Dışı Çalışma Süresi",count:15,hours:h,total:15*h});left=target-r.reduce((s,x)=>s+x.total,0);if(left)r.push({name:"Kaynak İnceleme ve Akademik Hazırlık",count:1,hours:left,total:left});return r};
const checks=(source)=>["Ders adı ve kodları doğrulandı mı?","Tüm OBS linkleri gerçek mi?","Dersin program düzeyi doğru mu?","Ders amacı açık ve uygun mu?","Ders amacı program düzeyine uygun mu?","DÖÇ sayısı ve kapsamı uygun mu?","DÖÇ'ler ölçülebilir mi?","Bloom fiilleri uygun mu?","Bloom düzeyi program düzeyine uygun mu?","Amaç–DÖÇ uyumu sağlandı mı?","DÖÇ–içerik uyumu sağlandı mı?","İçerik–haftalık plan uyumu sağlandı mı?","DÖÇ–öğretim yöntemi uyumu sağlandı mı?","DÖÇ–ölçme/değerlendirme uyumu sağlandı mı?","AKTS–iş yükü tutarlı mı?","DÖÇ–PÇ matrisi gerçekçi mi?","1–5 katkı düzeyleri doğru kullanılmış mı?","Yapay yüksek ilişkilendirme var mı?","Tekrarlı kodlar doğru tekilleştirildi mi?","Kaynakta olmayan bilgi kesin bilgi gibi yazılmış mı?","Eksik/doğrulanması gereken alan kaldı mı?"].map((item,i)=>({item,status:!source&&(i===1||i===20)?"Doğrulanmalı":([3,5,6,7,9,10,11,12,14,15,16].includes(i)?"Revize Edildi":"Uygun")}));
const common=/^(DAN90[1-8]|MMB90[1-9]|MMB910|MMB91[2-8])$/u;
const forbidden=/(quiz|ödev|proje|sunum|konu\s+tekrarı|genel\s+tekrar|ara\s*sınav|arasınav|vize(?: sınavı)?|yarıyıl\s+sonu\s+sınavı|final(?: sınavı)?)/iu;
const overrides={
PFE901:{purpose:"Gelişim ve öğrenme kuramlarını doktora düzeyindeki öğretim, araştırma ve akademik rehberlik süreçleri bağlamında eleştirel değerlendirme yetkinliği kazandırmak.",content:"Bilişsel, duyuşsal ve sosyal gelişim; davranışçı, bilişsel, yapılandırmacı ve yetişkin öğrenmesi yaklaşımları; bireysel farklılıklar, üst düzey düşünme ve kapsayıcı öğrenme ortamları.",resources:"Gelişim psikolojisi, öğrenme psikolojisi ve yetişkin öğrenmesi alanındaki temel eserler ile güncel hakemli eğitim araştırmaları; kesin kaynak seçimi öğretim elemanı tarafından doğrulanmalıdır."},
PFE942:{purpose:"Doktora düzeyinde öğrenme çıktısı temelli öğretim tasarlama ve geçerli, güvenilir değerlendirme süreçleri geliştirme yetkinliği kazandırmak.",content:"Program geliştirme, öğrenme çıktıları, içerik düzenleme, öğretim stratejileri, materyal seçimi, ölçme aracı geliştirme, geçerlik, güvenirlik, değerlendirme verilerinin analizi ve eğitimde etik.",resources:"Öğretim tasarımı, program geliştirme ve eğitimde ölçme-değerlendirme alanındaki temel eserler ile güncel hakemli eğitim araştırmaları; kesin kaynak seçimi öğretim elemanı tarafından doğrulanmalıdır."}
};
const academics=official.filter((o)=>!common.test(o.code)&&o.code!=="MMB950").map((o)=>{const src=sourceByCode.get(o.code),c=src?.course,courseName=clean(c?.name||o.name),d=domainFor(courseName),a=assessments(c),theory=Number(src?.assignment?.theory??o.theory),practice=Number(src?.assignment?.practice??o.practice),wt=(()=>{const t=table(c,["hafta","konu"]),raw=(t?.rows||[]).slice(1).map(cells).map((x)=>x[1]).filter((x)=>x&&!forbidden.test(x));return[...new Set([...raw,...weeks(courseName,d)])].slice(0,15)})();const generated=overrides[o.code]||{};return{...o,name:courseName,theory,practice,credit:Number(src?.assignment?.local_credit??o.credit),ects:6,status:undefined,source:undefined,purpose:generated.purpose||detail(c,"dersin amaci")||`${title(courseName)} alanındaki ileri kuramsal ve hesaplamalı yaklaşımları doktora düzeyinde eleştirel değerlendirme yetkinliği kazandırmak.`,content:generated.content||detail(c,"dersin icerigi")||`${title(courseName)}; ${d.terms.join(", ")} boyutlarıyla ele alınır.`,methods:detail(c,"dersin yontem")||"Kuramsal anlatım, ileri problem çözme, bilimsel kaynak incelemesi, modelleme ve mühendislik bulgularının eleştirel tartışılması.",resources:generated.resources||(c?.source_url?"Dersin gerçek OBS kaynakları; güncel makine mühendisliği literatürü, hakemli makaleler ve ilgili ulusal/uluslararası standartlar.":"Güncel makine mühendisliği literatürü, hakemli makaleler ve ilgili ulusal/uluslararası standartlar; kesin kaynak seçimi öğretim elemanı tarafından doğrulanmalıdır."),sdgs:d.sdgs.map(String),outcomes:outcomes(courseName,d),weeklyTopics:wt,assessments:a,workloads:workloads(6,theory,practice,a),contributionMatrix:matrix(d),sourceUrl:c?.source_url,qualityChecks:checks(Boolean(c?.source_url)),publicQualityChecklist:false}});
const commonSpecs=[
{code:"DAN9XX",aliases:["DAN901","DAN902","DAN903","DAN904","DAN905","DAN906","DAN907","DAN908"],name:"DANIŞMANLIK",theory:0,practice:1,credit:0,ects:1,core:[2,6,9,10,7]},
{code:"MMB9XX",aliases:["MMB901","MMB902","MMB903","MMB904","MMB905","MMB906","MMB907","MMB908"],name:"UZMANLIK ALAN DERSİ",theory:4,practice:0,credit:0,ects:5,core:[1,3,5,6,7]},
{code:"MMB909",aliases:["MMB909","MMB910"],name:"SEMİNER",theory:0,practice:0,credit:0,ects:6,core:[2,5,8,10,7]},
{code:"MMB917",aliases:["MMB917","MMB918"],name:"DOKTORA YETERLİK",theory:0,practice:0,credit:0,ects:24,core:[1,2,3,4,10]},
{code:"MMB91X",aliases:["MMB912","MMB913","MMB914","MMB915","MMB916"],name:"TEZ ÇALIŞMASI",theory:0,practice:0,credit:0,ects:24,core:[2,6,7,9,10]}
];
const processStages={
DAN9XX:["Doktora çalışma planının oluşturulması","Makine mühendisliği uzmanlık alanının sınırlandırılması","İleri literatür tarama stratejisinin değerlendirilmesi","Özgün araştırma probleminin netleştirilmesi","Etik ve güvenlik gerekliliklerinin değerlendirilmesi","Hipotez ve araştırma tasarımının gözden geçirilmesi","Deneysel veya hesaplamalı çalışma planının değerlendirilmesi","Araştırma kayıtları ve kalite güvencesi","Bulguların eleştirel ön değerlendirmesi","İleri analiz yaklaşımının gözden geçirilmesi","Bilimsel yayın planının oluşturulması","Kaynak ve araştırma bütünlüğü denetimi","Araştırma sınırlılıklarının değerlendirilmesi","Doktora ilerlemesi ve özgün katkının izlenmesi","Sonraki dönem araştırma hedeflerinin kararlaştırılması"],
MMB9XX:["Doktora tez alanının bilimsel kapsamı","Güncel makine mühendisliği literatürünün eleştirel sınıflandırılması","Kuramsal, deneysel ve hesaplamalı yaklaşımların sentezlenmesi","Uluslararası literatürde araştırma boşluğunun belirlenmesi","Özgün araştırma sorularının geliştirilmesi","Hipotezlerin mühendislik ilkeleriyle temellendirilmesi","İleri modelleme ve deneysel yöntemlerin karşılaştırılması","Araştırma tasarımının değerlendirilmesi","Ölçüm, veri üretimi ve doğrulama yöntemleri","Belirsizlik, veri kalitesi ve tekrarlanabilirlik","İleri analiz seçeneklerinin karşılaştırılması","Bulguların mühendislik açısından yorumlanması","Güvenlik, sürdürülebilirlik ve etik riskler","Özgün katkı ve sınırlılıkların tartışılması","Kuramsal ve yöntemsel çerçevenin bütünleştirilmesi"],
MMB909:["Seminer konusunun özgünlük ve kapsam bakımından belirlenmesi","İleri araştırma sorusunun geliştirilmesi","Sistematik literatür tarama stratejisinin kurulması","Kaynakların kanıt düzeyi bakımından değerlendirilmesi","Literatürün kavramsal sınıflandırılması","Sayısal ve deneysel kanıtların karşılaştırılması","Seminer metninin bilimsel yapısının oluşturulması","Yöntem ve bulguların eleştirel sentezi","Tablo ve görsellerin bilimsel düzenlenmesi","Doktora düzeyinde tartışmanın yapılandırılması","Özgün mühendislik çıkarımlarının geliştirilmesi","Atıf ve kaynakça bütünlüğünün denetlenmesi","Akademik anlatım tasarımının geliştirilmesi","Bilimsel savunmanın yürütülmesi","Geri bildirimle nihai metnin geliştirilmesi"],
MMB917:["Yeterlik kapsamındaki makine mühendisliği alanlarının belirlenmesi","İleri alan bilgisinin sistematik incelenmesi","Makine mühendisliği alt alanlarının sentezi","Karmaşık mühendislik problemlerinin bilimsel çözümlemesi","Özgün araştırma sorusu geliştirme","Hipotezlerin eleştirel değerlendirilmesi","Modelleme yaklaşımlarının karşılaştırılması","Deneysel yöntem ve örnekleme seçimi","Ölçüm belirsizliği ve geçerlik ölçütleri","İleri sayısal ve istatistiksel çözümleme","Bulguların uluslararası literatür bağlamında yorumlanması","Bilimsel etik, güvenlik ve araştırma bütünlüğü","Sürdürülebilirlik ve toplumsal etkilerin değerlendirilmesi","Bilimsel argümanın yazılı yapılandırılması","Bilimsel argümanın sözlü savunulması"],
MMB91X:["Özgün araştırma probleminin kesinleştirilmesi","İleri literatür çerçevesinin güncellenmesi","Araştırma amaç ve hipotezlerinin yapılandırılması","Yenilikçi model veya deney planının kesinleştirilmesi","Etik, güvenlik ve kurumsal gereklilikler","Veri üretim sürecinin planlanması","Araştırma kayıtları ve kalite kontrolü","Deneysel veya hesaplamalı sürecin izlenmesi","Verilerin düzenlenmesi ve doğrulanması","İleri analizlerin yürütülmesi","Bulguların mühendislik açısından yorumlanması","Özgün katkının literatürle karşılaştırılması","Bilimsel yayın ve tez bölümlerinin yazımı","Tez metninin bütünlük ve etik denetimi","Doktora savunması ve bilimsel katkının sunulması"]};
const commonPackages=commonSpecs.map((s)=>{const d={...domainFor(s.name),core:s.core},a=[{name:"Başarılı / Başarısız",count:1,weight:100}];return{...s,department:"Makine Mühendisliği ABD",programName:"Makine Mühendisliği",language:"Türkçe",level:"Doktora",teachingMode:"Bireysel Çalışma",prerequisites:"Yok",instructor:"Öğrencinin Danışmanı",purpose:`${title(s.name)} kapsamında makine mühendisliği alanındaki bilimsel gelişimi, özgün araştırma yetkinliğini ve akademik etik farkındalığını geliştirmek.`,content:"Makine mühendisliği alanına özgü ileri literatür, araştırma problemi, kuramsal çerçeve, yöntem seçimi, veri yorumlama, bilimsel yazım ve araştırma etiği süreçleri.",methods:"Literatür incelemesi, akademik tartışma, bireysel araştırma ve danışmanlık görüşmesi.",resources:"Güncel makine mühendisliği literatürü; ulusal ve uluslararası mühendislik standartları ve veri kaynakları; bilimsel araştırma ve yayın etiği rehberleri.",sdgs:d.sdgs.map(String),outcomes:outcomes(s.name,d),weeklyTopics:processStages[s.code],assessments:a,workloads:workloads(s.ects,s.theory,s.practice,a),contributionMatrix:matrix(d),qualityChecks:checks(true),publicQualityChecklist:false}});
writeFileSync(path.join(process.cwd(),"lib/data/makineMuhendisligiDoktoraCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const makineMuhendisligiDoktoraCoursePackages: CoursePackage[] = ${JSON.stringify(academics,null,2)};\n`);
writeFileSync(path.join(process.cwd(),"lib/data/makineMuhendisligiDoktoraCommonCoursePackages.ts"),`import type { CoursePackage } from "./coursePackages";\nexport const makineMuhendisligiDoktoraCommonCoursePackages: CoursePackage[] = ${JSON.stringify(commonPackages,null,2)};\n`);
console.log(JSON.stringify({academic:academics.length,common:commonPackages.length,missing:academics.filter((x)=>!x.sourceUrl).map((x)=>x.code)}));
